-- Oracle DDL Statements for Stellar Staging Tables
-- Staging tables for ETL data loading
-- These tables receive data from source systems before transformation and loading into warehouse tables

-- ====================================================================
-- CORE BUSINESS TABLES
-- ====================================================================

-- Locations Table (Marina/Business locations)
CREATE TABLE STG_STELLAR_LOCATIONS (
    ID NUMBER(10,0),
    CODE NVARCHAR2(191),
    LOCATION_NAME NVARCHAR2(191),
    LOCATION_TYPE NUMBER(1,0),
    MINIMUM_1 NUMBER(10,2),
    MINIMUM_2 NUMBER(10,2),
    DELIVERY NUMBER(10,2),
    FRONTEND NUMBER(1,0),
    PRICING NUMBER(1,0),
    IS_INTERNAL NUMBER(1,0) DEFAULT 0,
    IS_CANCELED NUMBER(1,0) DEFAULT 0,
    CANCEL_REASON NVARCHAR2(191),
    CANCEL_DATE DATE,
    IS_TRANSFERRED NUMBER(1,0) DEFAULT 0,
    TRANSFER_DESTINATION NVARCHAR2(50),
    MODULE_TYPE NVARCHAR2(20),
    OPERATING_LOCATION NVARCHAR2(191),
    ZOHO_ID NVARCHAR2(20),
    ZCRM_ID NVARCHAR2(50),
    IS_ACTIVE NUMBER(1,0) DEFAULT 1,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Customers Table (Core customer information)
CREATE TABLE STG_STELLAR_CUSTOMERS (
    USER_ID NUMBER(10,0),
    CLUB_PRINCIPAL_USER_ID NUMBER(10,0),
    COUPON_ID NUMBER(10,0),
    CLUB_TIER_ID NUMBER(10,0),
    FIRST_NAME NVARCHAR2(191),
    LAST_NAME NVARCHAR2(191),
    MIDDLE_NAME NVARCHAR2(191),
    GENDER NVARCHAR2(10),
    PHONE NVARCHAR2(25),
    CELL NVARCHAR2(25),
    EMERGENCY_NAME NVARCHAR2(191),
    EMERGENCY_PHONE NVARCHAR2(25),
    SECONDARY_EMAIL NCLOB,
    BILLING_STREET1 NVARCHAR2(191),
    BILLING_STREET2 NVARCHAR2(191),
    BILLING_CITY NVARCHAR2(191),
    BILLING_STATE NVARCHAR2(191),
    BILLING_COUNTRY CHAR(3) DEFAULT 'USA',
    BILLING_ZIP NVARCHAR2(12),
    MAILING_STREET1 NVARCHAR2(191),
    MAILING_STREET2 NVARCHAR2(191),
    MAILING_CITY NVARCHAR2(191),
    MAILING_STATE NVARCHAR2(191),
    MAILING_COUNTRY CHAR(3) DEFAULT 'USA',
    MAILING_ZIP NVARCHAR2(12),
    NUM_KIDS NVARCHAR2(10),
    REFERRER NVARCHAR2(191),
    SERVICES NVARCHAR2(191),
    DATE_OF_BIRTH NVARCHAR2(30),
    DL_STATE NVARCHAR2(50),
    DL_COUNTRY CHAR(3) DEFAULT 'USA',
    DL_NUMBER NVARCHAR2(40),
    NOTES NCLOB,
    INTERNAL_NOTES NCLOB,
    CLUB_STATUS NVARCHAR2(20),
    CLUB_START_DATE DATE,
    CLUB_USE_RECURRING_BILLING NVARCHAR2(3) DEFAULT 'No',
    CLUB_RECURRING_BILLING_START_DATE DATE,
    BALANCE NUMBER(10,2),
    BOAT_DAMAGE_RESPONSIBILITY_COVERAGE NVARCHAR2(3),
    PENALTY_POINTS NUMBER(10,0),
    OPEN_BALANCE_THRESHOLD NUMBER(10,0),
    CLUB_END_DATE DATE,
    CC_SAVED_NAME NVARCHAR2(191),
    CC_SAVED_LAST4 NUMBER(4,0),
    CC_SAVED_EXPIRY DATE,
    CC_SAVED_PROFILE_ID NVARCHAR2(191),
    CC_SAVED_METHOD_ID NVARCHAR2(191),
    CC_SAVED_ADDRESS_ID NVARCHAR2(191),
    EXTERNAL_ID NVARCHAR2(191),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Bookings Table (Main reservation/booking records)
CREATE TABLE STG_STELLAR_BOOKINGS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    CUSTOMER_ID NUMBER(10,0),
    CREATOR_ID NUMBER(10,0),
    ADMIN_ID NUMBER(10,0),
    BILLING_FIRST_NAME NVARCHAR2(191),
    BILLING_LAST_NAME NVARCHAR2(191),
    BILLING_STREET1 NVARCHAR2(191),
    BILLING_STREET2 NVARCHAR2(191),
    BILLING_CITY NVARCHAR2(191),
    BILLING_STATE NVARCHAR2(191),
    BILLING_COUNTRY CHAR(3) DEFAULT 'USA',
    BILLING_ZIP NVARCHAR2(15),
    CC_SAVED_NAME NVARCHAR2(191),
    CC_SAVED_LAST4 NUMBER(4,0),
    CC_SAVED_PROFILE_ID NVARCHAR2(191),
    CC_SAVED_METHOD_ID NVARCHAR2(191),
    CC_SAVED_ADDRESS_ID NVARCHAR2(191),
    CC_PREAUTH_ID NVARCHAR2(191),
    CC_PREAUTH_AMOUNT NUMBER(10,2),
    CC_CONNECT_TYPE NVARCHAR2(20),
    CC_CONNECT_ID NVARCHAR2(30),
    ACCESSORIES_CUSTOM_PRICE NUMBER(10,2),
    ACCESSORIES_TOTAL NUMBER(10,2),
    INSURANCE_AMOUNT NUMBER(10,2),
    PETS NUMBER(10,2),
    PARKING NUMBER(10,2),
    PARKING_OVERRIDE NUMBER(1,0),
    BOATS_TOTAL NUMBER(10,2),
    POS_TOTAL NUMBER(10,2),
    USE_CLUB_CREDITS NUMBER(1,0),
    NO_SHOW_FEE NUMBER(1,0),
    CANCELLATION_FEE NUMBER(1,0),
    CLUB_FEES NUMBER(10,2),
    CLUB_FEES_OVERRIDE NUMBER(1,0),
    SUB_TOTAL NUMBER(10,2),
    CONVENIENCE_FEE NUMBER(10,2),
    CONVENIENCE_FEE_WAIVED NUMBER(1,0),
    INTERNAL_APPLICATION_FEE NUMBER(10,2),
    TAX_1 NUMBER(10,2),
    TAX_1_EXEMPT NUMBER(1,0),
    TAX_1_RATE_OVERRIDE NUMBER(10,2),
    TAX_2 NUMBER(10,2),
    TAX_2_EXEMPT NUMBER(1,0),
    CHECK_IN_TAX_1 NUMBER(10,2),
    CHECK_IN_TAX_2 NUMBER(10,2),
    CHECK_IN_TOTAL NUMBER(10,2),
    DEPOSIT_TOTAL NUMBER(10,2),
    DEPOSIT_OVERRIDE NUMBER(1,0),
    DEPOSIT_WAIVED NUMBER(1,0),
    GRATUITY NUMBER(10,2),
    GRAND_TOTAL NUMBER(10,2),
    ADJUSTMENT_TOTAL NUMBER(10,2),
    AMOUNT_PAID NUMBER(10,2),
    NOTES NCLOB,
    NOTES_CONTRACT NVARCHAR2(3),
    NOTES_FROM_CUSTOMER NCLOB,
    NOTES_FROM_CUSTOMER_CONTRACT NVARCHAR2(3),
    NOTES_FOR_CUSTOMER NCLOB,
    NOTES_FOR_CUSTOMER_CONTRACT NVARCHAR2(3),
    FRONTEND NVARCHAR2(3) DEFAULT 'No',
    IS_ON_HOLD NVARCHAR2(3) DEFAULT 'No',
    IS_LOCKED NVARCHAR2(3) DEFAULT 'No',
    IS_FINALIZED NVARCHAR2(3) DEFAULT 'No',
    IS_CANCELED NVARCHAR2(3) DEFAULT 'No',
    OVERRIDE_TURNAROUND_TIME NVARCHAR2(3) DEFAULT 'No',
    CANCELLATION_TYPE NVARCHAR2(20),
    BYPASS_CLUB_RESTRICTIONS NVARCHAR2(3) DEFAULT 'No',
    RENTERS_INSURANCE_INTEREST NVARCHAR2(3),
    COUPON_ID NUMBER(10,0),
    COUPON_TYPE NVARCHAR2(20),
    COUPON_AMOUNT NUMBER(10,2),
    DISCOUNT_TOTAL NUMBER(10,2),
    AGENT_ID NUMBER(10,0),
    AGENT_NAME NVARCHAR2(191),
    REFERRER_ID NVARCHAR2(191),
    SAFETY_REMINDER NUMBER(1,0),
    DELETED_ADMIN_ID NUMBER(10,0),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    FINALIZED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP

);

-- Booking Boats Table (Individual boat rentals within bookings)
CREATE TABLE STG_STELLAR_BOOKING_BOATS (
    ID NUMBER(10,0),
    BOOKING_ID NUMBER(10,0),
    STYLE_ID NUMBER(10,0),
    BOAT_ID NVARCHAR2(11),
    TIME_ID NVARCHAR2(11),
    TIMEFRAME_ID NUMBER(1,0),
    MAIN_BOAT NUMBER(1,0),
    NUM_PASSENGERS NUMBER(3,0),
    BOAT_DEPARTURE TIMESTAMP,
    BOAT_RETURN TIMESTAMP,
    STATUS_BOOKING NVARCHAR2(20) DEFAULT 'Booked',
    PRICE NUMBER(10,2),
    PRICE_OVERRIDE NUMBER(1,0),
    SIGNATURE_DATE TIMESTAMP,
    CHECK_OUT_DATE TIMESTAMP,
    CHECK_OUT_EQUIPMENT NCLOB,
    CHECK_OUT_NOTES NCLOB,
    CHECK_OUT_ENGINE_HOURS NUMBER(10,2),
    CHECK_IN_DATE TIMESTAMP,
    CHECK_IN_EQUIPMENT NCLOB,
    CHECK_IN_NOTES NCLOB,
    CHECK_IN_ENGINE_HOURS NUMBER(10,2),
    CHECK_IN_HOURS NUMBER(10,2),
    CHECK_IN_DEPOSIT NUMBER(10,2),
    CHECK_IN_WEATHER NUMBER(10,2),
    CHECK_IN_LATE NUMBER(10,2),
    CHECK_IN_MISC_NON_TAX NUMBER(10,2),
    CHECK_IN_MISC_TAX NUMBER(10,2),
    CHECK_IN_CLEANING NUMBER(10,2),
    CHECK_IN_GALLONS NUMBER(10,3),
    CHECK_IN_FUEL NUMBER(10,2),
    CHECK_IN_DIESEL_GALLONS NUMBER(10,3),
    CHECK_IN_DIESEL NUMBER(10,2),
    CHECK_IN_TIP NUMBER(10,2),
    CHECK_IN_TAX_1 NUMBER(10,2),
    CHECK_IN_TAX_2 NUMBER(10,2),
    CHECK_IN_TOTAL NUMBER(10,2),
    QUEUE_ADMIN_ID NUMBER(10,0),
    QUEUE_DATE TIMESTAMP,
    ATTENDANT_QUEUE_ADMIN_ID NUMBER(10,0),
    ATTENDANT_WATER_ADMIN_ID NUMBER(10,0),
    BOAT_ASSIGNED NUMBER(10,0),
    ADDITIONAL_DRIVERS NUMBER(1,0),
    ADDITIONAL_DRIVER_NAMES NCLOB,
    ACCESSORIES_MIGRATED NUMBER(1,0) DEFAULT 0,
    PRICE_RULE_ID NUMBER(10,0),
    PRICE_RULE_ORIGINAL_PRICE NUMBER(10,2),
    PRICE_RULE_DYNAMIC_PRICE NUMBER(10,2),
    PRICE_RULE_DIFFERENCE NUMBER(10,2),
    EMERGENCY_NAME NVARCHAR2(191),
    EMERGENCY_PHONE NVARCHAR2(25),
    DATE_OF_BIRTH NVARCHAR2(30),
    CONTRACT_RETURN_PDF NCLOB,
    CONTRACT_PDF NCLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP

);

-- Booking Payments Table (Payment transactions for bookings)
CREATE TABLE STG_STELLAR_BOOKING_PAYMENTS (
    ID NUMBER(10,0),
    BOOKING_ID NUMBER(10,0),
    CUSTOMER_ID NUMBER(10,0),
    ADMIN_ID NUMBER(10,0),
    FRONTEND NUMBER(1,0),
    PAYMENT_FOR NVARCHAR2(191),
    PAYMENT_TYPE NVARCHAR2(25),
    CARD_TYPE CHAR(1),
    PAYMENT_TOTAL NUMBER(10,2),
    CASH_TOTAL NUMBER(10,2),
    CREDIT_TOTAL NUMBER(10,2),
    AGENT_AR_TOTAL NUMBER(10,2),
    CREDIT_LAST4 NVARCHAR2(4),
    CREDIT_EXPIRY NVARCHAR2(10),
    BILLING_FIRST_NAME NVARCHAR2(191),
    BILLING_LAST_NAME NVARCHAR2(191),
    BILLING_STREET1 NVARCHAR2(191),
    BILLING_STREET2 NVARCHAR2(191),
    BILLING_CITY NVARCHAR2(191),
    BILLING_STATE NVARCHAR2(191),
    BILLING_COUNTRY CHAR(3) DEFAULT 'USA',
    BILLING_ZIP NVARCHAR2(15),
    TRANS_ID NVARCHAR2(191),
    ORIGINAL_PAYMENT_ID NUMBER(10,0),
    STATUS_PAYMENT NVARCHAR2(191),
    NOTES NCLOB,
    IS_AGENT_AR NVARCHAR2(3) DEFAULT 'No',
    OFFLINE_TYPE NVARCHAR2(25),
    DOCK_MASTER_TICKET NCLOB,
    MY_TASK_IT_ID NVARCHAR2(50),
    REPORT_BOATS NUMBER(10,2),
    REPORT_PROPANE NUMBER(10,2),
    REPORT_ACCESSORIES NUMBER(10,2),
    REPORT_PARKING NUMBER(10,2),
    REPORT_INSURANCE NUMBER(10,2),
    REPORT_FUEL NUMBER(10,2),
    REPORT_DAMAGES NUMBER(10,2),
    REPORT_CLEANING NUMBER(10,2),
    REPORT_LATE NUMBER(10,2),
    REPORT_OTHER NUMBER(10,2),
    REPORT_DISCOUNT NUMBER(10,2),
    INTERNAL_APPLICATION_FEE NUMBER(10,2),
    CC_PROCESSOR_FEE NUMBER(10,2),
    CC_BRAND NVARCHAR2(30),
    CC_COUNTRY CHAR(2),
    CC_FUNDING NVARCHAR2(30),
    CC_CONNECT_TYPE NVARCHAR2(20),
    CC_CONNECT_ID NVARCHAR2(30),
    CC_PAYOUT_ID NVARCHAR2(50),
    CC_PAYOUT_DATE TIMESTAMP,
    EXTERNAL_CHARGE_ID NVARCHAR2(191),
    IS_SYNCED NUMBER(1,0),
    STRIPE_READER_ID NVARCHAR2(191),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP

);

-- ====================================================================
-- BOAT AND VESSEL MANAGEMENT
-- ====================================================================

-- Style Groups Table (Boat categories)
CREATE TABLE STG_STELLAR_STYLE_GROUPS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    GROUP_NAME NVARCHAR2(191),
    FRONTEND_MAX_SAME_DEPARTURES NUMBER(10,0),
    SAFETY_TEST_ENABLED NVARCHAR2(3) DEFAULT 'No',
    SAFETY_TEST_INSTRUCTIONS NCLOB,
    SAFETY_TEST_MIN_PERCENT_PASS NUMBER(10,2),
    SAFETY_TEST_EXPIRATION_DAYS NUMBER(10,0),
    SAFETY_VIDEO_LINK NCLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Styles Table (Boat types/models)
CREATE TABLE STG_STELLAR_STYLES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    STYLE_GROUP_ID NUMBER(10,0),
    STYLE_NAME NVARCHAR2(191),
    BACKEND_DISPLAY NVARCHAR2(3) DEFAULT 'Yes',
    POSITION_ORDER NUMBER(10,0),
    TURN_AROUND_TIME NUMBER(5,2),
    DEPOSIT_AMOUNT NUMBER(10,2),
    MULTI_DAY_DEPOSIT_AMOUNT NUMBER(10,2),
    PRE_AUTH_AMOUNT NUMBER(10,2),
    FUEL_BURN_RATIO NUMBER(10,3),
    TAX_1_RATE NUMBER(10,2),
    TAX_2_RATE NUMBER(10,2),
    INSURANCE_ENABLED NVARCHAR2(3) DEFAULT 'Yes',
    INSURANCE_PRICING_TYPE NVARCHAR2(50),
    INSURANCE_PRICING_RATE NUMBER(10,2),
    INSURANCE_FIRST_DAY_PRICE NUMBER(10,2),
    GRATUITY_ENABLED NVARCHAR2(3) DEFAULT 'No',
    GRATUITY_PRICING_RATE NUMBER(10,2),
    PARKING_QTY_MULTIPLIER NUMBER(10,2),
    FRONTEND_DISPLAY NVARCHAR2(3) DEFAULT 'No',
    FRONTEND_NAME NVARCHAR2(191),
    FRONTEND_POSITION NUMBER(10,0),
    FRONTEND_TYPE NVARCHAR2(50) DEFAULT 'Amenities',
    FRONTEND_QTY_LIMIT NUMBER(10,0),
    FRONTEND_UNIT_SELECTOR NVARCHAR2(3) DEFAULT 'No',
    FRONTEND_PARTIAL_PAYMENT_TYPE NVARCHAR2(20),
    FRONTEND_PARTIAL_PAYMENT_AMOUNT NUMBER(10,2),
    BACKEND_MULTI_DAY_DISABLED NVARCHAR2(3) DEFAULT 'No',
    MAX_SAME_STYLE_PER_BOOKING NUMBER(5,0),
    FRONTEND_MIN_HOURS_ADVANCE_DEPARTURE NUMBER(10,2),
    BACKEND_HOURLY_ENABLED NVARCHAR2(3) DEFAULT 'No',
    WEEK_DAY_BACKEND_HOURLY_MIN_HOURS NUMBER(10,2),
    WEEK_DAY_BACKEND_HOURLY_MAX_HOURS NUMBER(10,2),
    WEEK_END_BACKEND_HOURLY_MIN_HOURS NUMBER(10,2),
    WEEK_END_BACKEND_HOURLY_MAX_HOURS NUMBER(10,2),
    HOLIDAY_BACKEND_HOURLY_MIN_HOURS NUMBER(10,2),
    HOLIDAY_BACKEND_HOURLY_MAX_HOURS NUMBER(10,2),
    FRONTEND_HOURLY_ENABLED NVARCHAR2(3) DEFAULT 'No',
    WEEK_DAY_FRONTEND_HOURLY_MIN_HOURS NUMBER(10,2),
    WEEK_DAY_FRONTEND_HOURLY_MAX_HOURS NUMBER(10,2),
    WEEK_DAY_FRONTEND_HOURLY_TIME_INCREMENT NUMBER(10,2),
    WEEK_DAY_FRONTEND_HOURLY_LENGTH_INCREMENT NUMBER(10,2),
    WEEK_END_FRONTEND_HOURLY_MIN_HOURS NUMBER(10,2),
    WEEK_END_FRONTEND_HOURLY_MAX_HOURS NUMBER(10,2),
    WEEK_END_FRONTEND_HOURLY_TIME_INCREMENT NUMBER(10,2),
    WEEK_END_FRONTEND_HOURLY_LENGTH_INCREMENT NUMBER(10,2),
    HOLIDAY_FRONTEND_HOURLY_MIN_HOURS NUMBER(10,2),
    HOLIDAY_FRONTEND_HOURLY_MAX_HOURS NUMBER(10,2),
    HOLIDAY_FRONTEND_HOURLY_TIME_INCREMENT NUMBER(10,2),
    HOLIDAY_FRONTEND_HOURLY_LENGTH_INCREMENT NUMBER(10,2),
    BACKEND_NIGHTLY_ENABLED NVARCHAR2(3) DEFAULT 'No',
    BACKEND_NIGHTLY_MIN_NIGHTS NUMBER(10,2),
    BACKEND_NIGHTLY_MAX_NIGHTS NUMBER(10,2),
    BACKEND_NIGHTLY_START NUMBER(4,2),
    BACKEND_NIGHTLY_END NUMBER(4,2),
    BACKEND_NIGHTLY_DISCOUNT_DAYS NUMBER(6,0),
    BACKEND_NIGHTLY_DISCOUNT_TYPE NVARCHAR2(20),
    BACKEND_NIGHTLY_DISCOUNT_AMOUNT NUMBER(10,2),
    FRONTEND_NIGHTLY_ENABLED NVARCHAR2(3) DEFAULT 'No',
    FRONTEND_NIGHTLY_MIN_NIGHTS NUMBER(10,2),
    FRONTEND_NIGHTLY_MIN_NIGHTS_PEAK NUMBER(10,2),
    FRONTEND_NIGHTLY_MAX_NIGHTS NUMBER(10,2),
    FRONTEND_NIGHTLY_START NUMBER(4,2),
    FRONTEND_NIGHTLY_END NUMBER(4,2),
    FRONTEND_NIGHTLY_ADDL_TIMES NCLOB,
    FRONTEND_NIGHTLY_DISCOUNT_DAYS NUMBER(6,0),
    FRONTEND_NIGHTLY_DISCOUNT_TYPE NVARCHAR2(20),
    FRONTEND_NIGHTLY_DISCOUNT_AMOUNT NUMBER(10,2),
    IMAGE_URL NVARCHAR2(191),
    PASSENGERS NUMBER(4,0),
    WEIGHT_CAPACITY NUMBER(5,0),
    HORSEPOWER NUMBER(4,0),
    ENGINE_TYPE NVARCHAR2(191),
    LENGTH_FEET NUMBER(6,2),
    WIDTH_FEET NUMBER(6,2),
    DRAFT_FEET NUMBER(6,2),
    FUEL_CAPACITY NUMBER(4,0),
    BRAND NVARCHAR2(191),
    MODEL NVARCHAR2(191),
    TITLE NVARCHAR2(191),
    DESCRIPTION_TEXT NCLOB,
    SUMMARY_TEXT NCLOB,
    NOTES NCLOB,
    VIDEO_LINK NVARCHAR2(191),
    SMARTWAIVER_WAIVER_LINK NVARCHAR2(191),
    ACCOUNTING_ITEM_ID NVARCHAR2(191),
    LOCAL_VIDEO_LINK NVARCHAR2(191),
    DOCKMASTER_PART_NUMBER NVARCHAR2(191),
    DOCKMASTER_TAX_CODE NVARCHAR2(191),
    END_HOURS NCLOB,
    SEASONAL_BUFFER_DEFAULT_LOWER NUMBER(10,2),
    SEASONAL_BUFFER_DEFAULT_UPPER NUMBER(10,2),
    SEASONAL_BUFFER_PEAK_LOWER NUMBER(10,2),
    SEASONAL_BUFFER_PEAK_UPPER NUMBER(10,2),
    BILLABLE_UNIT_TYPE NVARCHAR2(191),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Style Boats Table (Individual boat/vessel inventory)
CREATE TABLE STG_STELLAR_STYLE_BOATS (
    ID NUMBER(10,0),
    STYLE_ID NUMBER(10,0),
    BOAT_NUMBER NVARCHAR2(191),
    PAPER_LESS_NUMBER NVARCHAR2(191),
    MOTOR NVARCHAR2(191),
    MANUFACTURER NVARCHAR2(191),
    SERIAL_NUMBER NVARCHAR2(191),
    IN_FLEET NVARCHAR2(3) DEFAULT 'Yes',
    HULL_NUMBER NVARCHAR2(191),
    STATE_NUMBER NVARCHAR2(191),
    CYLINDERS NVARCHAR2(191),
    HP NVARCHAR2(191),
    MODEL NVARCHAR2(191),
    BOAT_TYPE NVARCHAR2(191),
    PURCHASED_DATE DATE,
    PURCHASED_COST NUMBER(10,2),
    SALE_DATE DATE,
    SALE_PRICE NUMBER(10,2),
    CLUB_LOCATION NVARCHAR2(191),
    DEALER_NAME NVARCHAR2(191),
    DEALER_CITY NVARCHAR2(191),
    DEALER_STATE NVARCHAR2(191),
    PO_NUMBER NVARCHAR2(191),
    BOAT_YEAR_MODEL NVARCHAR2(191),
    MOTOR_YEAR_MODEL NVARCHAR2(191),
    MOTOR_MANUFACTURER_MODEL NVARCHAR2(191),
    STATE_REG_DATE DATE,
    STATE_REG_EXP_DATE DATE,
    ENGINE_PURCHASED_COST NUMBER(10,2),
    BACKEND_DISPLAY NVARCHAR2(3) DEFAULT 'Yes',
    POSITION_ORDER NUMBER(10,0),
    STATUS_BOAT NVARCHAR2(20) DEFAULT 'Out of Service',
    SERVICE_START DATE,
    SERVICE_END DATE,
    CLEAN_STATUS NVARCHAR2(10),
    INSURANCE_REG_NO NVARCHAR2(50),
    BUOY_INSURANCE_STATUS NVARCHAR2(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Customer Boats Table (Customer-owned vessels)
CREATE TABLE STG_STELLAR_CUSTOMER_BOATS (
    ID NUMBER(10,0),
    CUSTOMER_ID NUMBER(10,0),
    SLIP_ID NUMBER(10,0),
    BOAT_NAME NVARCHAR2(191),
    BOAT_NUMBER NVARCHAR2(191),
    LENGTH_FEET NUMBER(10,2),
    WIDTH_FEET NUMBER(10,2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- PRICING AND SEASONS
-- ====================================================================

-- Seasons Table (Pricing seasons)
CREATE TABLE STG_STELLAR_SEASONS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    SEASON_NAME NVARCHAR2(191),
    SEASON_START DATE,
    SEASON_END DATE,
    STATUS_SEASON NVARCHAR2(10) DEFAULT 'Inactive',
    WEEK_DAY_MIN_START_TIME NUMBER(4,2),
    WEEK_DAY_MAX_START_TIME NUMBER(4,2),
    WEEK_DAY_MIN_END_TIME NUMBER(4,2),
    WEEK_DAY_MAX_END_TIME NUMBER(4,2),
    WEEK_END_MIN_START_TIME NUMBER(4,2),
    WEEK_END_MAX_START_TIME NUMBER(4,2),
    WEEK_END_MIN_END_TIME NUMBER(4,2),
    WEEK_END_MAX_END_TIME NUMBER(4,2),
    HOLIDAY_MIN_START_TIME NUMBER(4,2),
    HOLIDAY_MAX_START_TIME NUMBER(4,2),
    HOLIDAY_MIN_END_TIME NUMBER(4,2),
    HOLIDAY_MAX_END_TIME NUMBER(4,2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Season Dates Table (Season date ranges)
CREATE TABLE STG_STELLAR_SEASON_DATES (
    ID NUMBER(10,0),
    SEASON_ID NUMBER(10,0),
    START_DATE DATE,
    END_DATE DATE

);

-- Style Hourly Prices Table (Hourly pricing by style and season)
CREATE TABLE STG_STELLAR_STYLE_HOURLY_PRICES (
    ID NUMBER(10,0),
    STYLE_ID NUMBER(10,0),
    SEASON_ID NUMBER(10,0),
    HOURLY_TYPE NVARCHAR2(20),
    DEFAULT_PRICE NUMBER(10,4),
    HOLIDAY NUMBER(10,4),
    SATURDAY NUMBER(10,4),
    SUNDAY NUMBER(10,4),
    MONDAY NUMBER(10,4),
    TUESDAY NUMBER(10,4),
    WEDNESDAY NUMBER(10,4),
    THURSDAY NUMBER(10,4),
    FRIDAY NUMBER(10,4),
    DAY_DISCOUNT NUMBER(10,4),
    UNDER_ONE_HOUR NUMBER(10,4),
    FIRST_HOUR_AM NUMBER(10,4),
    FIRST_HOUR_PM NUMBER(10,4),
    MAX_PRICE NUMBER(10,4),
    MIN_HOURS NUMBER(10,4),
    MAX_HOURS NUMBER(10,4),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Style Times Table (Available time slots)
CREATE TABLE STG_STELLAR_STYLE_TIMES (
    ID NUMBER(10,0),
    STYLE_ID NUMBER(10,0),
    SEASON_ID NUMBER(10,0),
    DESCRIPTION_TEXT NVARCHAR2(191),
    FRONTEND_DISPLAY NVARCHAR2(3) DEFAULT 'No',
    START_1 NUMBER(4,2),
    END_1 NUMBER(4,2),
    END_DAYS_1 NUMBER(5,0),
    STATUS_1 NVARCHAR2(3) DEFAULT 'Off',
    START_2 NUMBER(4,2),
    END_2 NUMBER(4,2),
    END_DAYS_2 NUMBER(5,0),
    STATUS_2 NVARCHAR2(3) DEFAULT 'Off',
    START_3 NUMBER(4,2),
    END_3 NUMBER(4,2),
    END_DAYS_3 NUMBER(5,0),
    STATUS_3 NVARCHAR2(3) DEFAULT 'Off',
    START_4 NUMBER(4,2),
    END_4 NUMBER(4,2),
    END_DAYS_4 NUMBER(5,0),
    STATUS_4 NVARCHAR2(3) DEFAULT 'Off',
    VALID_DAYS NCLOB,
    HOLIDAYS_ONLY_IF_VALID_DAY NUMBER(1,0),
    MAPPED_TIME_ID NUMBER(10,0),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Style Prices Table (Static pricing)
CREATE TABLE STG_STELLAR_STYLE_PRICES (
    TIME_ID NUMBER(10,0),
    DEFAULT_PRICE NUMBER(10,2),
    HOLIDAY NUMBER(10,2),
    SATURDAY NUMBER(10,2),
    SUNDAY NUMBER(10,2),
    MONDAY NUMBER(10,2),
    TUESDAY NUMBER(10,2),
    WEDNESDAY NUMBER(10,2),
    THURSDAY NUMBER(10,2),
    FRIDAY NUMBER(10,2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- ACCESSORIES AND ADD-ONS
-- ====================================================================

-- Accessories Table (Rental accessories)
CREATE TABLE STG_STELLAR_ACCESSORIES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    ACCESSORY_NAME NVARCHAR2(191),
    POSITION_ORDER NUMBER(10,0),
    FRONTEND_POSITION NUMBER(10,0),
    SHORT_NAME NVARCHAR2(4),
    ABBREVIATION CHAR(2),
    IMAGE_URL NVARCHAR2(191),
    PRICE NUMBER(10,2),
    DEPOSIT_AMOUNT NUMBER(10,2),
    TAX_EXEMPT NVARCHAR2(3) DEFAULT 'No',
    MAX_OVERLAPPING_RENTALS NUMBER(10,0),
    FRONTEND_QTY_LIMIT NUMBER(10,0),
    USE_STRIPED_BACKGROUND NVARCHAR2(3) DEFAULT 'No',
    BACKEND_AVAILABLE_DAYS NCLOB,
    FRONTEND_AVAILABLE_DAYS NCLOB,
    MAX_SAME_DEPARTURES NUMBER(10,0),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Accessory Options Table (Accessory variations)
CREATE TABLE STG_STELLAR_ACCESSORY_OPTIONS (
    ID NUMBER(10,0),
    ACCESSORY_ID NUMBER(10,0),
    VALUE_TEXT NCLOB,
    USE_STRIPED_BACKGROUND NVARCHAR2(3) DEFAULT 'No',
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Accessory Tiers Table (Tiered pricing for accessories)
CREATE TABLE STG_STELLAR_ACCESSORY_TIERS (
    ID NUMBER(10,0),
    ACCESSORY_ID NUMBER(10,0),
    MIN_HOURS NUMBER(10,2),
    MAX_HOURS NUMBER(10,2),
    PRICE NUMBER(10,2),
    ACCESSORY_OPTION_ID NUMBER(10,0),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Booking Accessories Table (Accessories rented with bookings)
CREATE TABLE STG_STELLAR_BOOKING_ACCESSORIES (
    BOOKING_ID NUMBER(10,0),
    ACCESSORY_ID NUMBER(10,0),
    QTY NUMBER(3,0),
    PRICE NUMBER(10,2),
    PRICE_OVERRIDE NUMBER(1,0) DEFAULT 0,
    ACCESSORY_OPTION_ID NUMBER(10,0),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- CLUBS AND MEMBERSHIPS
-- ====================================================================

-- Club Tiers Table (Membership tiers)
CREATE TABLE STG_STELLAR_CLUB_TIERS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    TIER_NAME NVARCHAR2(191),
    FRONTEND_DISPLAY NVARCHAR2(3) DEFAULT 'Yes',
    FRONTEND_NAME NVARCHAR2(191),
    FRONTEND_POSITION NUMBER(10,0),
    TERM_LENGTH NUMBER(10,0),
    TERM_LENGTH_TYPE NVARCHAR2(10) DEFAULT 'Years',
    TERM_AUTO_RENEW NVARCHAR2(3) DEFAULT 'No',
    TERM_FEE NUMBER(10,2),
    PERIOD_LENGTH NUMBER(10,0),
    PERIOD_LENGTH_TYPE NVARCHAR2(10) DEFAULT 'Days',
    CREDITS_PER_PERIOD NUMBER(10,2),
    HOURS_PER_CREDIT NUMBER(10,2),
    PERIOD_FEE NUMBER(10,2),
    FRONTEND_DISPLAY_PRICING NVARCHAR2(3) DEFAULT 'Yes',
    NO_SHOW_FEE NUMBER(10,2),
    ALLOW_SELF_CANCELLATIONS NVARCHAR2(3) DEFAULT 'Yes',
    CANCELLATION_FEE NUMBER(10,2),
    APPLICATION_FEE NUMBER(10,2),
    BOAT_DAMAGE_RESPONSIBILITY_DEDUCTION NUMBER(10,2),
    MAX_PENDING_WAIT_LIST_ENTRIES NUMBER(10,0),
    FREE_ACCESSORIES NCLOB,
    DESCRIPTION_TEXT NCLOB,
    TERMS_TEXT NCLOB,
    STATUS_TIER NVARCHAR2(10) DEFAULT 'Active',
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- COUPONS AND DISCOUNTS
-- ====================================================================

-- Coupons Table (Discount coupons)
CREATE TABLE STG_STELLAR_COUPONS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    CODE NVARCHAR2(191),
    COUPON_NAME NVARCHAR2(191),
    COUPON_TYPE NVARCHAR2(30) DEFAULT 'Percentage',
    COUPON_AMOUNT NUMBER(10,2),
    COUNT_ALLOWED NUMBER(6,0),
    COUNT_ALLOWED_DAILY NUMBER(6,0),
    COUNT_USED NUMBER(6,0) DEFAULT 0,
    RENTAL_START DATE,
    RENTAL_END DATE,
    COUPON_START DATE,
    COUPON_END DATE,
    MIN_DEPARTURE_TIME NUMBER(4,2),
    MAX_DEPARTURE_TIME NUMBER(4,2),
    MIN_RETURN_TIME NUMBER(4,2),
    MAX_RETURN_TIME NUMBER(4,2),
    MIN_HOURS NUMBER(10,2),
    MAX_HOURS NUMBER(10,2),
    MIN_HOURS_BEFORE_DEPARTURE NUMBER(10,2),
    MAX_HOURS_BEFORE_DEPARTURE NUMBER(10,2),
    MAX_SAME_DAY_PER_CUSTOMER NUMBER(10,0),
    MAX_ACTIVE_PER_CUSTOMER NUMBER(10,0),
    DISABLE_CONSECUTIVE_PER_CUSTOMER NCLOB,
    STATUS_COUPON NVARCHAR2(10) DEFAULT 'Inactive',
    VALID_DAYS NCLOB,
    HOLIDAYS_ONLY_IF_VALID_DAY NUMBER(1,0),
    VALID_STYLES NCLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- POINT OF SALE
-- ====================================================================

-- POS Items Table (Point of sale inventory)
CREATE TABLE STG_STELLAR_POS_ITEMS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    SKU NVARCHAR2(191),
    ITEM_NAME NVARCHAR2(191),
    COST NUMBER(10,2),
    PRICE NUMBER(10,2),
    TAX_EXEMPT NVARCHAR2(3) DEFAULT 'No',
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- POS Sales Table (Point of sale transactions)
CREATE TABLE STG_STELLAR_POS_SALES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    ADMIN_ID NUMBER(10,0),
    CUSTOMER_NAME NVARCHAR2(191),
    SUB_TOTAL NUMBER(10,2),
    TAX_1 NUMBER(10,2),
    GRAND_TOTAL NUMBER(10,2),
    AMOUNT_PAID NUMBER(10,2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP

);

-- Fuel Sales Table (Fuel transactions)
CREATE TABLE STG_STELLAR_FUEL_SALES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    ADMIN_ID NUMBER(10,0),
    CUSTOMER_NAME NVARCHAR2(191),
    FUEL_TYPE NVARCHAR2(191),
    QTY NUMBER(10,4),
    PRICE NUMBER(10,4),
    SUB_TOTAL NUMBER(10,2),
    TIP NUMBER(10,2),
    GRAND_TOTAL NUMBER(10,2),
    AMOUNT_PAID NUMBER(10,2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP

);

-- ====================================================================
-- OPERATIONAL TABLES
-- ====================================================================

-- Waitlists Table (Customer waiting lists)
CREATE TABLE STG_STELLAR_WAITLISTS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    CATEGORY_ID NUMBER(10,0),
    STYLE_ID NUMBER(10,0),
    CUSTOMER_ID NUMBER(10,0),
    TIME_ID NUMBER(10,0),
    TIMEFRAME_ID NUMBER(1,0),
    FIRST_NAME NVARCHAR2(191),
    LAST_NAME NVARCHAR2(191),
    EMAIL NVARCHAR2(191),
    PHONE NVARCHAR2(25),
    DEPARTURE_DATE DATE,
    LENGTH_REQUESTED NVARCHAR2(20),
    WAIT_LIST_TIME NVARCHAR2(50),
    FULFILLED NVARCHAR2(10) DEFAULT 'Pending',
    FULFILLED_DATE DATE,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Closed Dates Table (Business closure dates)
CREATE TABLE STG_STELLAR_CLOSED_DATES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    CLOSED_DATE DATE,
    ALLOW_BACKEND_DEPARTURES NVARCHAR2(3) DEFAULT 'No',
    ALLOW_BACKEND_RETURNS NVARCHAR2(3) DEFAULT 'No',
    ALLOW_FRONTEND_DEPARTURES NVARCHAR2(3) DEFAULT 'No',
    ALLOW_FRONTEND_RETURNS NVARCHAR2(3) DEFAULT 'No',
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Holidays Table (Holiday dates)
CREATE TABLE STG_STELLAR_HOLIDAYS (
    LOCATION_ID NUMBER(10,0),
    HOLIDAY_DATE DATE

);

-- Blacklists Table (Blacklisted customers)
CREATE TABLE STG_STELLAR_BLACKLISTS (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    FIRST_NAME NVARCHAR2(191),
    LAST_NAME NVARCHAR2(191),
    PHONE NVARCHAR2(25),
    CELL NVARCHAR2(25),
    EMAIL NVARCHAR2(191),
    DL_NUMBER NVARCHAR2(40),
    NOTES NCLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- LOOKUP AND STATUS TABLES
-- ====================================================================

-- Categories Table (Boat categories)
CREATE TABLE STG_STELLAR_CATEGORIES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    CATEGORY_NAME NVARCHAR2(191),
    FRONTEND_DISPLAY NVARCHAR2(3) DEFAULT 'Yes',
    FRONTEND_NAME NVARCHAR2(191),
    FRONTEND_TYPE NVARCHAR2(30) DEFAULT 'Same Day Only',
    FRONTEND_POSITION NUMBER(10,0),
    FILTER_UNIT_TYPE_ENABLED NVARCHAR2(3) DEFAULT 'Yes',
    FILTER_UNIT_TYPE_NAME NVARCHAR2(191),
    FILTER_UNIT_TYPE_POSITION NVARCHAR2(10) DEFAULT 'First',
    MIN_NIGHTS_MULTI_DAY NUMBER(10,0) DEFAULT 1,
    CALENDAR_BANNER_TEXT NVARCHAR2(191),
    DESCRIPTION_TEXT NCLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- Amenities Table (Boat amenities)
CREATE TABLE STG_STELLAR_AMENITIES (
    ID NUMBER(10,0),
    LOCATION_ID NUMBER(10,0),
    AMENITY_NAME NVARCHAR2(191),
    FRONTEND_DISPLAY NVARCHAR2(3) DEFAULT 'Yes',
    FRONTEND_NAME NVARCHAR2(191),
    FRONTEND_POSITION NUMBER(10,0),
    FEATURED NVARCHAR2(3) DEFAULT 'Yes',
    FILTERABLE NVARCHAR2(3) DEFAULT 'Yes',
    ICON NVARCHAR2(191),
    AMENITY_TYPE NVARCHAR2(10) DEFAULT 'Text',
    OPTIONS_TEXT NCLOB,
    PREFIX_TEXT NVARCHAR2(191),
    SUFFIX_TEXT NVARCHAR2(191),
    DESCRIPTION_TEXT NCLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP

);

-- ====================================================================
-- COMMENTS
-- ====================================================================

COMMENT ON TABLE DW_STELLAR_LOCATIONS IS 'Marina and business location information';
COMMENT ON TABLE DW_STELLAR_CUSTOMERS IS 'Customer master data and profiles';
COMMENT ON TABLE DW_STELLAR_BOOKINGS IS 'Main booking/reservation records';
COMMENT ON TABLE DW_STELLAR_BOOKING_BOATS IS 'Individual boat rentals within bookings';
COMMENT ON TABLE DW_STELLAR_BOOKING_PAYMENTS IS 'Payment transactions for bookings';
COMMENT ON TABLE DW_STELLAR_STYLE_GROUPS IS 'Boat category groupings';
COMMENT ON TABLE DW_STELLAR_STYLES IS 'Boat types and models with configuration';
COMMENT ON TABLE DW_STELLAR_STYLE_BOATS IS 'Individual boat/vessel inventory';
COMMENT ON TABLE DW_STELLAR_CUSTOMER_BOATS IS 'Customer-owned vessels';
COMMENT ON TABLE DW_STELLAR_SEASONS IS 'Pricing and operational seasons';
COMMENT ON TABLE DW_STELLAR_SEASON_DATES IS 'Date ranges for seasons';
COMMENT ON TABLE DW_STELLAR_STYLE_HOURLY_PRICES IS 'Hourly pricing by style and season';
COMMENT ON TABLE DW_STELLAR_STYLE_TIMES IS 'Available time slots for bookings';
COMMENT ON TABLE DW_STELLAR_STYLE_PRICES IS 'Static pricing for time slots';
COMMENT ON TABLE DW_STELLAR_ACCESSORIES IS 'Rental accessories and add-ons';
COMMENT ON TABLE DW_STELLAR_ACCESSORY_OPTIONS IS 'Variations of accessories';
COMMENT ON TABLE DW_STELLAR_ACCESSORY_TIERS IS 'Tiered pricing for accessories';
COMMENT ON TABLE DW_STELLAR_BOOKING_ACCESSORIES IS 'Accessories rented with bookings';
COMMENT ON TABLE DW_STELLAR_CLUB_TIERS IS 'Membership tier definitions';
COMMENT ON TABLE DW_STELLAR_COUPONS IS 'Discount coupons and promotions';
COMMENT ON TABLE DW_STELLAR_POS_ITEMS IS 'Point of sale inventory items';
COMMENT ON TABLE DW_STELLAR_POS_SALES IS 'Point of sale transaction records';
COMMENT ON TABLE DW_STELLAR_FUEL_SALES IS 'Fuel transaction records';
COMMENT ON TABLE DW_STELLAR_WAITLISTS IS 'Customer waiting lists for bookings';
COMMENT ON TABLE DW_STELLAR_CLOSED_DATES IS 'Business closure dates';
COMMENT ON TABLE DW_STELLAR_HOLIDAYS IS 'Holiday dates affecting pricing';
COMMENT ON TABLE DW_STELLAR_BLACKLISTS IS 'Blacklisted customers';
COMMENT ON TABLE DW_STELLAR_CATEGORIES IS 'Boat category classifications';
COMMENT ON TABLE DW_STELLAR_AMENITIES IS 'Boat amenities and features';

COMMIT;