-- Oracle DDL Statements for Molo Data Warehouse
-- Generated from Molo Data Dictionary
-- Only includes tables that store company business data
-- Excludes user login and administration data

-- Companies Table
CREATE TABLE DW_MOLO_COMPANIES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    OWNER NVARCHAR2(1000),
    PRIMARY_FAX_NUMBER NVARCHAR2(1000),
    PRIMARY_PHONE_NUMBER NVARCHAR2(1000),
    CITY_ID NUMBER(10,0),
    IMAGE NVARCHAR2(1000),
    DESCRIPTION NVARCHAR2(1000),
    PARTNER_ID NUMBER(10,0),
    MOLO_API_PARTNER_ID NUMBER(10,0),
    COMPANY_MOLO_API_PARTNER_COMPANY_ID NVARCHAR2(1000),
    INVOICE_AT_COMPANY_LEVEL NUMBER(1,0),
    MOLO_CONTACT_ID NUMBER(10,0),
    STRIPE_CUSTOMER_ID NUMBER(10,0),
    LOGIN_PROVIDER_ID NUMBER(10,0),
    DEFAULT_CC_FEE BINARY_DOUBLE,
    TIER1_PERCENT_ACH_FEE BINARY_DOUBLE,
    TIER2_PERCENT_ACH_FEE BINARY_DOUBLE,
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Marina Locations Table
CREATE TABLE DW_MOLO_MARINA_LOCATIONS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    PRIMARY_PHONE_NUMBER NVARCHAR2(1000),
    PRIMARY_FAX_NUMBER NVARCHAR2(1000),
    RULES NVARCHAR2(1000),
    ARRIVAL_GUIDE NVARCHAR2(1000),
    DEPOSIT_PERCENTAGE NUMBER(5,0),
    CITY_ID NUMBER(10,0),
    ORGANIZATION_ID NUMBER(10,0),
    MARINA_HASH NVARCHAR2(1000),
    UNIT_SYSTEM NVARCHAR2(1000),
    SAFETY_DISTANCE_W NUMBER(5,0),
    SAFETY_DISTANCE_L NUMBER(5,0),
    DEFAULT_ARRIVAL_TIME NVARCHAR2(1000),
    DEFAULT_DEPARTURE_TIME NVARCHAR2(1000),
    POLICY NVARCHAR2(1000),
    MAP NVARCHAR2(1000),
    RETURNS_REFUNDS_POLICY NVARCHAR2(1000),
    DEFAULT_TAX_RATE BINARY_DOUBLE,
    EMAIL_ADDRESS NVARCHAR2(1000),
    INVOICE_WARNING_DAY_COUNT NUMBER(10,0),
    MARINA_WEBSITE NVARCHAR2(1000),
    VESSEL_DIMENSIONS_OPTIONS NUMBER(1,0),
    ALLOW_MOLO_ONLINE_PAYMENT NUMBER(1,0),
    TIME_ZONE NVARCHAR2(1000),
    CURRENCIES_ID NUMBER(10,0),
    HASH_ID NVARCHAR2(1000),
    COUNTRY_ID NUMBER(10,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contacts Table
CREATE TABLE DW_MOLO_CONTACTS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    EMAILS NVARCHAR2(1000),
    FIRST_NAME NVARCHAR2(1000),
    MIDDLE_NAME NVARCHAR2(1000),
    LAST_NAME NVARCHAR2(1000),
    MARINA_LOCATION_ID NUMBER(10,0),
    NOTES NVARCHAR2(1000),
    RECORD_STATUS_ID NUMBER(10,0),
    IS_SUPPLIER NUMBER(1,0),
    IS_CUSTOMER NUMBER(1,0),
    XERO_ID NVARCHAR2(1000),
    COMPANY_CONTACT_NAME NVARCHAR2(1000),
    CREATION_USER NVARCHAR2(1000),
    CREATION_DATE_TIME DATE,
    CIM_ID NUMBER(10,0),
    MARINA_LOCATION1_ID NUMBER(10,0),
    QB_CUSTOMER_ID NUMBER(10,0),
    STATEMENTS_PREFERENCE_ID NUMBER(10,0),
    HASH_ID NVARCHAR2(1000),
    MOLO_API_PARTNER_ID NUMBER(10,0),
    TAX_EXEMPT_STATUS NUMBER(1,0),
    AUTOMATIC_DISCOUNT_PERCENT NUMBER(10,0),
    COST_PLUS_DISCOUNT BINARY_DOUBLE,
    LINKED_PARENT_CONTACT NUMBER(10,0),
    CONTACT_AUTO_CHARGE_ID NUMBER(10,0),
    LAST_EDITED_DATE_TIME DATE,
    LAST_EDITED_USER_ID NVARCHAR2(256),
    LAST_EDITED_MOLO_API_PARTNER_ID NUMBER(10,0),
    STRIPE_CUSTOMER_ID NUMBER(10,0),
    ACCOUNT_LIMIT BINARY_DOUBLE,
    FILESTACK_ID NUMBER(10,0),
    SHOW_COMPANY_NAME_PRINTED NUMBER(1,0),
    BOOKING_MERGING_DONE NUMBER(1,0),
    DATE_OF_BIRTH DATE,
    IDS_CUSTOMER_ID NVARCHAR2(1000),
    DO_NOT_LAUNCH NUMBER(1,0),
    DO_NOT_LAUNCH_REASON NVARCHAR2(1000),
    DRIVER_LICENSE_ID NVARCHAR2(1000),
    QUICKBOOKS_ID NVARCHAR2(1000),
    QUICKBOOKS_NAME NVARCHAR2(1000),
    QBO_VENDOR_ID NVARCHAR2(1000),
    SKIP_FOR_FINANCE_CHARGES NUMBER(1,0),
    MAIN_CONTACT_ID NUMBER(10,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Boats Table
CREATE TABLE DW_MOLO_BOATS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    PHOTO NVARCHAR2(1000),
    MAKE NVARCHAR2(1000),
    MODEL NVARCHAR2(1000),
    NAME NVARCHAR2(1000),
    LOA NVARCHAR2(1000),
    BEAM NVARCHAR2(1000),
    DRAFT NVARCHAR2(1000),
    AIR_DRAFT NVARCHAR2(1000),
    REGISTRATION_NUMBER NVARCHAR2(1000),
    REGISTRATION_STATE NVARCHAR2(1000),
    CREATION_TIME DATE,
    BOAT_TYPE_ID NUMBER(10,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    POWER_NEED_ID NUMBER(10,0),
    NOTES NVARCHAR2(1000),
    RECORD_STATUS_ID NUMBER(10,0),
    ASPNET_USER_ID NVARCHAR2(256),
    MAST_LENGTH NVARCHAR2(1000),
    WEIGHT BINARY_DOUBLE,
    COLOR NVARCHAR2(1000),
    HULL_ID NVARCHAR2(1000),
    KEY_LOCATION_CODE NVARCHAR2(1000),
    YEAR NUMBER(10,0),
    HASH_ID NVARCHAR2(1000),
    MOLO_API_PARTNER_ID NUMBER(10,0),
    POWER_NEED1_ID NUMBER(10,0),
    LAST_EDITED_DATE_TIME DATE,
    LAST_EDITED_USER_ID NVARCHAR2(256),
    LAST_EDITED_MOLO_API_PARTNER_ID NUMBER(10,0),
    FILESTACK_ID NUMBER(10,0),
    TONNAGE BINARY_DOUBLE,
    GALLON_CAPACITY BINARY_DOUBLE,
    IS_ACTIVE NUMBER(1,0),
    BOOKING_MERGING_DONE NUMBER(1,0),
    DECAL_NUMBER NVARCHAR2(1000),
    MANUFACTURER NVARCHAR2(1000),
    SERIAL_NUMBER NVARCHAR2(1000),
    REGISTRATION_EXPIRATION DATE,
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Accounts Table
CREATE TABLE DW_MOLO_ACCOUNTS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    ACCOUNT_STATUS_ID NUMBER(10,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    CONTACT_ID NUMBER(10,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Reservations Table
CREATE TABLE DW_MOLO_RESERVATIONS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    CREATION_TIME DATE,
    RESERVATION_STATUS_ID NUMBER(10,0),
    RESERVATION_TYPE_ID NUMBER(10,0),
    ASPNET_USER_ID NVARCHAR2(256),
    CONTACT_ID NUMBER(10,0),
    BOAT_ID NUMBER(10,0),
    SCHEDULED_ARRIVAL_TIME DATE,
    SCHEDULED_DEPARTURE_TIME DATE,
    CANCELLATION_TIME DATE,
    ACCOUNT_ID NUMBER(10,0),
    SLIP_ID NUMBER(10,0),
    SLIP_SLOT_INDEX NUMBER(5,0),
    DISTANCE_FROM_THE_START BINARY_DOUBLE,
    RATE NUMBER(10,0),
    NAME NVARCHAR2(1000),
    HAS_INSTALLMENTS NUMBER(1,0),
    INSTALLMENT_FREQUENCY NUMBER(10,0),
    INSTALLMENT_NUMBER NUMBER(10,0),
    INSTALLMENT_PAYMENT_METHOD NVARCHAR2(1000),
    ONLY_RESERVATION_INSTALLMENTS NUMBER(1,0),
    NOTES NVARCHAR2(1000),
    ACTUAL_ARRIVAL_DATE_TIME DATE,
    ACTUAL_DEPARTURE_DATE_TIME DATE,
    CONFIRMATION_EMAIL_DATE_TIME DATE,
    TERMS_ACCEPTED_DATE_TIME NVARCHAR2(1000),
    TERMS_ACCEPTED_LOCATION NVARCHAR2(1000),
    CUSTOMER_IP_ADDRESS NVARCHAR2(1000),
    CUSTOMER_DEVICE NVARCHAR2(1000),
    CONFIRMATION_EMAIL_ASP_USER_ID NVARCHAR2(256),
    RATE_PRICE_OVERRIDE BINARY_DOUBLE,
    HASH_ID NVARCHAR2(1000),
    RESERVATION_SOURCE NVARCHAR2(1000),
    RESERVATION_MEDIUM_ID NUMBER(10,0),
    RESERVATION_CAMPAIGN_ID NUMBER(10,0),
    MOLO_API_PARTNER_ID NUMBER(10,0),
    CANCELATION_USER_ID NVARCHAR2(1000),
    CONTACT_MERGED NUMBER(1,0),
    TRANSIENT_PRICE_ID NUMBER(10,0),
    SEASONAL_PRICE_ID NUMBER(10,0),
    PRINTED_TERMS NVARCHAR2(1000),
    ONLINE_TERMS NVARCHAR2(1000),
    CHECK_IN_TERMS NVARCHAR2(1000),
    CHECK_OUT_TERMS NVARCHAR2(1000),
    ONLINE_PAYMENT_COMPLETION NVARCHAR2(1000),
    MOLO_ONLINE_BOOKING NUMBER(1,0),
    BOOKING_CONTACT_MERGED NUMBER(1,0),
    SLIP_BLOCK_SET_ID NUMBER(10,0),
    OFFERS_ID NUMBER(10,0),
    RECURRING_INVOICE_DAY NUMBER(10,0),
    ALTERNATE_RESERVATION_NAME NVARCHAR2(1000),
    RECURRING_DISCOUNT_PERCENT BINARY_DOUBLE,
    RECURRING_RATE_OVERRIDE BINARY_DOUBLE,
    ONLINE_BOOKING_NOTES NVARCHAR2(1000),
    ORIGINAL_OFFER_HOLD_ID NVARCHAR2(1000),
    SCHEDULED_FOR_STATUS_CHANGE NVARCHAR2(1000),
    TERMS_OFFLINE NUMBER(1,0),
    TERMS_USER NVARCHAR2(256),
    ORIGINAL_START_DATE DATE,
    ORIGINAL_END_DATE DATE,
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invoices Table
CREATE TABLE DW_MOLO_INVOICES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    DATE_FIELD DATE,
    DOLLAR_DISCOUNT NUMBER(9,2),
    PERCENT_DISCOUNT NUMBER(9,2),
    ACTIVE NUMBER(1,0),
    CLOSING_DATE DATE,
    DISCOUNT_TOTAL NUMBER(9,2),
    OPENED NUMBER(1,0),
    PAYED BINARY_DOUBLE,
    SUBTOTAL NUMBER(9,2),
    SUBTOTAL_WO_DISCOUNT NUMBER(9,2),
    TAX_TOTAL NUMBER(9,2),
    TITLE NVARCHAR2(1000),
    TOTAL NUMBER(9,2),
    RESERVATION_ID NUMBER(10,0),
    ACCOUNT_ID NUMBER(10,0),
    SERVICE_PAID_AMOUNT NUMBER(9,2),
    MARINA_PAID_AMOUNT NUMBER(9,2),
    GAS_PAID_AMOUNT NUMBER(9,2),
    INVOICE_STATUS_ID NUMBER(10,0),
    START_DATE DATE,
    INSTALLMENTS_PAYMENT_METHOD_ID NUMBER(10,0),
    SCHEDULED_FOR_CRON NUMBER(1,0),
    ORIGINAL_INVOICE NUMBER(10,0),
    PAYMENTS_SENT_TO_XERO NUMBER(1,0),
    WORK_ORDER_ID NUMBER(10,0),
    IS_INSTALLMENT_INVOICE NUMBER(1,0),
    VOID_USER NVARCHAR2(1000),
    VOID_DATE_TIME DATE,
    CREATION_USER NVARCHAR2(1000),
    PAYMENT_ID NUMBER(10,0),
    QB_INVOICE_ID NUMBER(10,0),
    INVOICE_TYPE_ID NUMBER(10,0),
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    CURRENCY_CODE NVARCHAR2(1000),
    LAST_MODIFIED_DATE_TIME DATE,
    LAST_MODIFIED_ASPNET_USER NVARCHAR2(1000),
    VOID_REASON NVARCHAR2(1000),
    CREATE_PARTNER_ID NUMBER(10,0),
    VOID_PARTNER_ID NUMBER(10,0),
    UPDATE_HASH NVARCHAR2(1000),
    SCHEDULED_FOR_INVENTORY_CRON NUMBER(1,0),
    SCHEDULED_FOR_SUBLET_CRON NUMBER(1,0),
    SCHEDULED_FOR_LABOR_CRON NUMBER(1,0),
    CREATED_ON_MOBILE NUMBER(1,0),
    STRIPE_INVOICE_ID NVARCHAR2(1000),
    SENT_TO_STRIPE NUMBER(1,0),
    RESOURCE_BOOKING_ID NUMBER(10,0),
    MODIFIED_ON_MOBILE NUMBER(1,0),
    NOTE NVARCHAR2(1000),
    QUICKBOOKS_INVOICE_ID NVARCHAR2(1000),
    TAX_CAP BINARY_DOUBLE,
    IS_SURCHARGE NUMBER(1,0),
    HASH_CHECK NUMBER(20,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invoice Items Table
CREATE TABLE DW_MOLO_INVOICE_ITEMS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    PREFIX NVARCHAR2(1000),
    QUANTITY BINARY_DOUBLE,
    TITLE NVARCHAR2(1000),
    TYPE_FIELD NVARCHAR2(1000),
    VALUE_FIELD NUMBER(9,2),
    DISCOUNT BINARY_DOUBLE,
    DISCOUNT_TYPE NVARCHAR2(1000),
    TAXABLE NUMBER(1,0),
    TAX BINARY_DOUBLE,
    MISC NVARCHAR2(1000),
    DISCOUNT_TOTAL BINARY_DOUBLE,
    PRICE_SUFFIX NVARCHAR2(1000),
    SUB_TOTAL NUMBER(9,2),
    SUBTOTAL_WO_DISCOUNT NUMBER(9,2),
    TAX_TOTAL BINARY_DOUBLE,
    TOTAL NUMBER(9,2),
    INVOICE_ID NUMBER(10,0),
    CHARGE_GROUP NVARCHAR2(1000),
    PAYMENT_ACCOUNT NVARCHAR2(1000),
    PRICE_STR NVARCHAR2(1000),
    IS_VOID NUMBER(1,0),
    DATE_FIELD DATE,
    TEXT_AUX NVARCHAR2(1000),
    TEXT_AUX2 NVARCHAR2(1000),
    DISCOUNT_DATE_TIME DATE,
    DISCOUNT_USER_ID NVARCHAR2(1000),
    NOTES NVARCHAR2(1000),
    PR_TYPE NVARCHAR2(1000),
    STATUS_FIELD NVARCHAR2(1000),
    DELETION_USER_ID NVARCHAR2(1000),
    DELETION_DATE_TIME DATE,
    OVERPAYMENT_ID NUMBER(10,0),
    VOID_USER NVARCHAR2(1000),
    VOID_DATE_TIME DATE,
    MISC2 NVARCHAR2(1000),
    PREPAYMENT_ID NUMBER(10,0),
    CREDIT_INVOICE_ID NUMBER(10,0),
    ALLOCATION_TYPE NVARCHAR2(1000),
    RESERVATION_ID NUMBER(10,0),
    ITEM_MASTER_ID NUMBER(10,0),
    ASPNET_USER_ID NVARCHAR2(256),
    INVOICE_ITEM_TYPE_ID NUMBER(10,0),
    SEASONAL_PRICE_ID NUMBER(10,0),
    TRANSIENT_PRICE_ID NUMBER(10,0),
    SV_JOB_ID NUMBER(10,0),
    ORIGINAL_CREDIT_ITEM NUMBER(10,0),
    TAX_EXEMPT NUMBER(1,0),
    LAST_MODIFIED_DATE_TIME DATE,
    LAST_MODIFIED_ASPNET_USER NVARCHAR2(1000),
    DELETION_REASON NVARCHAR2(1000),
    VOID_REASON NVARCHAR2(1000),
    START_DATE_TIME DATE,
    END_DATE_TIME DATE,
    CREATION_PARTNER_ID NUMBER(10,0),
    DELETE_PARTNER_ID NUMBER(10,0),
    VOID_PARTNER_ID NUMBER(10,0),
    ORIGINAL_PRICE BINARY_DOUBLE,
    OVERRIDE_XERO_TAX_RATE NUMBER(10,0),
    OVERRIDE_XERO_SALES_ACCOUNT NUMBER(10,0),
    ORIGINAL_RESERVATION_PRICE BINARY_DOUBLE,
    NUMBER_OF_DECIMALS NUMBER(10,0),
    STRIPE_TRANSACTION_DATA_ID NUMBER(10,0),
    VALUE_ALTERNATIVE BINARY_DOUBLE,
    STRIPE_TERMINAL_ID NUMBER(10,0),
    STRIPE_APPLICATION_NAME NVARCHAR2(1000),
    STRIPE_AID NVARCHAR2(1000),
    ENTERED_AMOUNT BINARY_DOUBLE,
    EXCHANGE_RATE NUMBER(9,2),
    CURRENCIES_ID NUMBER(10,0),
    SV_CHARGE_INSTANCE_ID NUMBER(10,0),
    SV_LABOR_INSTANCE_ID NUMBER(10,0),
    SV_PART_INSTANCE_ID NUMBER(10,0),
    REVENUE_GL_CODE NVARCHAR2(1000),
    AR_GL_CODE NVARCHAR2(1000),
    PAYMENT_GL_CODE NVARCHAR2(1000),
    COGS_GL_CODE NVARCHAR2(1000),
    INVENTORY_GL_CODE NVARCHAR2(1000),
    SALES_TAX_GL_CODE NVARCHAR2(1000),
    PREPAYMENT_GL_CODE NVARCHAR2(1000),
    ACCOUNT_TYPE NVARCHAR2(1000),
    APPLICATION_CRYPTOGRAM NVARCHAR2(1000),
    AUTHORIZATION_CODE NVARCHAR2(1000),
    AUTHORIZATION_RESPONSE_CODE NVARCHAR2(1000),
    CARDHOLDER_VERIFICATION_METHOD NVARCHAR2(1000),
    TERMINAL_VERIFICATION_RESULTS NVARCHAR2(1000),
    TRANSACTION_STATUS_INFORMATION NVARCHAR2(1000),
    TRACKING_CODE NVARCHAR2(1000),
    DISCOUNT_GL_CODE NVARCHAR2(1000),
    OVERRIDE_TRACKING_CATEGORY1 NUMBER(10,0),
    OVERRIDE_TRACKING_CATEGORY2 NUMBER(10,0),
    QUICKBOOKS_PAYMENT_ID NVARCHAR2(1000),
    ALLOW_TOTAL_PRICE_ENTRY NUMBER(1,0),
    ADDED_AUTOMATICALLY NUMBER(1,0),
    ALLOCATION_PERFORMED_DATE DATE,
    CREATED_DATE DATE,
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transactions Table
CREATE TABLE DW_MOLO_TRANSACTIONS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    CREATION_TIME DATE,
    INVOICE_ID NUMBER(10,0),
    TRANSACTION_TYPE_ID NUMBER(10,0),
    TRANSACTION_METHOD_ID NUMBER(10,0),
    VALUE_FIELD NUMBER(9,2),
    IS_REFUNDED NUMBER(1,0),
    CUSTOMER_IP_ADDRESS NVARCHAR2(1000),
    CUSTOMER_DEVICE NVARCHAR2(1000),
    REFUND_REASON NVARCHAR2(1000),
    AUX NVARCHAR2(1000),
    CHECK_NUMBER NVARCHAR2(1000),
    CC_TYPE NVARCHAR2(1000),
    INVOICE_ITEM_ID NUMBER(10,0),
    SENT_TO_XERO NUMBER(1,0),
    OVERPAYMENT_ID NVARCHAR2(1000),
    PAYMENT_COLLECTED_OFFLINE NUMBER(1,0),
    PART_OF_OVERPAYMENT NUMBER(1,0),
    PREPAYMENT_ID NVARCHAR2(1000),
    ACCOUNT_TRANSACTION_TRANSACTION_ID NUMBER(10,0),
    PAYMENT_ID NUMBER(10,0),
    CREATION_DATE DATE,
    ASPNET_USER_ID NVARCHAR2(256),
    HASH_ID NVARCHAR2(1000),
    CUSTOM_TRANSACTION_METHODS_ID NUMBER(10,0),
    REFERENCE NVARCHAR2(1000),
    IS_VOID NUMBER(1,0),
    AMOUNT_REFUNDED BINARY_DOUBLE,
    STRIPE_TRANSACTION_DATA_ID NUMBER(10,0),
    PAYMENT_INTENT_ID NVARCHAR2(1000),
    SENT_TO_PAYOUT NUMBER(1,0),
    STRIPE_AUTHORIZATIONS_ID NUMBER(10,0),
    STRIPE_RESPONSE_ID NUMBER(10,0),
    STRIPE_READER_SERIAL_NUMBER NVARCHAR2(1000),
    STRIPE_TERMINAL_ID NVARCHAR2(1000),
    CREATED_ON_MOBILE NUMBER(1,0),
    ONLINE_PERCENT_FEE BINARY_DOUBLE,
    ONLINE_FEE_AMOUNT BINARY_DOUBLE,
    SCHEDULED_FOR_ONLINE_FEE_CRON NUMBER(1,0),
    ONLINE_PAYMENT_FEE_ID NUMBER(10,0),
    BANK_NAME NVARCHAR2(1000),
    LAST4 NVARCHAR2(1000),
    STRIPE_BANK_ACCOUNT_ID NUMBER(10,0),
    STRIPE_BATCH_ID NUMBER(10,0),
    ROUTING_NUMBER NVARCHAR2(1000),
    FULLY_REFUNDED NUMBER(1,0),
    LAST_UPDATED DATE,
    PAYMENT_SOURCE NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seasonal Prices Table
CREATE TABLE DW_MOLO_SEASONAL_PRICES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    SEASON_NAME NVARCHAR2(1000),
    START_DATE DATE,
    END_DATE DATE,
    SEASONAL_CHARGE_METHOD_ID NUMBER(10,0),
    PRICE_PER_FOOT NUMBER(9,2),
    FLAT_RATE NUMBER(9,2),
    TAXABLE NUMBER(1,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    ACTIVE NUMBER(1,0),
    TAX BINARY_DOUBLE,
    RATE_DETAILS NVARCHAR2(1000),
    RATE_SHORT_NAME NVARCHAR2(1000),
    ONLINE_PAYMENT_PLACEHOLDER NVARCHAR2(1000),
    XERO_ITEM_CODE NVARCHAR2(1000),
    XERO_ID NVARCHAR2(1000),
    FIRST_TRACKING_CATEGORY NUMBER(10,0),
    SECOND_TRACKING_CATEGORY NUMBER(10,0),
    SEASONAL_INVOICING_METHOD_ID NUMBER(10,0),
    SV_INVENTORY_CATEGORY_ID NUMBER(10,0),
    SV_INVENTORY_SUB_CATEGORY_ID NUMBER(10,0),
    CREATION_DATE_TIME DATE,
    ASPNET_USER_ID NVARCHAR2(256),
    CHECK_IN_TERMS NVARCHAR2(1000),
    CHECK_OUT_TERMS NVARCHAR2(1000),
    ONLINE_PAYMENT_COMPLETION NVARCHAR2(1000),
    DUE_DATE_DAYS NUMBER(10,0),
    DUE_DATE_SETTINGS_ID NUMBER(10,0),
    CHARGE_CATEGORY NVARCHAR2(1000),
    INTRO_TEXT NVARCHAR2(1000),
    REVENUE_GL_CODE NVARCHAR2(1000),
    AR_GL_CODE NVARCHAR2(1000),
    SALES_TAX_GL_CODE NVARCHAR2(1000),
    DELETION_DATETIME DATE,
    DELETION_ASPNET_USER_ID NVARCHAR2(256),
    RECORD_STATUS_ID NUMBER(10,0),
    DEFERRED_REVENUE_RECOGNITION NUMBER(1,0),
    DEFERRED_RECOGNITION_GL_CODE NVARCHAR2(1000),
    TRACKING_CODE NVARCHAR2(1000),
    XERO_RECOGNITION_ACCOUNT_ID NUMBER(10,0),
    REVENUE_XERO_ACCOUNT_ID NUMBER(10,0),
    ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS NUMBER(1,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transient Prices Table
CREATE TABLE DW_MOLO_TRANSIENT_PRICES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    START_DATE DATE,
    END_DATE DATE,
    FEE NUMBER(9,2),
    RATE_NAME NVARCHAR2(1000),
    TRANSIENT_CHARGE_METHOD_ID NUMBER(10,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    TAXABLE NUMBER(1,0),
    TAX BINARY_DOUBLE,
    RATE_DETAILS NVARCHAR2(1000),
    RATE_SHORT_NAME NVARCHAR2(1000),
    ONLINE_PAYMENT_PLACEHOLDER NVARCHAR2(1000),
    XERO_ITEM_CODE NVARCHAR2(1000),
    XERO_ID NVARCHAR2(1000),
    FIRST_TRACKING_CATEGORY NUMBER(10,0),
    SECOND_TRACKING_CATEGORY NUMBER(10,0),
    TRANSIENT_INVOICING_METHOD_ID NUMBER(10,0),
    SV_INVENTORY_CATEGORY_ID NUMBER(10,0),
    SV_INVENTORY_SUB_CATEGORY_ID NUMBER(10,0),
    CREATION_DATE_TIME DATE,
    ASPNET_USER_ID NVARCHAR2(256),
    CHECK_IN_TERMS NVARCHAR2(1000),
    CHECK_OUT_TERMS NVARCHAR2(1000),
    ONLINE_PAYMENT_COMPLETION NVARCHAR2(1000),
    DUE_DATE_DAYS NUMBER(10,0),
    DUE_DATE_SETTINGS_ID NUMBER(10,0),
    HOURLY_CALCULATION NVARCHAR2(1000),
    ROUND_MINUTES NUMBER(10,0),
    MINIMUM_HOURS NUMBER(10,0),
    NUM_HOURS_BLOCK NUMBER(10,0),
    CHARGE_CATEGORY NVARCHAR2(1000),
    INTRO_TEXT NVARCHAR2(1000),
    REVENUE_GL_CODE NVARCHAR2(1000),
    AR_GL_CODE NVARCHAR2(1000),
    SALES_TAX_GL_CODE NVARCHAR2(1000),
    DELETION_DATETIME DATE,
    DELETION_ASPNET_USER_ID NVARCHAR2(256),
    RECORD_STATUS_ID NUMBER(10,0),
    RECURRING_INVOICE_OPTIONS_ID NUMBER(10,0),
    RECURRING NUMBER(1,0),
    TRACKING_CODE NVARCHAR2(1000),
    ALTERNATE_RESERVATION_NAME NVARCHAR2(1000),
    RESOURCE_RATE NUMBER(1,0),
    QUANTITY_CAP NUMBER(10,0),
    ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS NUMBER(1,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Slips Table
CREATE TABLE DW_MOLO_SLIPS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    TYPE NVARCHAR2(1000),
    RECOMMENDED_LOA NVARCHAR2(1000),
    RECOMMENDED_BEAM NVARCHAR2(1000),
    RECOMMENDED_DRAFT NVARCHAR2(1000),
    RECOMMENDED_AIR_DRAFT NVARCHAR2(1000),
    MAXIMUM_LOA NVARCHAR2(1000),
    MAXIMUM_BEAM NVARCHAR2(1000),
    MAXIMUM_DRAFT NVARCHAR2(1000),
    MAXIMUM_AIR_DRAFT NVARCHAR2(1000),
    MARINA_LOCATION_ID NUMBER(10,0),
    PIER_ID NUMBER(10,0),
    STATUS NVARCHAR2(1000),
    START_DATE DATE,
    END_DATE DATE,
    DO_NOT_COUNT_IN_OCCUPANCY NUMBER(1,0),
    ACTIVE NUMBER(1,0),
    CREATION_DATE_TIME DATE,
    CREATION_USER NVARCHAR2(1000),
    SLIP_TYPE_ID NUMBER(10,0),
    PAYMENT_PROCESSING_FEE BINARY_DOUBLE,
    MANAGEMENT_FEE BINARY_DOUBLE,
    OWNER_ID NUMBER(10,0),
    PAYMENT_PROCESSING_FEE_TYPE_ID NUMBER(10,0),
    MANAGEMENT_FEE_TYPE_ID NUMBER(10,0),
    OVERRIDE_OCCUPANCY_LOA NVARCHAR2(1000),
    HASH_ID NVARCHAR2(1000),
    MAINTENANCE_FEE BINARY_DOUBLE,
    SVG_ID NVARCHAR2(1000),
    ASSESSMENT BINARY_DOUBLE,
    LOAN BINARY_DOUBLE,
    ORDER_COLUMN NUMBER(10,0),
    SIGN_NAME NVARCHAR2(1000),
    MAX_WEIGHT BINARY_DOUBLE,
    MAX_REVENUE BINARY_DOUBLE,
    TRANSIENT_PRICE_ID NUMBER(10,0),
    SEASONAL_PRICE_ID NUMBER(10,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Piers Table  
CREATE TABLE DW_MOLO_PIERS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    MARINA_LOCATION_ID NUMBER(10,0),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Item Masters Table (Inventory)
CREATE TABLE DW_MOLO_ITEM_MASTERS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    AMOUNT BINARY_DOUBLE,
    ITEM_CHARGE_METHOD_ID NUMBER(10,0),
    TAXABLE NUMBER(1,0),
    AVAILABLE_AS_ADD_ON NUMBER(1,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    PRICE BINARY_DOUBLE,
    TAX BINARY_DOUBLE,
    SINGLE NUMBER(1,0),
    CHARGE_CATEGORY NVARCHAR2(1000),
    AMOUNT_IS_DECIMAL NUMBER(1,0),
    NUMBER_OF_DECIMALS NUMBER(10,0),
    ITEM_SHORT_NAME NVARCHAR2(1000),
    ITEM_CODE NVARCHAR2(1000),
    TRACKED_INVENTORY NUMBER(1,0),
    QUANTITY_ON_HAND BINARY_DOUBLE,
    PURCHASE_PRICE BINARY_DOUBLE,
    FIRST_TRACKING_CATEGORY NUMBER(10,0),
    SECOND_TRACKING_CATEGORY NUMBER(10,0),
    XERO_ID NVARCHAR2(1000),
    SALE_FREQUENCY NUMBER(10,0),
    LOW_QUANTITY_WARNING BINARY_DOUBLE,
    MARINA_LOCATION1_ID NUMBER(10,0),
    MARINA_LOCATION2_ID NUMBER(10,0),
    PEDESTAL_ID NUMBER(10,0),
    PEDESTAL1_ID NUMBER(10,0),
    QB_ITEM_ID NUMBER(10,0),
    XERO_ITEM_ID NUMBER(10,0),
    BARCODE NVARCHAR2(1000),
    DISTRIBUTE_TO_OWNERS NUMBER(1,0),
    FUEL_CLOUD_PRODUCT_ID NVARCHAR2(1000),
    HASH_ID NVARCHAR2(1000),
    REQUIRES_AGE_VERIFICATION NUMBER(1,0),
    MINIMUM_AGE NUMBER(10,0),
    CREATION_DATE_TIME DATE,
    CREATION_ASPNET_USER_ID NVARCHAR2(256),
    RECORD_STATUS_ID NUMBER(10,0),
    UPDATE_HASH NVARCHAR2(1000),
    SUBLET_ITEM NUMBER(1,0),
    INTERNAL_REVENUE_XERO_ACCOUNT_ID NUMBER(10,0),
    INTERNAL_COGS_XERO_ACCOUNT_ID NUMBER(10,0),
    WIP_XERO_ACCOUNT_ID NUMBER(10,0),
    INVENTORY_REVALUATION_ID NUMBER(10,0),
    MARINA_LOCATION6_ID NUMBER(10,0),
    FINALE_PRODUCT_URL NVARCHAR2(1000),
    REVENUE_GL_CODE NVARCHAR2(1000),
    COGS_GL_CODE NVARCHAR2(1000),
    INVENTORY_GL_CODE NVARCHAR2(1000),
    AR_GL_CODE NVARCHAR2(1000),
    SALES_TAX_GL_CODE NVARCHAR2(1000),
    ONLY_USE_LAST2_AVERAGE NUMBER(1,0),
    DEFERRED_REVENUE_RECOGNITION NUMBER(1,0),
    DEFERRED_RECOGNITION_GL_CODE NVARCHAR2(1000),
    TRACKING_CODE NVARCHAR2(1000),
    ADD_DESCRIPTION_TO_INVOICE_NOTE NUMBER(1,0),
    MARINA_LOCATION7_ID NUMBER(10,0),
    IGNORE_INVENTORY_QOH NUMBER(1,0),
    QOH_COMMITTED BINARY_DOUBLE,
    QOH_ON_ORDER BINARY_DOUBLE,
    ALLOW_TOTAL_PRICE_ENTRY NUMBER(1,0),
    MARINA_LOCATION9_ID NUMBER(10,0),
    ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS NUMBER(1,0),
    ORDER_COLUMN NUMBER(10,0),
    ENABLE_NEGATIVE_INVENTORY NUMBER(1,0),
    WIP BINARY_DOUBLE,
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insurance Table
CREATE TABLE DW_MOLO_INSURANCE (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    PROVIDER NVARCHAR2(1000),
    LISTED_INDIVIDUAL NVARCHAR2(1000),
    ACCOUNT_NUMBER NVARCHAR2(1000),
    POLICY_NUMBER NVARCHAR2(1000),
    GROUP_NUMBER NVARCHAR2(1000),
    LIABILITY_MAXIMUM BINARY_DOUBLE,
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    NOTES NVARCHAR2(1000),
    CREATION_USER NVARCHAR2(1000),
    CREATION_DATE_TIME DATE,
    LAST_EDIT_USER NVARCHAR2(1000),
    LAST_EDIT_DATE_TIME DATE,
    DELETE_USER NVARCHAR2(1000),
    DELETE_DATE_TIME DATE,
    INSURANCE_STATUS_ID NUMBER(10,0),
    BOAT_ID NUMBER(10,0),
    HASH_ID NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Equipment Table
CREATE TABLE DW_MOLO_EQUIPMENT (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    HASH_ID NVARCHAR2(1000),
    MODEL NVARCHAR2(1000),
    SERIAL_NUMBER NVARCHAR2(1000),
    YEAR_OF_MANUFACTURE NVARCHAR2(1000),
    YEAR_OF_REBUILD_REFIT NVARCHAR2(1000),
    NUMBER_POSITION NVARCHAR2(1000),
    NUMBER_OF_CYLINDERS NUMBER(10,0),
    DISPLACEMENT NVARCHAR2(1000),
    OUTPUT NVARCHAR2(1000),
    LENGTH NVARCHAR2(1000),
    WIDTH NVARCHAR2(1000),
    HEIGHT NVARCHAR2(1000),
    WEIGHT BINARY_DOUBLE,
    CAPACITY BINARY_DOUBLE,
    MATERIAL NVARCHAR2(1000),
    NUMBER_OF_AXLES NUMBER(10,0),
    MAX_LENGTH_CAPACITY BINARY_DOUBLE,
    TIRE_SIZE NVARCHAR2(1000),
    NUMBER_OF_BRAKES NVARCHAR2(1000),
    BALL_DIAMETER NVARCHAR2(1000),
    CODE_COMBINATION NVARCHAR2(1000),
    NOTES NVARCHAR2(1000),
    EQUIPMENT_TYPE_ID NUMBER(10,0),
    VESSEL_ENGINE_CLASS_ID NUMBER(10,0),
    EQUIPMENT_FUEL_TYPE_ID NUMBER(10,0),
    SV_MANUFACTURER_ID NUMBER(10,0),
    MARINA_LOCATION_ID NUMBER(10,0),
    LICENSE_PLATE NVARCHAR2(1000),
    DELETION_DATE_TIME DATE,
    RECORD_STATUS_ID NUMBER(10,0),
    DELETION_ASPNET_USER_ID NVARCHAR2(256),
    CREATION_USER NVARCHAR2(1000),
    CREATION_DATE DATE,
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add indexes for better performance
CREATE INDEX IDX_DW_MOLO_COMPANIES_ORG ON DW_MOLO_COMPANIES (ORGANIZATION_ID);
CREATE INDEX IDX_DW_MOLO_CONTACTS_MARINA ON DW_MOLO_CONTACTS (MARINA_LOCATION_ID);
CREATE INDEX IDX_DW_MOLO_BOATS_MARINA ON DW_MOLO_BOATS (MARINA_LOCATION_ID);
CREATE INDEX IDX_DW_MOLO_RESERVATIONS_MARINA ON DW_MOLO_RESERVATIONS (MARINA_LOCATION_ID);
CREATE INDEX IDX_DW_MOLO_RESERVATIONS_CONTACT ON DW_MOLO_RESERVATIONS (CONTACT_ID);
CREATE INDEX IDX_DW_MOLO_RESERVATIONS_BOAT ON DW_MOLO_RESERVATIONS (BOAT_ID);
CREATE INDEX IDX_DW_MOLO_INVOICES_RESERVATION ON DW_MOLO_INVOICES (RESERVATION_ID);
CREATE INDEX IDX_DW_MOLO_INVOICE_ITEMS_INVOICE ON DW_MOLO_INVOICE_ITEMS (INVOICE_ID);
CREATE INDEX IDX_DW_MOLO_TRANSACTIONS_INVOICE ON DW_MOLO_TRANSACTIONS (INVOICE_ID);
CREATE INDEX IDX_DW_MOLO_SLIPS_MARINA ON DW_MOLO_SLIPS (MARINA_LOCATION_ID);
CREATE INDEX IDX_DW_MOLO_ITEM_MASTERS_MARINA ON DW_MOLO_ITEM_MASTERS (MARINA_LOCATION_ID);

-- Add comments to tables
COMMENT ON TABLE DW_MOLO_COMPANIES IS 'Company/Organization information';
COMMENT ON TABLE DW_MOLO_MARINA_LOCATIONS IS 'Marina location settings and configuration';
COMMENT ON TABLE DW_MOLO_CONTACTS IS 'Marina customers and contacts';
COMMENT ON TABLE DW_MOLO_BOATS IS 'Vessel information for marina customers';
COMMENT ON TABLE DW_MOLO_ACCOUNTS IS 'Customer account linking table';
COMMENT ON TABLE DW_MOLO_RESERVATIONS IS 'Slip reservations and bookings';
COMMENT ON TABLE DW_MOLO_INVOICES IS 'Customer invoices and billing';
COMMENT ON TABLE DW_MOLO_INVOICE_ITEMS IS 'Invoice line items and charges';
COMMENT ON TABLE DW_MOLO_TRANSACTIONS IS 'Payment transactions';
COMMENT ON TABLE DW_MOLO_SEASONAL_PRICES IS 'Seasonal rate pricing structure';
COMMENT ON TABLE DW_MOLO_TRANSIENT_PRICES IS 'Transient/hourly rate pricing structure';
COMMENT ON TABLE DW_MOLO_SLIPS IS 'Marina slip inventory';
COMMENT ON TABLE DW_MOLO_PIERS IS 'Marina pier information';
COMMENT ON TABLE DW_MOLO_ITEM_MASTERS IS 'Inventory items and services';
COMMENT ON TABLE DW_MOLO_INSURANCE IS 'Vessel insurance information';
COMMENT ON TABLE DW_MOLO_EQUIPMENT IS 'Vessel equipment information';

-- Record Status Table (Lookup)
CREATE TABLE DW_MOLO_RECORD_STATUS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Reservation Status Table (Lookup)
CREATE TABLE DW_MOLO_RESERVATION_STATUS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Reservation Types Table (Lookup)
CREATE TABLE DW_MOLO_RESERVATION_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Account Status Table (Lookup)
CREATE TABLE DW_MOLO_ACCOUNT_STATUS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Boat Types Table (Lookup)
CREATE TABLE DW_MOLO_BOAT_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Power Needs Table (Lookup)
CREATE TABLE DW_MOLO_POWER_NEEDS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact Types Table (Lookup)
CREATE TABLE DW_MOLO_CONTACT_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact Auto Charge Table (Lookup)
CREATE TABLE DW_MOLO_CONTACT_AUTO_CHARGE (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Statements Preference Table (Lookup)
CREATE TABLE DW_MOLO_STATEMENTS_PREFERENCE (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invoice Status Table (Lookup)
CREATE TABLE DW_MOLO_INVOICE_STATUS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invoice Types Table (Lookup)
CREATE TABLE DW_MOLO_INVOICE_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invoice Item Types Table (Lookup)
CREATE TABLE DW_MOLO_INVOICE_ITEM_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transaction Types Table (Lookup)
CREATE TABLE DW_MOLO_TRANSACTION_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transaction Methods Table (Lookup)
CREATE TABLE DW_MOLO_TRANSACTION_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Payment Methods Table (Lookup)
CREATE TABLE DW_MOLO_PAYMENT_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seasonal Charge Methods Table (Lookup)
CREATE TABLE DW_MOLO_SEASONAL_CHARGE_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seasonal Invoicing Methods Table (Lookup)
CREATE TABLE DW_MOLO_SEASONAL_INVOICING_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transient Charge Methods Table (Lookup)
CREATE TABLE DW_MOLO_TRANSIENT_CHARGE_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transient Invoicing Methods Table (Lookup)
CREATE TABLE DW_MOLO_TRANSIENT_INVOICING_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Recurring Invoice Options Table (Lookup)
CREATE TABLE DW_MOLO_RECURRING_INVOICE_OPTIONS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Due Date Settings Table (Lookup)
CREATE TABLE DW_MOLO_DUE_DATE_SETTINGS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Slip Types Table (Lookup)
CREATE TABLE DW_MOLO_SLIP_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Item Charge Methods Table (Lookup)
CREATE TABLE DW_MOLO_ITEM_CHARGE_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insurance Status Table (Lookup)
CREATE TABLE DW_MOLO_INSURANCE_STATUS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Equipment Types Table (Lookup)
CREATE TABLE DW_MOLO_EQUIPMENT_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Equipment Fuel Types Table (Lookup)
CREATE TABLE DW_MOLO_EQUIPMENT_FUEL_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Vessel Engine Class Table (Lookup)
CREATE TABLE DW_MOLO_VESSEL_ENGINE_CLASS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cities Table (Lookup)
CREATE TABLE DW_MOLO_CITIES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    STATE NVARCHAR2(1000),
    COUNTRY NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Countries Table (Lookup)
CREATE TABLE DW_MOLO_COUNTRIES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    CODE NVARCHAR2(10),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Currencies Table (Lookup)
CREATE TABLE DW_MOLO_CURRENCIES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    CODE NVARCHAR2(10),
    SYMBOL NVARCHAR2(10),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Phone Types Table (Lookup)
CREATE TABLE DW_MOLO_PHONE_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Address Types Table (Lookup)
CREATE TABLE DW_MOLO_ADDRESS_TYPES (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Installments Payment Methods Table (Lookup)
CREATE TABLE DW_MOLO_INSTALLMENTS_PAYMENT_METHODS (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Payments Provider Table (Lookup)
CREATE TABLE DW_MOLO_PAYMENTS_PROVIDER (
    DW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID NUMBER(10,0),
    NAME NVARCHAR2(1000),
    DW_LAST_INSERTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DW_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add comments to lookup tables
COMMENT ON TABLE DW_MOLO_RECORD_STATUS IS 'Lookup table for record status (Active, Inactive, Deleted)';
COMMENT ON TABLE DW_MOLO_RESERVATION_STATUS IS 'Lookup table for reservation status';
COMMENT ON TABLE DW_MOLO_RESERVATION_TYPES IS 'Lookup table for reservation types';
COMMENT ON TABLE DW_MOLO_ACCOUNT_STATUS IS 'Lookup table for account status';
COMMENT ON TABLE DW_MOLO_BOAT_TYPES IS 'Lookup table for boat/vessel types';
COMMENT ON TABLE DW_MOLO_POWER_NEEDS IS 'Lookup table for electrical power requirements';
COMMENT ON TABLE DW_MOLO_CONTACT_TYPES IS 'Lookup table for contact types (Owner, Captain, etc.)';
COMMENT ON TABLE DW_MOLO_CONTACT_AUTO_CHARGE IS 'Lookup table for contact auto-charge settings';
COMMENT ON TABLE DW_MOLO_STATEMENTS_PREFERENCE IS 'Lookup table for customer statement preferences';
COMMENT ON TABLE DW_MOLO_INVOICE_STATUS IS 'Lookup table for invoice status';
COMMENT ON TABLE DW_MOLO_INVOICE_TYPES IS 'Lookup table for invoice types';
COMMENT ON TABLE DW_MOLO_INVOICE_ITEM_TYPES IS 'Lookup table for invoice item types';
COMMENT ON TABLE DW_MOLO_TRANSACTION_TYPES IS 'Lookup table for transaction types';
COMMENT ON TABLE DW_MOLO_TRANSACTION_METHODS IS 'Lookup table for transaction methods';
COMMENT ON TABLE DW_MOLO_PAYMENT_METHODS IS 'Lookup table for payment methods';
COMMENT ON TABLE DW_MOLO_SEASONAL_CHARGE_METHODS IS 'Lookup table for seasonal pricing charge methods';
COMMENT ON TABLE DW_MOLO_SEASONAL_INVOICING_METHODS IS 'Lookup table for seasonal invoicing methods';
COMMENT ON TABLE DW_MOLO_TRANSIENT_CHARGE_METHODS IS 'Lookup table for transient pricing charge methods';
COMMENT ON TABLE DW_MOLO_TRANSIENT_INVOICING_METHODS IS 'Lookup table for transient invoicing methods';
COMMENT ON TABLE DW_MOLO_RECURRING_INVOICE_OPTIONS IS 'Lookup table for recurring invoice options';
COMMENT ON TABLE DW_MOLO_DUE_DATE_SETTINGS IS 'Lookup table for due date calculation settings';
COMMENT ON TABLE DW_MOLO_SLIP_TYPES IS 'Lookup table for slip types';
COMMENT ON TABLE DW_MOLO_ITEM_CHARGE_METHODS IS 'Lookup table for inventory item charge methods';
COMMENT ON TABLE DW_MOLO_INSURANCE_STATUS IS 'Lookup table for insurance status';
COMMENT ON TABLE DW_MOLO_EQUIPMENT_TYPES IS 'Lookup table for equipment types';
COMMENT ON TABLE DW_MOLO_EQUIPMENT_FUEL_TYPES IS 'Lookup table for equipment fuel types';
COMMENT ON TABLE DW_MOLO_VESSEL_ENGINE_CLASS IS 'Lookup table for vessel engine classifications';
COMMENT ON TABLE DW_MOLO_CITIES IS 'Lookup table for cities';
COMMENT ON TABLE DW_MOLO_COUNTRIES IS 'Lookup table for countries';
COMMENT ON TABLE DW_MOLO_CURRENCIES IS 'Lookup table for currencies';
COMMENT ON TABLE DW_MOLO_PHONE_TYPES IS 'Lookup table for phone types';
COMMENT ON TABLE DW_MOLO_ADDRESS_TYPES IS 'Lookup table for address types';
COMMENT ON TABLE DW_MOLO_INSTALLMENTS_PAYMENT_METHODS IS 'Lookup table for installment payment methods';
COMMENT ON TABLE DW_MOLO_PAYMENTS_PROVIDER IS 'Lookup table for payment providers';

COMMIT;