
-- ============================================================================
-- Merge STG_STELLAR_CATEGORIES to DW_STELLAR_CATEGORIES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_CATEGORIES
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_CATEGORIES tgt
    USING STG_STELLAR_CATEGORIES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.CATEGORY_NAME = src.CATEGORY_NAME,
            tgt.FRONTEND_DISPLAY = src.FRONTEND_DISPLAY,
            tgt.FRONTEND_NAME = src.FRONTEND_NAME,
            tgt.FRONTEND_TYPE = src.FRONTEND_TYPE,
            tgt.FRONTEND_POSITION = src.FRONTEND_POSITION,
            tgt.FILTER_UNIT_TYPE_ENABLED = src.FILTER_UNIT_TYPE_ENABLED,
            tgt.FILTER_UNIT_TYPE_NAME = src.FILTER_UNIT_TYPE_NAME,
            tgt.FILTER_UNIT_TYPE_POSITION = src.FILTER_UNIT_TYPE_POSITION,
            tgt.MIN_NIGHTS_MULTI_DAY = src.MIN_NIGHTS_MULTI_DAY,
            tgt.CALENDAR_BANNER_TEXT = src.CALENDAR_BANNER_TEXT,
            tgt.DESCRIPTION_TEXT = src.DESCRIPTION_TEXT,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.LOCATION_ID, -1) != NVL(src.LOCATION_ID, -1)
            OR NVL(tgt.CATEGORY_NAME, '~') != NVL(src.CATEGORY_NAME, '~')
            OR NVL(tgt.FRONTEND_DISPLAY, '~') != NVL(src.FRONTEND_DISPLAY, '~')
            OR NVL(tgt.FRONTEND_NAME, '~') != NVL(src.FRONTEND_NAME, '~')
            OR NVL(tgt.FRONTEND_TYPE, '~') != NVL(src.FRONTEND_TYPE, '~')
            OR NVL(tgt.FRONTEND_POSITION, '~') != NVL(src.FRONTEND_POSITION, '~')
            OR NVL(tgt.FILTER_UNIT_TYPE_ENABLED, '~') != NVL(src.FILTER_UNIT_TYPE_ENABLED, '~')
            OR NVL(tgt.FILTER_UNIT_TYPE_NAME, '~') != NVL(src.FILTER_UNIT_TYPE_NAME, '~')
            OR NVL(tgt.FILTER_UNIT_TYPE_POSITION, '~') != NVL(src.FILTER_UNIT_TYPE_POSITION, '~')
            OR NVL(tgt.MIN_NIGHTS_MULTI_DAY, '~') != NVL(src.MIN_NIGHTS_MULTI_DAY, '~')
            OR NVL(tgt.CALENDAR_BANNER_TEXT, '~') != NVL(src.CALENDAR_BANNER_TEXT, '~')
            OR NVL(tgt.DESCRIPTION_TEXT, '~') != NVL(src.DESCRIPTION_TEXT, '~')
            OR NVL(tgt.CREATED_AT, '~') != NVL(src.CREATED_AT, '~')
            OR NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, CATEGORY_NAME, FRONTEND_DISPLAY, FRONTEND_NAME, FRONTEND_TYPE, FRONTEND_POSITION, FILTER_UNIT_TYPE_ENABLED, FILTER_UNIT_TYPE_NAME, FILTER_UNIT_TYPE_POSITION, MIN_NIGHTS_MULTI_DAY, CALENDAR_BANNER_TEXT, DESCRIPTION_TEXT, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.CATEGORY_NAME, src.FRONTEND_DISPLAY, src.FRONTEND_NAME, src.FRONTEND_TYPE, src.FRONTEND_POSITION, src.FILTER_UNIT_TYPE_ENABLED, src.FILTER_UNIT_TYPE_NAME, src.FILTER_UNIT_TYPE_POSITION, src.MIN_NIGHTS_MULTI_DAY, src.CALENDAR_BANNER_TEXT, src.DESCRIPTION_TEXT, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_CATEGORIES: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_CATEGORIES: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_CATEGORIES;
/
