
-- ============================================================================
-- Merge STG_MOLO_SEASONAL_PRICES to DW_MOLO_SEASONAL_PRICES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_SEASONAL_PRICES
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_SEASONAL_PRICES tgt
    USING STG_MOLO_SEASONAL_PRICES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.SEASON_NAME = src.SEASON_NAME,
            tgt.START_DATE = src.START_DATE,
            tgt.END_DATE = src.END_DATE,
            tgt.SEASONAL_CHARGE_METHOD_ID = src.SEASONAL_CHARGE_METHOD_ID,
            tgt.PRICE_PER_FOOT = src.PRICE_PER_FOOT,
            tgt.FLAT_RATE = src.FLAT_RATE,
            tgt.TAXABLE = src.TAXABLE,
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.ACTIVE = src.ACTIVE,
            tgt.TAX = src.TAX,
            tgt.RATE_DETAILS = src.RATE_DETAILS,
            tgt.RATE_SHORT_NAME = src.RATE_SHORT_NAME,
            tgt.ONLINE_PAYMENT_PLACEHOLDER = src.ONLINE_PAYMENT_PLACEHOLDER,
            tgt.XERO_ITEM_CODE = src.XERO_ITEM_CODE,
            tgt.XERO_ID = src.XERO_ID,
            tgt.FIRST_TRACKING_CATEGORY = src.FIRST_TRACKING_CATEGORY,
            tgt.SECOND_TRACKING_CATEGORY = src.SECOND_TRACKING_CATEGORY,
            tgt.SEASONAL_INVOICING_METHOD_ID = src.SEASONAL_INVOICING_METHOD_ID,
            tgt.SV_INVENTORY_CATEGORY_ID = src.SV_INVENTORY_CATEGORY_ID,
            tgt.SV_INVENTORY_SUB_CATEGORY_ID = src.SV_INVENTORY_SUB_CATEGORY_ID,
            tgt.CREATION_DATE_TIME = src.CREATION_DATE_TIME,
            tgt.ASPNET_USER_ID = src.ASPNET_USER_ID,
            tgt.CHECK_IN_TERMS = src.CHECK_IN_TERMS,
            tgt.CHECK_OUT_TERMS = src.CHECK_OUT_TERMS,
            tgt.ONLINE_PAYMENT_COMPLETION = src.ONLINE_PAYMENT_COMPLETION,
            tgt.DUE_DATE_DAYS = src.DUE_DATE_DAYS,
            tgt.DUE_DATE_SETTINGS_ID = src.DUE_DATE_SETTINGS_ID,
            tgt.CHARGE_CATEGORY = src.CHARGE_CATEGORY,
            tgt.INTRO_TEXT = src.INTRO_TEXT,
            tgt.REVENUE_GL_CODE = src.REVENUE_GL_CODE,
            tgt.AR_GL_CODE = src.AR_GL_CODE,
            tgt.SALES_TAX_GL_CODE = src.SALES_TAX_GL_CODE,
            tgt.DELETION_DATETIME = src.DELETION_DATETIME,
            tgt.DELETION_ASPNET_USER_ID = src.DELETION_ASPNET_USER_ID,
            tgt.RECORD_STATUS_ID = src.RECORD_STATUS_ID,
            tgt.DEFERRED_REVENUE_RECOGNITION = src.DEFERRED_REVENUE_RECOGNITION,
            tgt.DEFERRED_RECOGNITION_GL_CODE = src.DEFERRED_RECOGNITION_GL_CODE,
            tgt.TRACKING_CODE = src.TRACKING_CODE,
            tgt.XERO_RECOGNITION_ACCOUNT_ID = src.XERO_RECOGNITION_ACCOUNT_ID,
            tgt.REVENUE_XERO_ACCOUNT_ID = src.REVENUE_XERO_ACCOUNT_ID,
            tgt.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS = src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.SEASON_NAME, '~') != NVL(src.SEASON_NAME, '~')
            OR NVL(tgt.START_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.START_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.END_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.END_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.SEASONAL_CHARGE_METHOD_ID, -1) != NVL(src.SEASONAL_CHARGE_METHOD_ID, -1)
            OR NVL(tgt.PRICE_PER_FOOT, -1) != NVL(src.PRICE_PER_FOOT, -1)
            OR NVL(tgt.FLAT_RATE, -1) != NVL(src.FLAT_RATE, -1)
            OR NVL(tgt.TAXABLE, -1) != NVL(src.TAXABLE, -1)
            OR NVL(tgt.MARINA_LOCATION_ID, -1) != NVL(src.MARINA_LOCATION_ID, -1)
            OR NVL(tgt.ACTIVE, '~') != NVL(src.ACTIVE, '~')
            OR NVL(tgt.TAX, -999999) != NVL(src.TAX, -999999)
            OR NVL(tgt.RATE_DETAILS, -1) != NVL(src.RATE_DETAILS, -1)
            OR NVL(tgt.RATE_SHORT_NAME, -1) != NVL(src.RATE_SHORT_NAME, -1)
            OR NVL(tgt.ONLINE_PAYMENT_PLACEHOLDER, '~') != NVL(src.ONLINE_PAYMENT_PLACEHOLDER, '~')
            OR NVL(tgt.XERO_ITEM_CODE, '~') != NVL(src.XERO_ITEM_CODE, '~')
            OR NVL(tgt.XERO_ID, -1) != NVL(src.XERO_ID, -1)
            OR NVL(tgt.FIRST_TRACKING_CATEGORY, '~') != NVL(src.FIRST_TRACKING_CATEGORY, '~')
            OR NVL(tgt.SECOND_TRACKING_CATEGORY, '~') != NVL(src.SECOND_TRACKING_CATEGORY, '~')
            OR NVL(tgt.SEASONAL_INVOICING_METHOD_ID, -1) != NVL(src.SEASONAL_INVOICING_METHOD_ID, -1)
            OR NVL(tgt.SV_INVENTORY_CATEGORY_ID, -1) != NVL(src.SV_INVENTORY_CATEGORY_ID, -1)
            OR NVL(tgt.SV_INVENTORY_SUB_CATEGORY_ID, -1) != NVL(src.SV_INVENTORY_SUB_CATEGORY_ID, -1)
            OR NVL(tgt.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.ASPNET_USER_ID, -1) != NVL(src.ASPNET_USER_ID, -1)
            OR NVL(tgt.CHECK_IN_TERMS, '~') != NVL(src.CHECK_IN_TERMS, '~')
            OR NVL(tgt.CHECK_OUT_TERMS, '~') != NVL(src.CHECK_OUT_TERMS, '~')
            OR NVL(tgt.ONLINE_PAYMENT_COMPLETION, '~') != NVL(src.ONLINE_PAYMENT_COMPLETION, '~')
            OR NVL(tgt.DUE_DATE_DAYS, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DUE_DATE_DAYS, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DUE_DATE_SETTINGS_ID, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DUE_DATE_SETTINGS_ID, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CHARGE_CATEGORY, '~') != NVL(src.CHARGE_CATEGORY, '~')
            OR NVL(tgt.INTRO_TEXT, '~') != NVL(src.INTRO_TEXT, '~')
            OR NVL(tgt.REVENUE_GL_CODE, '~') != NVL(src.REVENUE_GL_CODE, '~')
            OR NVL(tgt.AR_GL_CODE, '~') != NVL(src.AR_GL_CODE, '~')
            OR NVL(tgt.SALES_TAX_GL_CODE, -1) != NVL(src.SALES_TAX_GL_CODE, -1)
            OR NVL(tgt.DELETION_DATETIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DELETION_DATETIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DELETION_ASPNET_USER_ID, -1) != NVL(src.DELETION_ASPNET_USER_ID, -1)
            OR NVL(tgt.RECORD_STATUS_ID, -1) != NVL(src.RECORD_STATUS_ID, -1)
            OR NVL(tgt.DEFERRED_REVENUE_RECOGNITION, '~') != NVL(src.DEFERRED_REVENUE_RECOGNITION, '~')
            OR NVL(tgt.DEFERRED_RECOGNITION_GL_CODE, '~') != NVL(src.DEFERRED_RECOGNITION_GL_CODE, '~')
            OR NVL(tgt.TRACKING_CODE, '~') != NVL(src.TRACKING_CODE, '~')
            OR NVL(tgt.XERO_RECOGNITION_ACCOUNT_ID, -1) != NVL(src.XERO_RECOGNITION_ACCOUNT_ID, -1)
            OR NVL(tgt.REVENUE_XERO_ACCOUNT_ID, -1) != NVL(src.REVENUE_XERO_ACCOUNT_ID, -1)
            OR NVL(tgt.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, -1) != NVL(src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, -1)
    WHEN NOT MATCHED THEN
        INSERT (
            ID, SEASON_NAME, START_DATE, END_DATE, SEASONAL_CHARGE_METHOD_ID, PRICE_PER_FOOT, FLAT_RATE, TAXABLE, MARINA_LOCATION_ID, ACTIVE, TAX, RATE_DETAILS, RATE_SHORT_NAME, ONLINE_PAYMENT_PLACEHOLDER, XERO_ITEM_CODE, XERO_ID, FIRST_TRACKING_CATEGORY, SECOND_TRACKING_CATEGORY, SEASONAL_INVOICING_METHOD_ID, SV_INVENTORY_CATEGORY_ID, SV_INVENTORY_SUB_CATEGORY_ID, CREATION_DATE_TIME, ASPNET_USER_ID, CHECK_IN_TERMS, CHECK_OUT_TERMS, ONLINE_PAYMENT_COMPLETION, DUE_DATE_DAYS, DUE_DATE_SETTINGS_ID, CHARGE_CATEGORY, INTRO_TEXT, REVENUE_GL_CODE, AR_GL_CODE, SALES_TAX_GL_CODE, DELETION_DATETIME, DELETION_ASPNET_USER_ID, RECORD_STATUS_ID, DEFERRED_REVENUE_RECOGNITION, DEFERRED_RECOGNITION_GL_CODE, TRACKING_CODE, XERO_RECOGNITION_ACCOUNT_ID, REVENUE_XERO_ACCOUNT_ID, ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.SEASON_NAME, src.START_DATE, src.END_DATE, src.SEASONAL_CHARGE_METHOD_ID, src.PRICE_PER_FOOT, src.FLAT_RATE, src.TAXABLE, src.MARINA_LOCATION_ID, src.ACTIVE, src.TAX, src.RATE_DETAILS, src.RATE_SHORT_NAME, src.ONLINE_PAYMENT_PLACEHOLDER, src.XERO_ITEM_CODE, src.XERO_ID, src.FIRST_TRACKING_CATEGORY, src.SECOND_TRACKING_CATEGORY, src.SEASONAL_INVOICING_METHOD_ID, src.SV_INVENTORY_CATEGORY_ID, src.SV_INVENTORY_SUB_CATEGORY_ID, src.CREATION_DATE_TIME, src.ASPNET_USER_ID, src.CHECK_IN_TERMS, src.CHECK_OUT_TERMS, src.ONLINE_PAYMENT_COMPLETION, src.DUE_DATE_DAYS, src.DUE_DATE_SETTINGS_ID, src.CHARGE_CATEGORY, src.INTRO_TEXT, src.REVENUE_GL_CODE, src.AR_GL_CODE, src.SALES_TAX_GL_CODE, src.DELETION_DATETIME, src.DELETION_ASPNET_USER_ID, src.RECORD_STATUS_ID, src.DEFERRED_REVENUE_RECOGNITION, src.DEFERRED_RECOGNITION_GL_CODE, src.TRACKING_CODE, src.XERO_RECOGNITION_ACCOUNT_ID, src.REVENUE_XERO_ACCOUNT_ID, src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_SEASONAL_PRICES: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_SEASONAL_PRICES: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_SEASONAL_PRICES;
/
