
-- ============================================================================
-- Merge STG_STELLAR_COUPONS to DW_STELLAR_COUPONS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_COUPONS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_COUPONS tgt
    USING STG_STELLAR_COUPONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.CODE = src.CODE,
            tgt.COUPON_NAME = src.COUPON_NAME,
            tgt.COUPON_TYPE = src.COUPON_TYPE,
            tgt.COUPON_AMOUNT = src.COUPON_AMOUNT,
            tgt.COUNT_ALLOWED = src.COUNT_ALLOWED,
            tgt.COUNT_ALLOWED_DAILY = src.COUNT_ALLOWED_DAILY,
            tgt.COUNT_USED = src.COUNT_USED,
            tgt.RENTAL_START = src.RENTAL_START,
            tgt.RENTAL_END = src.RENTAL_END,
            tgt.COUPON_START = src.COUPON_START,
            tgt.COUPON_END = src.COUPON_END,
            tgt.MIN_DEPARTURE_TIME = src.MIN_DEPARTURE_TIME,
            tgt.MAX_DEPARTURE_TIME = src.MAX_DEPARTURE_TIME,
            tgt.MIN_RETURN_TIME = src.MIN_RETURN_TIME,
            tgt.MAX_RETURN_TIME = src.MAX_RETURN_TIME,
            tgt.MIN_HOURS = src.MIN_HOURS,
            tgt.MAX_HOURS = src.MAX_HOURS,
            tgt.MIN_HOURS_BEFORE_DEPARTURE = src.MIN_HOURS_BEFORE_DEPARTURE,
            tgt.MAX_HOURS_BEFORE_DEPARTURE = src.MAX_HOURS_BEFORE_DEPARTURE,
            tgt.MAX_SAME_DAY_PER_CUSTOMER = src.MAX_SAME_DAY_PER_CUSTOMER,
            tgt.MAX_ACTIVE_PER_CUSTOMER = src.MAX_ACTIVE_PER_CUSTOMER,
            tgt.DISABLE_CONSECUTIVE_PER_CUSTOMER = src.DISABLE_CONSECUTIVE_PER_CUSTOMER,
            tgt.STATUS_COUPON = src.STATUS_COUPON,
            tgt.VALID_DAYS = src.VALID_DAYS,
            tgt.HOLIDAYS_ONLY_IF_VALID_DAY = src.HOLIDAYS_ONLY_IF_VALID_DAY,
            tgt.VALID_STYLES = src.VALID_STYLES,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.LOCATION_ID, -1) != NVL(src.LOCATION_ID, -1)
            OR NVL(tgt.CODE, '~') != NVL(src.CODE, '~')
            OR NVL(tgt.COUPON_NAME, '~') != NVL(src.COUPON_NAME, '~')
            OR NVL(tgt.COUPON_TYPE, '~') != NVL(src.COUPON_TYPE, '~')
            OR NVL(tgt.COUPON_AMOUNT, -1) != NVL(src.COUPON_AMOUNT, -1)
            OR NVL(tgt.COUNT_ALLOWED, -1) != NVL(src.COUNT_ALLOWED, -1)
            OR NVL(tgt.COUNT_ALLOWED_DAILY, -1) != NVL(src.COUNT_ALLOWED_DAILY, -1)
            OR NVL(tgt.COUNT_USED, -1) != NVL(src.COUNT_USED, -1)
            OR NVL(tgt.RENTAL_START, '~') != NVL(src.RENTAL_START, '~')
            OR NVL(tgt.RENTAL_END, '~') != NVL(src.RENTAL_END, '~')
            OR NVL(tgt.COUPON_START, '~') != NVL(src.COUPON_START, '~')
            OR NVL(tgt.COUPON_END, '~') != NVL(src.COUPON_END, '~')
            OR NVL(tgt.MIN_DEPARTURE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.MIN_DEPARTURE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.MAX_DEPARTURE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.MAX_DEPARTURE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.MIN_RETURN_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.MIN_RETURN_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.MAX_RETURN_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.MAX_RETURN_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.MIN_HOURS, -1) != NVL(src.MIN_HOURS, -1)
            OR NVL(tgt.MAX_HOURS, -1) != NVL(src.MAX_HOURS, -1)
            OR NVL(tgt.MIN_HOURS_BEFORE_DEPARTURE, -1) != NVL(src.MIN_HOURS_BEFORE_DEPARTURE, -1)
            OR NVL(tgt.MAX_HOURS_BEFORE_DEPARTURE, -1) != NVL(src.MAX_HOURS_BEFORE_DEPARTURE, -1)
            OR NVL(tgt.MAX_SAME_DAY_PER_CUSTOMER, '~') != NVL(src.MAX_SAME_DAY_PER_CUSTOMER, '~')
            OR NVL(tgt.MAX_ACTIVE_PER_CUSTOMER, '~') != NVL(src.MAX_ACTIVE_PER_CUSTOMER, '~')
            OR NVL(tgt.DISABLE_CONSECUTIVE_PER_CUSTOMER, '~') != NVL(src.DISABLE_CONSECUTIVE_PER_CUSTOMER, '~')
            OR NVL(tgt.STATUS_COUPON, '~') != NVL(src.STATUS_COUPON, '~')
            OR NVL(tgt.VALID_DAYS, -1) != NVL(src.VALID_DAYS, -1)
            OR NVL(tgt.HOLIDAYS_ONLY_IF_VALID_DAY, -1) != NVL(src.HOLIDAYS_ONLY_IF_VALID_DAY, -1)
            OR NVL(tgt.VALID_STYLES, '~') != NVL(src.VALID_STYLES, '~')
            OR NVL(tgt.CREATED_AT, '~') != NVL(src.CREATED_AT, '~')
            OR NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, CODE, COUPON_NAME, COUPON_TYPE, COUPON_AMOUNT, COUNT_ALLOWED, COUNT_ALLOWED_DAILY, COUNT_USED, RENTAL_START, RENTAL_END, COUPON_START, COUPON_END, MIN_DEPARTURE_TIME, MAX_DEPARTURE_TIME, MIN_RETURN_TIME, MAX_RETURN_TIME, MIN_HOURS, MAX_HOURS, MIN_HOURS_BEFORE_DEPARTURE, MAX_HOURS_BEFORE_DEPARTURE, MAX_SAME_DAY_PER_CUSTOMER, MAX_ACTIVE_PER_CUSTOMER, DISABLE_CONSECUTIVE_PER_CUSTOMER, STATUS_COUPON, VALID_DAYS, HOLIDAYS_ONLY_IF_VALID_DAY, VALID_STYLES, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.CODE, src.COUPON_NAME, src.COUPON_TYPE, src.COUPON_AMOUNT, src.COUNT_ALLOWED, src.COUNT_ALLOWED_DAILY, src.COUNT_USED, src.RENTAL_START, src.RENTAL_END, src.COUPON_START, src.COUPON_END, src.MIN_DEPARTURE_TIME, src.MAX_DEPARTURE_TIME, src.MIN_RETURN_TIME, src.MAX_RETURN_TIME, src.MIN_HOURS, src.MAX_HOURS, src.MIN_HOURS_BEFORE_DEPARTURE, src.MAX_HOURS_BEFORE_DEPARTURE, src.MAX_SAME_DAY_PER_CUSTOMER, src.MAX_ACTIVE_PER_CUSTOMER, src.DISABLE_CONSECUTIVE_PER_CUSTOMER, src.STATUS_COUPON, src.VALID_DAYS, src.HOLIDAYS_ONLY_IF_VALID_DAY, src.VALID_STYLES, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_COUPONS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_COUPONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_COUPONS;
/
