
-- ============================================================================
-- Merge STG_STELLAR_SEASONS to DW_STELLAR_SEASONS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_SEASONS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_SEASONS tgt
    USING STG_STELLAR_SEASONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.SEASON_NAME = src.SEASON_NAME,
            tgt.SEASON_START = src.SEASON_START,
            tgt.SEASON_END = src.SEASON_END,
            tgt.STATUS_SEASON = src.STATUS_SEASON,
            tgt.WEEK_DAY_MIN_START_TIME = src.WEEK_DAY_MIN_START_TIME,
            tgt.WEEK_DAY_MAX_START_TIME = src.WEEK_DAY_MAX_START_TIME,
            tgt.WEEK_DAY_MIN_END_TIME = src.WEEK_DAY_MIN_END_TIME,
            tgt.WEEK_DAY_MAX_END_TIME = src.WEEK_DAY_MAX_END_TIME,
            tgt.WEEK_END_MIN_START_TIME = src.WEEK_END_MIN_START_TIME,
            tgt.WEEK_END_MAX_START_TIME = src.WEEK_END_MAX_START_TIME,
            tgt.WEEK_END_MIN_END_TIME = src.WEEK_END_MIN_END_TIME,
            tgt.WEEK_END_MAX_END_TIME = src.WEEK_END_MAX_END_TIME,
            tgt.HOLIDAY_MIN_START_TIME = src.HOLIDAY_MIN_START_TIME,
            tgt.HOLIDAY_MAX_START_TIME = src.HOLIDAY_MAX_START_TIME,
            tgt.HOLIDAY_MIN_END_TIME = src.HOLIDAY_MIN_END_TIME,
            tgt.HOLIDAY_MAX_END_TIME = src.HOLIDAY_MAX_END_TIME,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.LOCATION_ID, -1) != NVL(src.LOCATION_ID, -1)
            OR NVL(tgt.SEASON_NAME, '~') != NVL(src.SEASON_NAME, '~')
            OR NVL(tgt.SEASON_START, '~') != NVL(src.SEASON_START, '~')
            OR NVL(tgt.SEASON_END, '~') != NVL(src.SEASON_END, '~')
            OR NVL(tgt.STATUS_SEASON, '~') != NVL(src.STATUS_SEASON, '~')
            OR NVL(tgt.WEEK_DAY_MIN_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_DAY_MIN_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_DAY_MAX_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_DAY_MAX_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_DAY_MIN_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_DAY_MIN_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_DAY_MAX_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_DAY_MAX_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_END_MIN_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_END_MIN_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_END_MAX_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_END_MAX_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_END_MIN_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_END_MIN_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.WEEK_END_MAX_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.WEEK_END_MAX_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.HOLIDAY_MIN_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.HOLIDAY_MIN_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.HOLIDAY_MAX_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.HOLIDAY_MAX_START_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.HOLIDAY_MIN_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.HOLIDAY_MIN_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.HOLIDAY_MAX_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.HOLIDAY_MAX_END_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CREATED_AT, '~') != NVL(src.CREATED_AT, '~')
            OR NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, SEASON_NAME, SEASON_START, SEASON_END, STATUS_SEASON, WEEK_DAY_MIN_START_TIME, WEEK_DAY_MAX_START_TIME, WEEK_DAY_MIN_END_TIME, WEEK_DAY_MAX_END_TIME, WEEK_END_MIN_START_TIME, WEEK_END_MAX_START_TIME, WEEK_END_MIN_END_TIME, WEEK_END_MAX_END_TIME, HOLIDAY_MIN_START_TIME, HOLIDAY_MAX_START_TIME, HOLIDAY_MIN_END_TIME, HOLIDAY_MAX_END_TIME, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.SEASON_NAME, src.SEASON_START, src.SEASON_END, src.STATUS_SEASON, src.WEEK_DAY_MIN_START_TIME, src.WEEK_DAY_MAX_START_TIME, src.WEEK_DAY_MIN_END_TIME, src.WEEK_DAY_MAX_END_TIME, src.WEEK_END_MIN_START_TIME, src.WEEK_END_MAX_START_TIME, src.WEEK_END_MIN_END_TIME, src.WEEK_END_MAX_END_TIME, src.HOLIDAY_MIN_START_TIME, src.HOLIDAY_MAX_START_TIME, src.HOLIDAY_MIN_END_TIME, src.HOLIDAY_MAX_END_TIME, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_SEASONS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_SEASONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_SEASONS;
/
