
-- ============================================================================
-- Merge STG_MOLO_ITEM_MASTERS to DW_MOLO_ITEM_MASTERS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_ITEM_MASTERS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_ITEM_MASTERS tgt
    USING STG_MOLO_ITEM_MASTERS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.NAME = src.NAME,
            tgt.AMOUNT = src.AMOUNT,
            tgt.ITEM_CHARGE_METHOD_ID = src.ITEM_CHARGE_METHOD_ID,
            tgt.TAXABLE = src.TAXABLE,
            tgt.AVAILABLE_AS_ADD_ON = src.AVAILABLE_AS_ADD_ON,
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.PRICE = src.PRICE,
            tgt.TAX = src.TAX,
            tgt.SINGLE = src.SINGLE,
            tgt.CHARGE_CATEGORY = src.CHARGE_CATEGORY,
            tgt.AMOUNT_IS_DECIMAL = src.AMOUNT_IS_DECIMAL,
            tgt.NUMBER_OF_DECIMALS = src.NUMBER_OF_DECIMALS,
            tgt.ITEM_SHORT_NAME = src.ITEM_SHORT_NAME,
            tgt.ITEM_CODE = src.ITEM_CODE,
            tgt.TRACKED_INVENTORY = src.TRACKED_INVENTORY,
            tgt.QUANTITY_ON_HAND = src.QUANTITY_ON_HAND,
            tgt.PURCHASE_PRICE = src.PURCHASE_PRICE,
            tgt.FIRST_TRACKING_CATEGORY = src.FIRST_TRACKING_CATEGORY,
            tgt.SECOND_TRACKING_CATEGORY = src.SECOND_TRACKING_CATEGORY,
            tgt.XERO_ID = src.XERO_ID,
            tgt.SALE_FREQUENCY = src.SALE_FREQUENCY,
            tgt.LOW_QUANTITY_WARNING = src.LOW_QUANTITY_WARNING,
            tgt.MARINA_LOCATION1_ID = src.MARINA_LOCATION1_ID,
            tgt.MARINA_LOCATION2_ID = src.MARINA_LOCATION2_ID,
            tgt.PEDESTAL_ID = src.PEDESTAL_ID,
            tgt.PEDESTAL1_ID = src.PEDESTAL1_ID,
            tgt.QB_ITEM_ID = src.QB_ITEM_ID,
            tgt.XERO_ITEM_ID = src.XERO_ITEM_ID,
            tgt.BARCODE = src.BARCODE,
            tgt.DISTRIBUTE_TO_OWNERS = src.DISTRIBUTE_TO_OWNERS,
            tgt.FUEL_CLOUD_PRODUCT_ID = src.FUEL_CLOUD_PRODUCT_ID,
            tgt.HASH_ID = src.HASH_ID,
            tgt.REQUIRES_AGE_VERIFICATION = src.REQUIRES_AGE_VERIFICATION,
            tgt.MINIMUM_AGE = src.MINIMUM_AGE,
            tgt.CREATION_DATE_TIME = src.CREATION_DATE_TIME,
            tgt.CREATION_ASPNET_USER_ID = src.CREATION_ASPNET_USER_ID,
            tgt.RECORD_STATUS_ID = src.RECORD_STATUS_ID,
            tgt.UPDATE_HASH = src.UPDATE_HASH,
            tgt.SUBLET_ITEM = src.SUBLET_ITEM,
            tgt.INTERNAL_REVENUE_XERO_ACCOUNT_ID = src.INTERNAL_REVENUE_XERO_ACCOUNT_ID,
            tgt.INTERNAL_COGS_XERO_ACCOUNT_ID = src.INTERNAL_COGS_XERO_ACCOUNT_ID,
            tgt.WIP_XERO_ACCOUNT_ID = src.WIP_XERO_ACCOUNT_ID,
            tgt.INVENTORY_REVALUATION_ID = src.INVENTORY_REVALUATION_ID,
            tgt.MARINA_LOCATION6_ID = src.MARINA_LOCATION6_ID,
            tgt.FINALE_PRODUCT_URL = src.FINALE_PRODUCT_URL,
            tgt.REVENUE_GL_CODE = src.REVENUE_GL_CODE,
            tgt.COGS_GL_CODE = src.COGS_GL_CODE,
            tgt.INVENTORY_GL_CODE = src.INVENTORY_GL_CODE,
            tgt.AR_GL_CODE = src.AR_GL_CODE,
            tgt.SALES_TAX_GL_CODE = src.SALES_TAX_GL_CODE,
            tgt.ONLY_USE_LAST2_AVERAGE = src.ONLY_USE_LAST2_AVERAGE,
            tgt.DEFERRED_REVENUE_RECOGNITION = src.DEFERRED_REVENUE_RECOGNITION,
            tgt.DEFERRED_RECOGNITION_GL_CODE = src.DEFERRED_RECOGNITION_GL_CODE,
            tgt.TRACKING_CODE = src.TRACKING_CODE,
            tgt.ADD_DESCRIPTION_TO_INVOICE_NOTE = src.ADD_DESCRIPTION_TO_INVOICE_NOTE,
            tgt.MARINA_LOCATION7_ID = src.MARINA_LOCATION7_ID,
            tgt.IGNORE_INVENTORY_QOH = src.IGNORE_INVENTORY_QOH,
            tgt.QOH_COMMITTED = src.QOH_COMMITTED,
            tgt.QOH_ON_ORDER = src.QOH_ON_ORDER,
            tgt.ALLOW_TOTAL_PRICE_ENTRY = src.ALLOW_TOTAL_PRICE_ENTRY,
            tgt.MARINA_LOCATION9_ID = src.MARINA_LOCATION9_ID,
            tgt.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS = src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            tgt.ORDER_COLUMN = src.ORDER_COLUMN,
            tgt.ENABLE_NEGATIVE_INVENTORY = src.ENABLE_NEGATIVE_INVENTORY,
            tgt.WIP = src.WIP,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.NAME, '~') != NVL(src.NAME, '~')
            OR NVL(tgt.AMOUNT, -999999) != NVL(src.AMOUNT, -999999)
            OR NVL(tgt.ITEM_CHARGE_METHOD_ID, -1) != NVL(src.ITEM_CHARGE_METHOD_ID, -1)
            OR NVL(tgt.TAXABLE, -1) != NVL(src.TAXABLE, -1)
            OR NVL(tgt.AVAILABLE_AS_ADD_ON, '~') != NVL(src.AVAILABLE_AS_ADD_ON, '~')
            OR NVL(tgt.MARINA_LOCATION_ID, -1) != NVL(src.MARINA_LOCATION_ID, -1)
            OR NVL(tgt.PRICE, -999999) != NVL(src.PRICE, -999999)
            OR NVL(tgt.TAX, -999999) != NVL(src.TAX, -999999)
            OR NVL(tgt.SINGLE, '~') != NVL(src.SINGLE, '~')
            OR NVL(tgt.CHARGE_CATEGORY, '~') != NVL(src.CHARGE_CATEGORY, '~')
            OR NVL(tgt.AMOUNT_IS_DECIMAL, -999999) != NVL(src.AMOUNT_IS_DECIMAL, -999999)
            OR NVL(tgt.NUMBER_OF_DECIMALS, -999999) != NVL(src.NUMBER_OF_DECIMALS, -999999)
            OR NVL(tgt.ITEM_SHORT_NAME, '~') != NVL(src.ITEM_SHORT_NAME, '~')
            OR NVL(tgt.ITEM_CODE, '~') != NVL(src.ITEM_CODE, '~')
            OR NVL(tgt.TRACKED_INVENTORY, '~') != NVL(src.TRACKED_INVENTORY, '~')
            OR NVL(tgt.QUANTITY_ON_HAND, -1) != NVL(src.QUANTITY_ON_HAND, -1)
            OR NVL(tgt.PURCHASE_PRICE, -1) != NVL(src.PURCHASE_PRICE, -1)
            OR NVL(tgt.FIRST_TRACKING_CATEGORY, '~') != NVL(src.FIRST_TRACKING_CATEGORY, '~')
            OR NVL(tgt.SECOND_TRACKING_CATEGORY, '~') != NVL(src.SECOND_TRACKING_CATEGORY, '~')
            OR NVL(tgt.XERO_ID, -1) != NVL(src.XERO_ID, -1)
            OR NVL(tgt.SALE_FREQUENCY, '~') != NVL(src.SALE_FREQUENCY, '~')
            OR NVL(tgt.LOW_QUANTITY_WARNING, -1) != NVL(src.LOW_QUANTITY_WARNING, -1)
            OR NVL(tgt.MARINA_LOCATION1_ID, -1) != NVL(src.MARINA_LOCATION1_ID, -1)
            OR NVL(tgt.MARINA_LOCATION2_ID, -1) != NVL(src.MARINA_LOCATION2_ID, -1)
            OR NVL(tgt.PEDESTAL_ID, -1) != NVL(src.PEDESTAL_ID, -1)
            OR NVL(tgt.PEDESTAL1_ID, -1) != NVL(src.PEDESTAL1_ID, -1)
            OR NVL(tgt.QB_ITEM_ID, -1) != NVL(src.QB_ITEM_ID, -1)
            OR NVL(tgt.XERO_ITEM_ID, -1) != NVL(src.XERO_ITEM_ID, -1)
            OR NVL(tgt.BARCODE, '~') != NVL(src.BARCODE, '~')
            OR NVL(tgt.DISTRIBUTE_TO_OWNERS, '~') != NVL(src.DISTRIBUTE_TO_OWNERS, '~')
            OR NVL(tgt.FUEL_CLOUD_PRODUCT_ID, -1) != NVL(src.FUEL_CLOUD_PRODUCT_ID, -1)
            OR NVL(tgt.HASH_ID, -1) != NVL(src.HASH_ID, -1)
            OR NVL(tgt.REQUIRES_AGE_VERIFICATION, '~') != NVL(src.REQUIRES_AGE_VERIFICATION, '~')
            OR NVL(tgt.MINIMUM_AGE, '~') != NVL(src.MINIMUM_AGE, '~')
            OR NVL(tgt.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CREATION_ASPNET_USER_ID, -1) != NVL(src.CREATION_ASPNET_USER_ID, -1)
            OR NVL(tgt.RECORD_STATUS_ID, -1) != NVL(src.RECORD_STATUS_ID, -1)
            OR NVL(tgt.UPDATE_HASH, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATE_HASH, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.SUBLET_ITEM, '~') != NVL(src.SUBLET_ITEM, '~')
            OR NVL(tgt.INTERNAL_REVENUE_XERO_ACCOUNT_ID, -1) != NVL(src.INTERNAL_REVENUE_XERO_ACCOUNT_ID, -1)
            OR NVL(tgt.INTERNAL_COGS_XERO_ACCOUNT_ID, -1) != NVL(src.INTERNAL_COGS_XERO_ACCOUNT_ID, -1)
            OR NVL(tgt.WIP_XERO_ACCOUNT_ID, -1) != NVL(src.WIP_XERO_ACCOUNT_ID, -1)
            OR NVL(tgt.INVENTORY_REVALUATION_ID, -1) != NVL(src.INVENTORY_REVALUATION_ID, -1)
            OR NVL(tgt.MARINA_LOCATION6_ID, -1) != NVL(src.MARINA_LOCATION6_ID, -1)
            OR NVL(tgt.FINALE_PRODUCT_URL, '~') != NVL(src.FINALE_PRODUCT_URL, '~')
            OR NVL(tgt.REVENUE_GL_CODE, '~') != NVL(src.REVENUE_GL_CODE, '~')
            OR NVL(tgt.COGS_GL_CODE, '~') != NVL(src.COGS_GL_CODE, '~')
            OR NVL(tgt.INVENTORY_GL_CODE, '~') != NVL(src.INVENTORY_GL_CODE, '~')
            OR NVL(tgt.AR_GL_CODE, '~') != NVL(src.AR_GL_CODE, '~')
            OR NVL(tgt.SALES_TAX_GL_CODE, -1) != NVL(src.SALES_TAX_GL_CODE, -1)
            OR NVL(tgt.ONLY_USE_LAST2_AVERAGE, '~') != NVL(src.ONLY_USE_LAST2_AVERAGE, '~')
            OR NVL(tgt.DEFERRED_REVENUE_RECOGNITION, '~') != NVL(src.DEFERRED_REVENUE_RECOGNITION, '~')
            OR NVL(tgt.DEFERRED_RECOGNITION_GL_CODE, '~') != NVL(src.DEFERRED_RECOGNITION_GL_CODE, '~')
            OR NVL(tgt.TRACKING_CODE, '~') != NVL(src.TRACKING_CODE, '~')
            OR NVL(tgt.ADD_DESCRIPTION_TO_INVOICE_NOTE, '~') != NVL(src.ADD_DESCRIPTION_TO_INVOICE_NOTE, '~')
            OR NVL(tgt.MARINA_LOCATION7_ID, -1) != NVL(src.MARINA_LOCATION7_ID, -1)
            OR NVL(tgt.IGNORE_INVENTORY_QOH, '~') != NVL(src.IGNORE_INVENTORY_QOH, '~')
            OR NVL(tgt.QOH_COMMITTED, '~') != NVL(src.QOH_COMMITTED, '~')
            OR NVL(tgt.QOH_ON_ORDER, '~') != NVL(src.QOH_ON_ORDER, '~')
            OR NVL(tgt.ALLOW_TOTAL_PRICE_ENTRY, -1) != NVL(src.ALLOW_TOTAL_PRICE_ENTRY, -1)
            OR NVL(tgt.MARINA_LOCATION9_ID, -1) != NVL(src.MARINA_LOCATION9_ID, -1)
            OR NVL(tgt.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, -1) != NVL(src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, -1)
            OR NVL(tgt.ORDER_COLUMN, '~') != NVL(src.ORDER_COLUMN, '~')
            OR NVL(tgt.ENABLE_NEGATIVE_INVENTORY, '~') != NVL(src.ENABLE_NEGATIVE_INVENTORY, '~')
            OR NVL(tgt.WIP, '~') != NVL(src.WIP, '~')
    WHEN NOT MATCHED THEN
        INSERT (
            ID, NAME, AMOUNT, ITEM_CHARGE_METHOD_ID, TAXABLE, AVAILABLE_AS_ADD_ON, MARINA_LOCATION_ID, PRICE, TAX, SINGLE, CHARGE_CATEGORY, AMOUNT_IS_DECIMAL, NUMBER_OF_DECIMALS, ITEM_SHORT_NAME, ITEM_CODE, TRACKED_INVENTORY, QUANTITY_ON_HAND, PURCHASE_PRICE, FIRST_TRACKING_CATEGORY, SECOND_TRACKING_CATEGORY, XERO_ID, SALE_FREQUENCY, LOW_QUANTITY_WARNING, MARINA_LOCATION1_ID, MARINA_LOCATION2_ID, PEDESTAL_ID, PEDESTAL1_ID, QB_ITEM_ID, XERO_ITEM_ID, BARCODE, DISTRIBUTE_TO_OWNERS, FUEL_CLOUD_PRODUCT_ID, HASH_ID, REQUIRES_AGE_VERIFICATION, MINIMUM_AGE, CREATION_DATE_TIME, CREATION_ASPNET_USER_ID, RECORD_STATUS_ID, UPDATE_HASH, SUBLET_ITEM, INTERNAL_REVENUE_XERO_ACCOUNT_ID, INTERNAL_COGS_XERO_ACCOUNT_ID, WIP_XERO_ACCOUNT_ID, INVENTORY_REVALUATION_ID, MARINA_LOCATION6_ID, FINALE_PRODUCT_URL, REVENUE_GL_CODE, COGS_GL_CODE, INVENTORY_GL_CODE, AR_GL_CODE, SALES_TAX_GL_CODE, ONLY_USE_LAST2_AVERAGE, DEFERRED_REVENUE_RECOGNITION, DEFERRED_RECOGNITION_GL_CODE, TRACKING_CODE, ADD_DESCRIPTION_TO_INVOICE_NOTE, MARINA_LOCATION7_ID, IGNORE_INVENTORY_QOH, QOH_COMMITTED, QOH_ON_ORDER, ALLOW_TOTAL_PRICE_ENTRY, MARINA_LOCATION9_ID, ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, ORDER_COLUMN, ENABLE_NEGATIVE_INVENTORY, WIP,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.NAME, src.AMOUNT, src.ITEM_CHARGE_METHOD_ID, src.TAXABLE, src.AVAILABLE_AS_ADD_ON, src.MARINA_LOCATION_ID, src.PRICE, src.TAX, src.SINGLE, src.CHARGE_CATEGORY, src.AMOUNT_IS_DECIMAL, src.NUMBER_OF_DECIMALS, src.ITEM_SHORT_NAME, src.ITEM_CODE, src.TRACKED_INVENTORY, src.QUANTITY_ON_HAND, src.PURCHASE_PRICE, src.FIRST_TRACKING_CATEGORY, src.SECOND_TRACKING_CATEGORY, src.XERO_ID, src.SALE_FREQUENCY, src.LOW_QUANTITY_WARNING, src.MARINA_LOCATION1_ID, src.MARINA_LOCATION2_ID, src.PEDESTAL_ID, src.PEDESTAL1_ID, src.QB_ITEM_ID, src.XERO_ITEM_ID, src.BARCODE, src.DISTRIBUTE_TO_OWNERS, src.FUEL_CLOUD_PRODUCT_ID, src.HASH_ID, src.REQUIRES_AGE_VERIFICATION, src.MINIMUM_AGE, src.CREATION_DATE_TIME, src.CREATION_ASPNET_USER_ID, src.RECORD_STATUS_ID, src.UPDATE_HASH, src.SUBLET_ITEM, src.INTERNAL_REVENUE_XERO_ACCOUNT_ID, src.INTERNAL_COGS_XERO_ACCOUNT_ID, src.WIP_XERO_ACCOUNT_ID, src.INVENTORY_REVALUATION_ID, src.MARINA_LOCATION6_ID, src.FINALE_PRODUCT_URL, src.REVENUE_GL_CODE, src.COGS_GL_CODE, src.INVENTORY_GL_CODE, src.AR_GL_CODE, src.SALES_TAX_GL_CODE, src.ONLY_USE_LAST2_AVERAGE, src.DEFERRED_REVENUE_RECOGNITION, src.DEFERRED_RECOGNITION_GL_CODE, src.TRACKING_CODE, src.ADD_DESCRIPTION_TO_INVOICE_NOTE, src.MARINA_LOCATION7_ID, src.IGNORE_INVENTORY_QOH, src.QOH_COMMITTED, src.QOH_ON_ORDER, src.ALLOW_TOTAL_PRICE_ENTRY, src.MARINA_LOCATION9_ID, src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, src.ORDER_COLUMN, src.ENABLE_NEGATIVE_INVENTORY, src.WIP,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_ITEM_MASTERS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_ITEM_MASTERS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_ITEM_MASTERS;
/
