
-- ============================================================================
-- Merge STG_MOLO_INVOICE_ITEMS to DW_MOLO_INVOICE_ITEMS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_INVOICE_ITEMS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_INVOICE_ITEMS tgt
    USING STG_MOLO_INVOICE_ITEMS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.PREFIX = src.PREFIX,
            tgt.QUANTITY = src.QUANTITY,
            tgt.TITLE = src.TITLE,
            tgt.TYPE_FIELD = src.TYPE_FIELD,
            tgt.VALUE_FIELD = src.VALUE_FIELD,
            tgt.DISCOUNT = src.DISCOUNT,
            tgt.DISCOUNT_TYPE = src.DISCOUNT_TYPE,
            tgt.TAXABLE = src.TAXABLE,
            tgt.TAX = src.TAX,
            tgt.MISC = src.MISC,
            tgt.DISCOUNT_TOTAL = src.DISCOUNT_TOTAL,
            tgt.PRICE_SUFFIX = src.PRICE_SUFFIX,
            tgt.SUB_TOTAL = src.SUB_TOTAL,
            tgt.SUBTOTAL_WO_DISCOUNT = src.SUBTOTAL_WO_DISCOUNT,
            tgt.TAX_TOTAL = src.TAX_TOTAL,
            tgt.TOTAL = src.TOTAL,
            tgt.INVOICE_ID = src.INVOICE_ID,
            tgt.CHARGE_GROUP = src.CHARGE_GROUP,
            tgt.PAYMENT_ACCOUNT = src.PAYMENT_ACCOUNT,
            tgt.PRICE_STR = src.PRICE_STR,
            tgt.IS_VOID = src.IS_VOID,
            tgt.DATE_FIELD = src.DATE_FIELD,
            tgt.TEXT_AUX = src.TEXT_AUX,
            tgt.TEXT_AUX2 = src.TEXT_AUX2,
            tgt.DISCOUNT_DATE_TIME = src.DISCOUNT_DATE_TIME,
            tgt.DISCOUNT_USER_ID = src.DISCOUNT_USER_ID,
            tgt.NOTES = src.NOTES,
            tgt.PR_TYPE = src.PR_TYPE,
            tgt.STATUS_FIELD = src.STATUS_FIELD,
            tgt.DELETION_USER_ID = src.DELETION_USER_ID,
            tgt.DELETION_DATE_TIME = src.DELETION_DATE_TIME,
            tgt.OVERPAYMENT_ID = src.OVERPAYMENT_ID,
            tgt.VOID_USER = src.VOID_USER,
            tgt.VOID_DATE_TIME = src.VOID_DATE_TIME,
            tgt.MISC2 = src.MISC2,
            tgt.PREPAYMENT_ID = src.PREPAYMENT_ID,
            tgt.CREDIT_INVOICE_ID = src.CREDIT_INVOICE_ID,
            tgt.ALLOCATION_TYPE = src.ALLOCATION_TYPE,
            tgt.RESERVATION_ID = src.RESERVATION_ID,
            tgt.ITEM_MASTER_ID = src.ITEM_MASTER_ID,
            tgt.ASPNET_USER_ID = src.ASPNET_USER_ID,
            tgt.INVOICE_ITEM_TYPE_ID = src.INVOICE_ITEM_TYPE_ID,
            tgt.SEASONAL_PRICE_ID = src.SEASONAL_PRICE_ID,
            tgt.TRANSIENT_PRICE_ID = src.TRANSIENT_PRICE_ID,
            tgt.SV_JOB_ID = src.SV_JOB_ID,
            tgt.ORIGINAL_CREDIT_ITEM = src.ORIGINAL_CREDIT_ITEM,
            tgt.TAX_EXEMPT = src.TAX_EXEMPT,
            tgt.LAST_MODIFIED_DATE_TIME = src.LAST_MODIFIED_DATE_TIME,
            tgt.LAST_MODIFIED_ASPNET_USER = src.LAST_MODIFIED_ASPNET_USER,
            tgt.DELETION_REASON = src.DELETION_REASON,
            tgt.VOID_REASON = src.VOID_REASON,
            tgt.START_DATE_TIME = src.START_DATE_TIME,
            tgt.END_DATE_TIME = src.END_DATE_TIME,
            tgt.CREATION_PARTNER_ID = src.CREATION_PARTNER_ID,
            tgt.DELETE_PARTNER_ID = src.DELETE_PARTNER_ID,
            tgt.VOID_PARTNER_ID = src.VOID_PARTNER_ID,
            tgt.ORIGINAL_PRICE = src.ORIGINAL_PRICE,
            tgt.OVERRIDE_XERO_TAX_RATE = src.OVERRIDE_XERO_TAX_RATE,
            tgt.OVERRIDE_XERO_SALES_ACCOUNT = src.OVERRIDE_XERO_SALES_ACCOUNT,
            tgt.ORIGINAL_RESERVATION_PRICE = src.ORIGINAL_RESERVATION_PRICE,
            tgt.NUMBER_OF_DECIMALS = src.NUMBER_OF_DECIMALS,
            tgt.STRIPE_TRANSACTION_DATA_ID = src.STRIPE_TRANSACTION_DATA_ID,
            tgt.VALUE_ALTERNATIVE = src.VALUE_ALTERNATIVE,
            tgt.STRIPE_TERMINAL_ID = src.STRIPE_TERMINAL_ID,
            tgt.STRIPE_APPLICATION_NAME = src.STRIPE_APPLICATION_NAME,
            tgt.STRIPE_AID = src.STRIPE_AID,
            tgt.ENTERED_AMOUNT = src.ENTERED_AMOUNT,
            tgt.EXCHANGE_RATE = src.EXCHANGE_RATE,
            tgt.CURRENCIES_ID = src.CURRENCIES_ID,
            tgt.SV_CHARGE_INSTANCE_ID = src.SV_CHARGE_INSTANCE_ID,
            tgt.SV_LABOR_INSTANCE_ID = src.SV_LABOR_INSTANCE_ID,
            tgt.SV_PART_INSTANCE_ID = src.SV_PART_INSTANCE_ID,
            tgt.REVENUE_GL_CODE = src.REVENUE_GL_CODE,
            tgt.AR_GL_CODE = src.AR_GL_CODE,
            tgt.PAYMENT_GL_CODE = src.PAYMENT_GL_CODE,
            tgt.COGS_GL_CODE = src.COGS_GL_CODE,
            tgt.INVENTORY_GL_CODE = src.INVENTORY_GL_CODE,
            tgt.SALES_TAX_GL_CODE = src.SALES_TAX_GL_CODE,
            tgt.PREPAYMENT_GL_CODE = src.PREPAYMENT_GL_CODE,
            tgt.ACCOUNT_TYPE = src.ACCOUNT_TYPE,
            tgt.APPLICATION_CRYPTOGRAM = src.APPLICATION_CRYPTOGRAM,
            tgt.AUTHORIZATION_CODE = src.AUTHORIZATION_CODE,
            tgt.AUTHORIZATION_RESPONSE_CODE = src.AUTHORIZATION_RESPONSE_CODE,
            tgt.CARDHOLDER_VERIFICATION_METHOD = src.CARDHOLDER_VERIFICATION_METHOD,
            tgt.TERMINAL_VERIFICATION_RESULTS = src.TERMINAL_VERIFICATION_RESULTS,
            tgt.TRANSACTION_STATUS_INFORMATION = src.TRANSACTION_STATUS_INFORMATION,
            tgt.TRACKING_CODE = src.TRACKING_CODE,
            tgt.DISCOUNT_GL_CODE = src.DISCOUNT_GL_CODE,
            tgt.OVERRIDE_TRACKING_CATEGORY1 = src.OVERRIDE_TRACKING_CATEGORY1,
            tgt.OVERRIDE_TRACKING_CATEGORY2 = src.OVERRIDE_TRACKING_CATEGORY2,
            tgt.QUICKBOOKS_PAYMENT_ID = src.QUICKBOOKS_PAYMENT_ID,
            tgt.ALLOW_TOTAL_PRICE_ENTRY = src.ALLOW_TOTAL_PRICE_ENTRY,
            tgt.ADDED_AUTOMATICALLY = src.ADDED_AUTOMATICALLY,
            tgt.ALLOCATION_PERFORMED_DATE = src.ALLOCATION_PERFORMED_DATE,
            tgt.CREATED_DATE = src.CREATED_DATE,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.PREFIX, '~') != NVL(src.PREFIX, '~')
            OR NVL(tgt.QUANTITY, -1) != NVL(src.QUANTITY, -1)
            OR NVL(tgt.TITLE, '~') != NVL(src.TITLE, '~')
            OR NVL(tgt.TYPE_FIELD, '~') != NVL(src.TYPE_FIELD, '~')
            OR NVL(tgt.VALUE_FIELD, '~') != NVL(src.VALUE_FIELD, '~')
            OR NVL(tgt.DISCOUNT, -1) != NVL(src.DISCOUNT, -1)
            OR NVL(tgt.DISCOUNT_TYPE, -1) != NVL(src.DISCOUNT_TYPE, -1)
            OR NVL(tgt.TAXABLE, -1) != NVL(src.TAXABLE, -1)
            OR NVL(tgt.TAX, -999999) != NVL(src.TAX, -999999)
            OR NVL(tgt.MISC, '~') != NVL(src.MISC, '~')
            OR NVL(tgt.DISCOUNT_TOTAL, -1) != NVL(src.DISCOUNT_TOTAL, -1)
            OR NVL(tgt.PRICE_SUFFIX, -1) != NVL(src.PRICE_SUFFIX, -1)
            OR NVL(tgt.SUB_TOTAL, '~') != NVL(src.SUB_TOTAL, '~')
            OR NVL(tgt.SUBTOTAL_WO_DISCOUNT, -1) != NVL(src.SUBTOTAL_WO_DISCOUNT, -1)
            OR NVL(tgt.TAX_TOTAL, -1) != NVL(src.TAX_TOTAL, -1)
            OR NVL(tgt.TOTAL, '~') != NVL(src.TOTAL, '~')
            OR NVL(tgt.INVOICE_ID, -1) != NVL(src.INVOICE_ID, -1)
            OR NVL(tgt.CHARGE_GROUP, '~') != NVL(src.CHARGE_GROUP, '~')
            OR NVL(tgt.PAYMENT_ACCOUNT, -1) != NVL(src.PAYMENT_ACCOUNT, -1)
            OR NVL(tgt.PRICE_STR, -1) != NVL(src.PRICE_STR, -1)
            OR NVL(tgt.IS_VOID, '~') != NVL(src.IS_VOID, '~')
            OR NVL(tgt.DATE_FIELD, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DATE_FIELD, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.TEXT_AUX, '~') != NVL(src.TEXT_AUX, '~')
            OR NVL(tgt.TEXT_AUX2, '~') != NVL(src.TEXT_AUX2, '~')
            OR NVL(tgt.DISCOUNT_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DISCOUNT_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DISCOUNT_USER_ID, -1) != NVL(src.DISCOUNT_USER_ID, -1)
            OR NVL(tgt.NOTES, '~') != NVL(src.NOTES, '~')
            OR NVL(tgt.PR_TYPE, '~') != NVL(src.PR_TYPE, '~')
            OR NVL(tgt.STATUS_FIELD, '~') != NVL(src.STATUS_FIELD, '~')
            OR NVL(tgt.DELETION_USER_ID, -1) != NVL(src.DELETION_USER_ID, -1)
            OR NVL(tgt.DELETION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DELETION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.OVERPAYMENT_ID, -1) != NVL(src.OVERPAYMENT_ID, -1)
            OR NVL(tgt.VOID_USER, '~') != NVL(src.VOID_USER, '~')
            OR NVL(tgt.VOID_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.VOID_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.MISC2, '~') != NVL(src.MISC2, '~')
            OR NVL(tgt.PREPAYMENT_ID, -1) != NVL(src.PREPAYMENT_ID, -1)
            OR NVL(tgt.CREDIT_INVOICE_ID, -1) != NVL(src.CREDIT_INVOICE_ID, -1)
            OR NVL(tgt.ALLOCATION_TYPE, '~') != NVL(src.ALLOCATION_TYPE, '~')
            OR NVL(tgt.RESERVATION_ID, -1) != NVL(src.RESERVATION_ID, -1)
            OR NVL(tgt.ITEM_MASTER_ID, -1) != NVL(src.ITEM_MASTER_ID, -1)
            OR NVL(tgt.ASPNET_USER_ID, -1) != NVL(src.ASPNET_USER_ID, -1)
            OR NVL(tgt.INVOICE_ITEM_TYPE_ID, -1) != NVL(src.INVOICE_ITEM_TYPE_ID, -1)
            OR NVL(tgt.SEASONAL_PRICE_ID, -1) != NVL(src.SEASONAL_PRICE_ID, -1)
            OR NVL(tgt.TRANSIENT_PRICE_ID, -1) != NVL(src.TRANSIENT_PRICE_ID, -1)
            OR NVL(tgt.SV_JOB_ID, -1) != NVL(src.SV_JOB_ID, -1)
            OR NVL(tgt.ORIGINAL_CREDIT_ITEM, '~') != NVL(src.ORIGINAL_CREDIT_ITEM, '~')
            OR NVL(tgt.TAX_EXEMPT, -1) != NVL(src.TAX_EXEMPT, -1)
            OR NVL(tgt.LAST_MODIFIED_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.LAST_MODIFIED_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.LAST_MODIFIED_ASPNET_USER, '~') != NVL(src.LAST_MODIFIED_ASPNET_USER, '~')
            OR NVL(tgt.DELETION_REASON, '~') != NVL(src.DELETION_REASON, '~')
            OR NVL(tgt.VOID_REASON, '~') != NVL(src.VOID_REASON, '~')
            OR NVL(tgt.START_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.START_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.END_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.END_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CREATION_PARTNER_ID, -1) != NVL(src.CREATION_PARTNER_ID, -1)
            OR NVL(tgt.DELETE_PARTNER_ID, -1) != NVL(src.DELETE_PARTNER_ID, -1)
            OR NVL(tgt.VOID_PARTNER_ID, -1) != NVL(src.VOID_PARTNER_ID, -1)
            OR NVL(tgt.ORIGINAL_PRICE, -1) != NVL(src.ORIGINAL_PRICE, -1)
            OR NVL(tgt.OVERRIDE_XERO_TAX_RATE, -1) != NVL(src.OVERRIDE_XERO_TAX_RATE, -1)
            OR NVL(tgt.OVERRIDE_XERO_SALES_ACCOUNT, -1) != NVL(src.OVERRIDE_XERO_SALES_ACCOUNT, -1)
            OR NVL(tgt.ORIGINAL_RESERVATION_PRICE, -1) != NVL(src.ORIGINAL_RESERVATION_PRICE, -1)
            OR NVL(tgt.NUMBER_OF_DECIMALS, -999999) != NVL(src.NUMBER_OF_DECIMALS, -999999)
            OR NVL(tgt.STRIPE_TRANSACTION_DATA_ID, -1) != NVL(src.STRIPE_TRANSACTION_DATA_ID, -1)
            OR NVL(tgt.VALUE_ALTERNATIVE, '~') != NVL(src.VALUE_ALTERNATIVE, '~')
            OR NVL(tgt.STRIPE_TERMINAL_ID, -1) != NVL(src.STRIPE_TERMINAL_ID, -1)
            OR NVL(tgt.STRIPE_APPLICATION_NAME, '~') != NVL(src.STRIPE_APPLICATION_NAME, '~')
            OR NVL(tgt.STRIPE_AID, '~') != NVL(src.STRIPE_AID, '~')
            OR NVL(tgt.ENTERED_AMOUNT, -1) != NVL(src.ENTERED_AMOUNT, -1)
            OR NVL(tgt.EXCHANGE_RATE, -1) != NVL(src.EXCHANGE_RATE, -1)
            OR NVL(tgt.CURRENCIES_ID, -1) != NVL(src.CURRENCIES_ID, -1)
            OR NVL(tgt.SV_CHARGE_INSTANCE_ID, -1) != NVL(src.SV_CHARGE_INSTANCE_ID, -1)
            OR NVL(tgt.SV_LABOR_INSTANCE_ID, -1) != NVL(src.SV_LABOR_INSTANCE_ID, -1)
            OR NVL(tgt.SV_PART_INSTANCE_ID, -1) != NVL(src.SV_PART_INSTANCE_ID, -1)
            OR NVL(tgt.REVENUE_GL_CODE, '~') != NVL(src.REVENUE_GL_CODE, '~')
            OR NVL(tgt.AR_GL_CODE, '~') != NVL(src.AR_GL_CODE, '~')
            OR NVL(tgt.PAYMENT_GL_CODE, '~') != NVL(src.PAYMENT_GL_CODE, '~')
            OR NVL(tgt.COGS_GL_CODE, '~') != NVL(src.COGS_GL_CODE, '~')
            OR NVL(tgt.INVENTORY_GL_CODE, '~') != NVL(src.INVENTORY_GL_CODE, '~')
            OR NVL(tgt.SALES_TAX_GL_CODE, -1) != NVL(src.SALES_TAX_GL_CODE, -1)
            OR NVL(tgt.PREPAYMENT_GL_CODE, '~') != NVL(src.PREPAYMENT_GL_CODE, '~')
            OR NVL(tgt.ACCOUNT_TYPE, -1) != NVL(src.ACCOUNT_TYPE, -1)
            OR NVL(tgt.APPLICATION_CRYPTOGRAM, '~') != NVL(src.APPLICATION_CRYPTOGRAM, '~')
            OR NVL(tgt.AUTHORIZATION_CODE, '~') != NVL(src.AUTHORIZATION_CODE, '~')
            OR NVL(tgt.AUTHORIZATION_RESPONSE_CODE, '~') != NVL(src.AUTHORIZATION_RESPONSE_CODE, '~')
            OR NVL(tgt.CARDHOLDER_VERIFICATION_METHOD, '~') != NVL(src.CARDHOLDER_VERIFICATION_METHOD, '~')
            OR NVL(tgt.TERMINAL_VERIFICATION_RESULTS, '~') != NVL(src.TERMINAL_VERIFICATION_RESULTS, '~')
            OR NVL(tgt.TRANSACTION_STATUS_INFORMATION, '~') != NVL(src.TRANSACTION_STATUS_INFORMATION, '~')
            OR NVL(tgt.TRACKING_CODE, '~') != NVL(src.TRACKING_CODE, '~')
            OR NVL(tgt.DISCOUNT_GL_CODE, -1) != NVL(src.DISCOUNT_GL_CODE, -1)
            OR NVL(tgt.OVERRIDE_TRACKING_CATEGORY1, '~') != NVL(src.OVERRIDE_TRACKING_CATEGORY1, '~')
            OR NVL(tgt.OVERRIDE_TRACKING_CATEGORY2, '~') != NVL(src.OVERRIDE_TRACKING_CATEGORY2, '~')
            OR NVL(tgt.QUICKBOOKS_PAYMENT_ID, -1) != NVL(src.QUICKBOOKS_PAYMENT_ID, -1)
            OR NVL(tgt.ALLOW_TOTAL_PRICE_ENTRY, -1) != NVL(src.ALLOW_TOTAL_PRICE_ENTRY, -1)
            OR NVL(tgt.ADDED_AUTOMATICALLY, '~') != NVL(src.ADDED_AUTOMATICALLY, '~')
            OR NVL(tgt.ALLOCATION_PERFORMED_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.ALLOCATION_PERFORMED_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CREATED_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CREATED_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
    WHEN NOT MATCHED THEN
        INSERT (
            ID, PREFIX, QUANTITY, TITLE, TYPE_FIELD, VALUE_FIELD, DISCOUNT, DISCOUNT_TYPE, TAXABLE, TAX, MISC, DISCOUNT_TOTAL, PRICE_SUFFIX, SUB_TOTAL, SUBTOTAL_WO_DISCOUNT, TAX_TOTAL, TOTAL, INVOICE_ID, CHARGE_GROUP, PAYMENT_ACCOUNT, PRICE_STR, IS_VOID, DATE_FIELD, TEXT_AUX, TEXT_AUX2, DISCOUNT_DATE_TIME, DISCOUNT_USER_ID, NOTES, PR_TYPE, STATUS_FIELD, DELETION_USER_ID, DELETION_DATE_TIME, OVERPAYMENT_ID, VOID_USER, VOID_DATE_TIME, MISC2, PREPAYMENT_ID, CREDIT_INVOICE_ID, ALLOCATION_TYPE, RESERVATION_ID, ITEM_MASTER_ID, ASPNET_USER_ID, INVOICE_ITEM_TYPE_ID, SEASONAL_PRICE_ID, TRANSIENT_PRICE_ID, SV_JOB_ID, ORIGINAL_CREDIT_ITEM, TAX_EXEMPT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_ASPNET_USER, DELETION_REASON, VOID_REASON, START_DATE_TIME, END_DATE_TIME, CREATION_PARTNER_ID, DELETE_PARTNER_ID, VOID_PARTNER_ID, ORIGINAL_PRICE, OVERRIDE_XERO_TAX_RATE, OVERRIDE_XERO_SALES_ACCOUNT, ORIGINAL_RESERVATION_PRICE, NUMBER_OF_DECIMALS, STRIPE_TRANSACTION_DATA_ID, VALUE_ALTERNATIVE, STRIPE_TERMINAL_ID, STRIPE_APPLICATION_NAME, STRIPE_AID, ENTERED_AMOUNT, EXCHANGE_RATE, CURRENCIES_ID, SV_CHARGE_INSTANCE_ID, SV_LABOR_INSTANCE_ID, SV_PART_INSTANCE_ID, REVENUE_GL_CODE, AR_GL_CODE, PAYMENT_GL_CODE, COGS_GL_CODE, INVENTORY_GL_CODE, SALES_TAX_GL_CODE, PREPAYMENT_GL_CODE, ACCOUNT_TYPE, APPLICATION_CRYPTOGRAM, AUTHORIZATION_CODE, AUTHORIZATION_RESPONSE_CODE, CARDHOLDER_VERIFICATION_METHOD, TERMINAL_VERIFICATION_RESULTS, TRANSACTION_STATUS_INFORMATION, TRACKING_CODE, DISCOUNT_GL_CODE, OVERRIDE_TRACKING_CATEGORY1, OVERRIDE_TRACKING_CATEGORY2, QUICKBOOKS_PAYMENT_ID, ALLOW_TOTAL_PRICE_ENTRY, ADDED_AUTOMATICALLY, ALLOCATION_PERFORMED_DATE, CREATED_DATE,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.PREFIX, src.QUANTITY, src.TITLE, src.TYPE_FIELD, src.VALUE_FIELD, src.DISCOUNT, src.DISCOUNT_TYPE, src.TAXABLE, src.TAX, src.MISC, src.DISCOUNT_TOTAL, src.PRICE_SUFFIX, src.SUB_TOTAL, src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TOTAL, src.INVOICE_ID, src.CHARGE_GROUP, src.PAYMENT_ACCOUNT, src.PRICE_STR, src.IS_VOID, src.DATE_FIELD, src.TEXT_AUX, src.TEXT_AUX2, src.DISCOUNT_DATE_TIME, src.DISCOUNT_USER_ID, src.NOTES, src.PR_TYPE, src.STATUS_FIELD, src.DELETION_USER_ID, src.DELETION_DATE_TIME, src.OVERPAYMENT_ID, src.VOID_USER, src.VOID_DATE_TIME, src.MISC2, src.PREPAYMENT_ID, src.CREDIT_INVOICE_ID, src.ALLOCATION_TYPE, src.RESERVATION_ID, src.ITEM_MASTER_ID, src.ASPNET_USER_ID, src.INVOICE_ITEM_TYPE_ID, src.SEASONAL_PRICE_ID, src.TRANSIENT_PRICE_ID, src.SV_JOB_ID, src.ORIGINAL_CREDIT_ITEM, src.TAX_EXEMPT, src.LAST_MODIFIED_DATE_TIME, src.LAST_MODIFIED_ASPNET_USER, src.DELETION_REASON, src.VOID_REASON, src.START_DATE_TIME, src.END_DATE_TIME, src.CREATION_PARTNER_ID, src.DELETE_PARTNER_ID, src.VOID_PARTNER_ID, src.ORIGINAL_PRICE, src.OVERRIDE_XERO_TAX_RATE, src.OVERRIDE_XERO_SALES_ACCOUNT, src.ORIGINAL_RESERVATION_PRICE, src.NUMBER_OF_DECIMALS, src.STRIPE_TRANSACTION_DATA_ID, src.VALUE_ALTERNATIVE, src.STRIPE_TERMINAL_ID, src.STRIPE_APPLICATION_NAME, src.STRIPE_AID, src.ENTERED_AMOUNT, src.EXCHANGE_RATE, src.CURRENCIES_ID, src.SV_CHARGE_INSTANCE_ID, src.SV_LABOR_INSTANCE_ID, src.SV_PART_INSTANCE_ID, src.REVENUE_GL_CODE, src.AR_GL_CODE, src.PAYMENT_GL_CODE, src.COGS_GL_CODE, src.INVENTORY_GL_CODE, src.SALES_TAX_GL_CODE, src.PREPAYMENT_GL_CODE, src.ACCOUNT_TYPE, src.APPLICATION_CRYPTOGRAM, src.AUTHORIZATION_CODE, src.AUTHORIZATION_RESPONSE_CODE, src.CARDHOLDER_VERIFICATION_METHOD, src.TERMINAL_VERIFICATION_RESULTS, src.TRANSACTION_STATUS_INFORMATION, src.TRACKING_CODE, src.DISCOUNT_GL_CODE, src.OVERRIDE_TRACKING_CATEGORY1, src.OVERRIDE_TRACKING_CATEGORY2, src.QUICKBOOKS_PAYMENT_ID, src.ALLOW_TOTAL_PRICE_ENTRY, src.ADDED_AUTOMATICALLY, src.ALLOCATION_PERFORMED_DATE, src.CREATED_DATE,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_INVOICE_ITEMS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_INVOICE_ITEMS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_INVOICE_ITEMS;
/
