
-- ============================================================================
-- Merge STG_MOLO_TRANSIENT_PRICES to DW_MOLO_TRANSIENT_PRICES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_TRANSIENT_PRICES
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_TRANSIENT_PRICES tgt
    USING STG_MOLO_TRANSIENT_PRICES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.START_DATE = src.START_DATE,
            tgt.END_DATE = src.END_DATE,
            tgt.FEE = src.FEE,
            tgt.RATE_NAME = src.RATE_NAME,
            tgt.TRANSIENT_CHARGE_METHOD_ID = src.TRANSIENT_CHARGE_METHOD_ID,
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.TAXABLE = src.TAXABLE,
            tgt.TAX = src.TAX,
            tgt.RATE_DETAILS = src.RATE_DETAILS,
            tgt.RATE_SHORT_NAME = src.RATE_SHORT_NAME,
            tgt.ONLINE_PAYMENT_PLACEHOLDER = src.ONLINE_PAYMENT_PLACEHOLDER,
            tgt.XERO_ITEM_CODE = src.XERO_ITEM_CODE,
            tgt.XERO_ID = src.XERO_ID,
            tgt.FIRST_TRACKING_CATEGORY = src.FIRST_TRACKING_CATEGORY,
            tgt.SECOND_TRACKING_CATEGORY = src.SECOND_TRACKING_CATEGORY,
            tgt.TRANSIENT_INVOICING_METHOD_ID = src.TRANSIENT_INVOICING_METHOD_ID,
            tgt.SV_INVENTORY_CATEGORY_ID = src.SV_INVENTORY_CATEGORY_ID,
            tgt.SV_INVENTORY_SUB_CATEGORY_ID = src.SV_INVENTORY_SUB_CATEGORY_ID,
            tgt.CREATION_DATE_TIME = src.CREATION_DATE_TIME,
            tgt.ASPNET_USER_ID = src.ASPNET_USER_ID,
            tgt.CHECK_IN_TERMS = src.CHECK_IN_TERMS,
            tgt.CHECK_OUT_TERMS = src.CHECK_OUT_TERMS,
            tgt.ONLINE_PAYMENT_COMPLETION = src.ONLINE_PAYMENT_COMPLETION,
            tgt.DUE_DATE_DAYS = src.DUE_DATE_DAYS,
            tgt.DUE_DATE_SETTINGS_ID = src.DUE_DATE_SETTINGS_ID,
            tgt.HOURLY_CALCULATION = src.HOURLY_CALCULATION,
            tgt.ROUND_MINUTES = src.ROUND_MINUTES,
            tgt.MINIMUM_HOURS = src.MINIMUM_HOURS,
            tgt.NUM_HOURS_BLOCK = src.NUM_HOURS_BLOCK,
            tgt.CHARGE_CATEGORY = src.CHARGE_CATEGORY,
            tgt.INTRO_TEXT = src.INTRO_TEXT,
            tgt.REVENUE_GL_CODE = src.REVENUE_GL_CODE,
            tgt.AR_GL_CODE = src.AR_GL_CODE,
            tgt.SALES_TAX_GL_CODE = src.SALES_TAX_GL_CODE,
            tgt.DELETION_DATETIME = src.DELETION_DATETIME,
            tgt.DELETION_ASPNET_USER_ID = src.DELETION_ASPNET_USER_ID,
            tgt.RECORD_STATUS_ID = src.RECORD_STATUS_ID,
            tgt.RECURRING_INVOICE_OPTIONS_ID = src.RECURRING_INVOICE_OPTIONS_ID,
            tgt.RECURRING = src.RECURRING,
            tgt.TRACKING_CODE = src.TRACKING_CODE,
            tgt.ALTERNATE_RESERVATION_NAME = src.ALTERNATE_RESERVATION_NAME,
            tgt.RESOURCE_RATE = src.RESOURCE_RATE,
            tgt.QUANTITY_CAP = src.QUANTITY_CAP,
            tgt.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS = src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.START_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.START_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.END_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.END_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.FEE, -999999) != NVL(src.FEE, -999999)
            OR NVL(tgt.RATE_NAME, '~') != NVL(src.RATE_NAME, '~')
            OR NVL(tgt.TRANSIENT_CHARGE_METHOD_ID, -1) != NVL(src.TRANSIENT_CHARGE_METHOD_ID, -1)
            OR NVL(tgt.MARINA_LOCATION_ID, -1) != NVL(src.MARINA_LOCATION_ID, -1)
            OR NVL(tgt.TAXABLE, -1) != NVL(src.TAXABLE, -1)
            OR NVL(tgt.TAX, -999999) != NVL(src.TAX, -999999)
            OR NVL(tgt.RATE_DETAILS, '~') != NVL(src.RATE_DETAILS, '~')
            OR NVL(tgt.RATE_SHORT_NAME, '~') != NVL(src.RATE_SHORT_NAME, '~')
            OR NVL(tgt.ONLINE_PAYMENT_PLACEHOLDER, '~') != NVL(src.ONLINE_PAYMENT_PLACEHOLDER, '~')
            OR NVL(tgt.XERO_ITEM_CODE, '~') != NVL(src.XERO_ITEM_CODE, '~')
            OR NVL(tgt.XERO_ID, '~') != NVL(src.XERO_ID, '~')
            OR NVL(tgt.FIRST_TRACKING_CATEGORY, -1) != NVL(src.FIRST_TRACKING_CATEGORY, -1)
            OR NVL(tgt.SECOND_TRACKING_CATEGORY, -1) != NVL(src.SECOND_TRACKING_CATEGORY, -1)
            OR NVL(tgt.TRANSIENT_INVOICING_METHOD_ID, -1) != NVL(src.TRANSIENT_INVOICING_METHOD_ID, -1)
            OR NVL(tgt.SV_INVENTORY_CATEGORY_ID, -1) != NVL(src.SV_INVENTORY_CATEGORY_ID, -1)
            OR NVL(tgt.SV_INVENTORY_SUB_CATEGORY_ID, -1) != NVL(src.SV_INVENTORY_SUB_CATEGORY_ID, -1)
            OR NVL(tgt.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.ASPNET_USER_ID, '~') != NVL(src.ASPNET_USER_ID, '~')
            OR NVL(tgt.CHECK_IN_TERMS, '~') != NVL(src.CHECK_IN_TERMS, '~')
            OR NVL(tgt.CHECK_OUT_TERMS, '~') != NVL(src.CHECK_OUT_TERMS, '~')
            OR NVL(tgt.ONLINE_PAYMENT_COMPLETION, '~') != NVL(src.ONLINE_PAYMENT_COMPLETION, '~')
            OR NVL(tgt.DUE_DATE_DAYS, -1) != NVL(src.DUE_DATE_DAYS, -1)
            OR NVL(tgt.DUE_DATE_SETTINGS_ID, -1) != NVL(src.DUE_DATE_SETTINGS_ID, -1)
            OR NVL(tgt.HOURLY_CALCULATION, '~') != NVL(src.HOURLY_CALCULATION, '~')
            OR NVL(tgt.ROUND_MINUTES, -1) != NVL(src.ROUND_MINUTES, -1)
            OR NVL(tgt.MINIMUM_HOURS, -1) != NVL(src.MINIMUM_HOURS, -1)
            OR NVL(tgt.NUM_HOURS_BLOCK, -1) != NVL(src.NUM_HOURS_BLOCK, -1)
            OR NVL(tgt.CHARGE_CATEGORY, '~') != NVL(src.CHARGE_CATEGORY, '~')
            OR NVL(tgt.INTRO_TEXT, '~') != NVL(src.INTRO_TEXT, '~')
            OR NVL(tgt.REVENUE_GL_CODE, '~') != NVL(src.REVENUE_GL_CODE, '~')
            OR NVL(tgt.AR_GL_CODE, '~') != NVL(src.AR_GL_CODE, '~')
            OR NVL(tgt.SALES_TAX_GL_CODE, '~') != NVL(src.SALES_TAX_GL_CODE, '~')
            OR NVL(tgt.DELETION_DATETIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DELETION_DATETIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DELETION_ASPNET_USER_ID, '~') != NVL(src.DELETION_ASPNET_USER_ID, '~')
            OR NVL(tgt.RECORD_STATUS_ID, -1) != NVL(src.RECORD_STATUS_ID, -1)
            OR NVL(tgt.RECURRING_INVOICE_OPTIONS_ID, -1) != NVL(src.RECURRING_INVOICE_OPTIONS_ID, -1)
            OR NVL(tgt.RECURRING, -1) != NVL(src.RECURRING, -1)
            OR NVL(tgt.TRACKING_CODE, '~') != NVL(src.TRACKING_CODE, '~')
            OR NVL(tgt.ALTERNATE_RESERVATION_NAME, '~') != NVL(src.ALTERNATE_RESERVATION_NAME, '~')
            OR NVL(tgt.RESOURCE_RATE, -1) != NVL(src.RESOURCE_RATE, -1)
            OR NVL(tgt.QUANTITY_CAP, -1) != NVL(src.QUANTITY_CAP, -1)
            OR NVL(tgt.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, -1) != NVL(src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS, -1)
    WHEN NOT MATCHED THEN
        INSERT (
            ID, START_DATE, END_DATE, FEE, RATE_NAME, TRANSIENT_CHARGE_METHOD_ID, MARINA_LOCATION_ID, TAXABLE, TAX, RATE_DETAILS, RATE_SHORT_NAME, ONLINE_PAYMENT_PLACEHOLDER, XERO_ITEM_CODE, XERO_ID, FIRST_TRACKING_CATEGORY, SECOND_TRACKING_CATEGORY, TRANSIENT_INVOICING_METHOD_ID, SV_INVENTORY_CATEGORY_ID, SV_INVENTORY_SUB_CATEGORY_ID, CREATION_DATE_TIME, ASPNET_USER_ID, CHECK_IN_TERMS, CHECK_OUT_TERMS, ONLINE_PAYMENT_COMPLETION, DUE_DATE_DAYS, DUE_DATE_SETTINGS_ID, HOURLY_CALCULATION, ROUND_MINUTES, MINIMUM_HOURS, NUM_HOURS_BLOCK, CHARGE_CATEGORY, INTRO_TEXT, REVENUE_GL_CODE, AR_GL_CODE, SALES_TAX_GL_CODE, DELETION_DATETIME, DELETION_ASPNET_USER_ID, RECORD_STATUS_ID, RECURRING_INVOICE_OPTIONS_ID, RECURRING, TRACKING_CODE, ALTERNATE_RESERVATION_NAME, RESOURCE_RATE, QUANTITY_CAP, ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.START_DATE, src.END_DATE, src.FEE, src.RATE_NAME, src.TRANSIENT_CHARGE_METHOD_ID, src.MARINA_LOCATION_ID, src.TAXABLE, src.TAX, src.RATE_DETAILS, src.RATE_SHORT_NAME, src.ONLINE_PAYMENT_PLACEHOLDER, src.XERO_ITEM_CODE, src.XERO_ID, src.FIRST_TRACKING_CATEGORY, src.SECOND_TRACKING_CATEGORY, src.TRANSIENT_INVOICING_METHOD_ID, src.SV_INVENTORY_CATEGORY_ID, src.SV_INVENTORY_SUB_CATEGORY_ID, src.CREATION_DATE_TIME, src.ASPNET_USER_ID, src.CHECK_IN_TERMS, src.CHECK_OUT_TERMS, src.ONLINE_PAYMENT_COMPLETION, src.DUE_DATE_DAYS, src.DUE_DATE_SETTINGS_ID, src.HOURLY_CALCULATION, src.ROUND_MINUTES, src.MINIMUM_HOURS, src.NUM_HOURS_BLOCK, src.CHARGE_CATEGORY, src.INTRO_TEXT, src.REVENUE_GL_CODE, src.AR_GL_CODE, src.SALES_TAX_GL_CODE, src.DELETION_DATETIME, src.DELETION_ASPNET_USER_ID, src.RECORD_STATUS_ID, src.RECURRING_INVOICE_OPTIONS_ID, src.RECURRING, src.TRACKING_CODE, src.ALTERNATE_RESERVATION_NAME, src.RESOURCE_RATE, src.QUANTITY_CAP, src.ALLOW_POSTING_TO_NON_INCOME_ACCOUNTS,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_TRANSIENT_PRICES: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_TRANSIENT_PRICES: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_TRANSIENT_PRICES;
/
