
-- ============================================================================
-- Merge STG_MOLO_INVOICES to DW_MOLO_INVOICES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_INVOICES
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    v_timestamp := SYSTIMESTAMP;
    
    MERGE INTO DW_MOLO_INVOICES tgt
    USING STG_MOLO_INVOICES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.DATE_FIELD = src.DATE_FIELD,
            tgt.DOLLAR_DISCOUNT = src.DOLLAR_DISCOUNT,
            tgt.PERCENT_DISCOUNT = src.PERCENT_DISCOUNT,
            tgt.ACTIVE = src.ACTIVE,
            tgt.CLOSING_DATE = src.CLOSING_DATE,
            tgt.DISCOUNT_TOTAL = src.DISCOUNT_TOTAL,
            tgt.OPENED = src.OPENED,
            tgt.PAYED = src.PAYED,
            tgt.SUBTOTAL = src.SUBTOTAL,
            tgt.SUBTOTAL_WO_DISCOUNT = src.SUBTOTAL_WO_DISCOUNT,
            tgt.TAX_TOTAL = src.TAX_TOTAL,
            tgt.TITLE = src.TITLE,
            tgt.TOTAL = src.TOTAL,
            tgt.RESERVATION_ID = src.RESERVATION_ID,
            tgt.ACCOUNT_ID = src.ACCOUNT_ID,
            tgt.SERVICE_PAID_AMOUNT = src.SERVICE_PAID_AMOUNT,
            tgt.MARINA_PAID_AMOUNT = src.MARINA_PAID_AMOUNT,
            tgt.GAS_PAID_AMOUNT = src.GAS_PAID_AMOUNT,
            tgt.INVOICE_STATUS_ID = src.INVOICE_STATUS_ID,
            tgt.START_DATE = src.START_DATE,
            tgt.INSTALLMENTS_PAYMENT_METHOD_ID = src.INSTALLMENTS_PAYMENT_METHOD_ID,
            tgt.SCHEDULED_FOR_CRON = src.SCHEDULED_FOR_CRON,
            tgt.ORIGINAL_INVOICE = src.ORIGINAL_INVOICE,
            tgt.PAYMENTS_SENT_TO_XERO = src.PAYMENTS_SENT_TO_XERO,
            tgt.WORK_ORDER_ID = src.WORK_ORDER_ID,
            tgt.IS_INSTALLMENT_INVOICE = src.IS_INSTALLMENT_INVOICE,
            tgt.VOID_USER = src.VOID_USER,
            tgt.VOID_DATE_TIME = src.VOID_DATE_TIME,
            tgt.CREATION_USER = src.CREATION_USER,
            tgt.PAYMENT_ID = src.PAYMENT_ID,
            tgt.QB_INVOICE_ID = src.QB_INVOICE_ID,
            tgt.INVOICE_TYPE_ID = src.INVOICE_TYPE_ID,
            tgt.INVOICE_DATE = src.INVOICE_DATE,
            tgt.DUE_DATE = src.DUE_DATE,
            tgt.CURRENCY_CODE = src.CURRENCY_CODE,
            tgt.LAST_MODIFIED_DATE_TIME = src.LAST_MODIFIED_DATE_TIME,
            tgt.LAST_MODIFIED_ASPNET_USER = src.LAST_MODIFIED_ASPNET_USER,
            tgt.VOID_REASON = src.VOID_REASON,
            tgt.CREATE_PARTNER_ID = src.CREATE_PARTNER_ID,
            tgt.VOID_PARTNER_ID = src.VOID_PARTNER_ID,
            tgt.UPDATE_HASH = src.UPDATE_HASH,
            tgt.SCHEDULED_FOR_INVENTORY_CRON = src.SCHEDULED_FOR_INVENTORY_CRON,
            tgt.SCHEDULED_FOR_SUBLET_CRON = src.SCHEDULED_FOR_SUBLET_CRON,
            tgt.SCHEDULED_FOR_LABOR_CRON = src.SCHEDULED_FOR_LABOR_CRON,
            tgt.CREATED_ON_MOBILE = src.CREATED_ON_MOBILE,
            tgt.STRIPE_INVOICE_ID = src.STRIPE_INVOICE_ID,
            tgt.SENT_TO_STRIPE = src.SENT_TO_STRIPE,
            tgt.RESOURCE_BOOKING_ID = src.RESOURCE_BOOKING_ID,
            tgt.MODIFIED_ON_MOBILE = src.MODIFIED_ON_MOBILE,
            tgt.NOTE = src.NOTE,
            tgt.QUICKBOOKS_INVOICE_ID = src.QUICKBOOKS_INVOICE_ID,
            tgt.TAX_CAP = src.TAX_CAP,
            tgt.IS_SURCHARGE = src.IS_SURCHARGE,
            tgt.HASH_CHECK = src.HASH_CHECK,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.ID, -999) <> NVL(src.ID, -999) OR
            NVL(tgt.DATE_FIELD, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.DATE_FIELD, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.DOLLAR_DISCOUNT, -999.999) <> NVL(src.DOLLAR_DISCOUNT, -999.999) OR
            NVL(tgt.PERCENT_DISCOUNT, -999.999) <> NVL(src.PERCENT_DISCOUNT, -999.999) OR
            NVL(tgt.ACTIVE, -999) <> NVL(src.ACTIVE, -999) OR
            NVL(tgt.CLOSING_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CLOSING_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.DISCOUNT_TOTAL, -999.999) <> NVL(src.DISCOUNT_TOTAL, -999.999) OR
            NVL(tgt.OPENED, -999) <> NVL(src.OPENED, -999) OR
            NVL(tgt.PAYED, -999.999) <> NVL(src.PAYED, -999.999) OR
            NVL(tgt.SUBTOTAL, -999.999) <> NVL(src.SUBTOTAL, -999.999) OR
            NVL(tgt.SUBTOTAL_WO_DISCOUNT, -999.999) <> NVL(src.SUBTOTAL_WO_DISCOUNT, -999.999) OR
            NVL(tgt.TAX_TOTAL, -999.999) <> NVL(src.TAX_TOTAL, -999.999) OR
            NVL(tgt.TITLE, '~NULL~') <> NVL(src.TITLE, '~NULL~') OR
            NVL(tgt.TOTAL, -999.999) <> NVL(src.TOTAL, -999.999) OR
            NVL(tgt.RESERVATION_ID, -999) <> NVL(src.RESERVATION_ID, -999) OR
            NVL(tgt.ACCOUNT_ID, -999) <> NVL(src.ACCOUNT_ID, -999) OR
            NVL(tgt.SERVICE_PAID_AMOUNT, -999.999) <> NVL(src.SERVICE_PAID_AMOUNT, -999.999) OR
            NVL(tgt.MARINA_PAID_AMOUNT, -999.999) <> NVL(src.MARINA_PAID_AMOUNT, -999.999) OR
            NVL(tgt.GAS_PAID_AMOUNT, -999.999) <> NVL(src.GAS_PAID_AMOUNT, -999.999) OR
            NVL(tgt.INVOICE_STATUS_ID, -999) <> NVL(src.INVOICE_STATUS_ID, -999) OR
            NVL(tgt.START_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.START_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.INSTALLMENTS_PAYMENT_METHOD_ID, -999) <> NVL(src.INSTALLMENTS_PAYMENT_METHOD_ID, -999) OR
            NVL(tgt.SCHEDULED_FOR_CRON, -999) <> NVL(src.SCHEDULED_FOR_CRON, -999) OR
            NVL(tgt.ORIGINAL_INVOICE, -999) <> NVL(src.ORIGINAL_INVOICE, -999) OR
            NVL(tgt.PAYMENTS_SENT_TO_XERO, -999) <> NVL(src.PAYMENTS_SENT_TO_XERO, -999) OR
            NVL(tgt.WORK_ORDER_ID, -999) <> NVL(src.WORK_ORDER_ID, -999) OR
            NVL(tgt.IS_INSTALLMENT_INVOICE, -999) <> NVL(src.IS_INSTALLMENT_INVOICE, -999) OR
            NVL(tgt.VOID_USER, '~NULL~') <> NVL(src.VOID_USER, '~NULL~') OR
            NVL(tgt.VOID_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.VOID_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.CREATION_USER, '~NULL~') <> NVL(src.CREATION_USER, '~NULL~') OR
            NVL(tgt.PAYMENT_ID, -999) <> NVL(src.PAYMENT_ID, -999) OR
            NVL(tgt.QB_INVOICE_ID, -999) <> NVL(src.QB_INVOICE_ID, -999) OR
            NVL(tgt.INVOICE_TYPE_ID, -999) <> NVL(src.INVOICE_TYPE_ID, -999) OR
            NVL(tgt.INVOICE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.INVOICE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.DUE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.DUE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.CURRENCY_CODE, '~NULL~') <> NVL(src.CURRENCY_CODE, '~NULL~') OR
            NVL(tgt.LAST_MODIFIED_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.LAST_MODIFIED_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.LAST_MODIFIED_ASPNET_USER, '~NULL~') <> NVL(src.LAST_MODIFIED_ASPNET_USER, '~NULL~') OR
            NVL(tgt.VOID_REASON, '~NULL~') <> NVL(src.VOID_REASON, '~NULL~') OR
            NVL(tgt.CREATE_PARTNER_ID, -999) <> NVL(src.CREATE_PARTNER_ID, -999) OR
            NVL(tgt.VOID_PARTNER_ID, -999) <> NVL(src.VOID_PARTNER_ID, -999) OR
            NVL(tgt.UPDATE_HASH, '~NULL~') <> NVL(src.UPDATE_HASH, '~NULL~') OR
            NVL(tgt.SCHEDULED_FOR_INVENTORY_CRON, -999) <> NVL(src.SCHEDULED_FOR_INVENTORY_CRON, -999) OR
            NVL(tgt.SCHEDULED_FOR_SUBLET_CRON, -999) <> NVL(src.SCHEDULED_FOR_SUBLET_CRON, -999) OR
            NVL(tgt.SCHEDULED_FOR_LABOR_CRON, -999) <> NVL(src.SCHEDULED_FOR_LABOR_CRON, -999) OR
            NVL(tgt.CREATED_ON_MOBILE, -999) <> NVL(src.CREATED_ON_MOBILE, -999) OR
            NVL(tgt.STRIPE_INVOICE_ID, '~NULL~') <> NVL(src.STRIPE_INVOICE_ID, '~NULL~') OR
            NVL(tgt.SENT_TO_STRIPE, -999) <> NVL(src.SENT_TO_STRIPE, -999) OR
            NVL(tgt.RESOURCE_BOOKING_ID, -999) <> NVL(src.RESOURCE_BOOKING_ID, -999) OR
            NVL(tgt.MODIFIED_ON_MOBILE, -999) <> NVL(src.MODIFIED_ON_MOBILE, -999) OR
            NVL(tgt.NOTE, '~NULL~') <> NVL(src.NOTE, '~NULL~') OR
            NVL(tgt.QUICKBOOKS_INVOICE_ID, '~NULL~') <> NVL(src.QUICKBOOKS_INVOICE_ID, '~NULL~') OR
            NVL(tgt.TAX_CAP, -999.999) <> NVL(src.TAX_CAP, -999.999) OR
            NVL(tgt.IS_SURCHARGE, -999) <> NVL(src.IS_SURCHARGE, -999) OR
            NVL(tgt.HASH_CHECK, -999) <> NVL(src.HASH_CHECK, -999)
        )
    WHEN NOT MATCHED THEN
        INSERT (
            ID, DATE_FIELD, DOLLAR_DISCOUNT, PERCENT_DISCOUNT, ACTIVE, CLOSING_DATE, DISCOUNT_TOTAL, OPENED, PAYED, SUBTOTAL, SUBTOTAL_WO_DISCOUNT, TAX_TOTAL, TITLE, TOTAL, RESERVATION_ID, ACCOUNT_ID, SERVICE_PAID_AMOUNT, MARINA_PAID_AMOUNT, GAS_PAID_AMOUNT, INVOICE_STATUS_ID, START_DATE, INSTALLMENTS_PAYMENT_METHOD_ID, SCHEDULED_FOR_CRON, ORIGINAL_INVOICE, PAYMENTS_SENT_TO_XERO, WORK_ORDER_ID, IS_INSTALLMENT_INVOICE, VOID_USER, VOID_DATE_TIME, CREATION_USER, PAYMENT_ID, QB_INVOICE_ID, INVOICE_TYPE_ID, INVOICE_DATE, DUE_DATE, CURRENCY_CODE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_ASPNET_USER, VOID_REASON, CREATE_PARTNER_ID, VOID_PARTNER_ID, UPDATE_HASH, SCHEDULED_FOR_INVENTORY_CRON, SCHEDULED_FOR_SUBLET_CRON, SCHEDULED_FOR_LABOR_CRON, CREATED_ON_MOBILE, STRIPE_INVOICE_ID, SENT_TO_STRIPE, RESOURCE_BOOKING_ID, MODIFIED_ON_MOBILE, NOTE, QUICKBOOKS_INVOICE_ID, TAX_CAP, IS_SURCHARGE, HASH_CHECK,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.DATE_FIELD, src.DOLLAR_DISCOUNT, src.PERCENT_DISCOUNT, src.ACTIVE, src.CLOSING_DATE, src.DISCOUNT_TOTAL, src.OPENED, src.PAYED, src.SUBTOTAL, src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TITLE, src.TOTAL, src.RESERVATION_ID, src.ACCOUNT_ID, src.SERVICE_PAID_AMOUNT, src.MARINA_PAID_AMOUNT, src.GAS_PAID_AMOUNT, src.INVOICE_STATUS_ID, src.START_DATE, src.INSTALLMENTS_PAYMENT_METHOD_ID, src.SCHEDULED_FOR_CRON, src.ORIGINAL_INVOICE, src.PAYMENTS_SENT_TO_XERO, src.WORK_ORDER_ID, src.IS_INSTALLMENT_INVOICE, src.VOID_USER, src.VOID_DATE_TIME, src.CREATION_USER, src.PAYMENT_ID, src.QB_INVOICE_ID, src.INVOICE_TYPE_ID, src.INVOICE_DATE, src.DUE_DATE, src.CURRENCY_CODE, src.LAST_MODIFIED_DATE_TIME, src.LAST_MODIFIED_ASPNET_USER, src.VOID_REASON, src.CREATE_PARTNER_ID, src.VOID_PARTNER_ID, src.UPDATE_HASH, src.SCHEDULED_FOR_INVENTORY_CRON, src.SCHEDULED_FOR_SUBLET_CRON, src.SCHEDULED_FOR_LABOR_CRON, src.CREATED_ON_MOBILE, src.STRIPE_INVOICE_ID, src.SENT_TO_STRIPE, src.RESOURCE_BOOKING_ID, src.MODIFIED_ON_MOBILE, src.NOTE, src.QUICKBOOKS_INVOICE_ID, src.TAX_CAP, src.IS_SURCHARGE, src.HASH_CHECK,
            v_timestamp,
            v_timestamp
        );
    
    -- Count updated records
    SELECT COUNT(*) INTO v_updated
    FROM DW_MOLO_INVOICES
    WHERE DW_LAST_UPDATED = v_timestamp
    AND DW_LAST_UPDATED > DW_LAST_INSERTED;
    
    -- Count inserted records
    SELECT COUNT(*) INTO v_inserted
    FROM DW_MOLO_INVOICES
    WHERE DW_LAST_INSERTED = v_timestamp;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_INVOICES: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_INVOICES: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_INVOICES;
/
