
-- ============================================================================
-- Merge STG_STELLAR_BOOKINGS to DW_STELLAR_BOOKINGS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_BOOKINGS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_BOOKINGS tgt
    USING STG_STELLAR_BOOKINGS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.CUSTOMER_ID = src.CUSTOMER_ID,
            tgt.CREATOR_ID = src.CREATOR_ID,
            tgt.ADMIN_ID = src.ADMIN_ID,
            tgt.BILLING_FIRST_NAME = src.BILLING_FIRST_NAME,
            tgt.BILLING_LAST_NAME = src.BILLING_LAST_NAME,
            tgt.BILLING_STREET1 = src.BILLING_STREET1,
            tgt.BILLING_STREET2 = src.BILLING_STREET2,
            tgt.BILLING_CITY = src.BILLING_CITY,
            tgt.BILLING_STATE = src.BILLING_STATE,
            tgt.BILLING_COUNTRY = src.BILLING_COUNTRY,
            tgt.BILLING_ZIP = src.BILLING_ZIP,
            tgt.CC_SAVED_NAME = src.CC_SAVED_NAME,
            tgt.CC_SAVED_LAST4 = src.CC_SAVED_LAST4,
            tgt.CC_SAVED_PROFILE_ID = src.CC_SAVED_PROFILE_ID,
            tgt.CC_SAVED_METHOD_ID = src.CC_SAVED_METHOD_ID,
            tgt.CC_SAVED_ADDRESS_ID = src.CC_SAVED_ADDRESS_ID,
            tgt.CC_PREAUTH_ID = src.CC_PREAUTH_ID,
            tgt.CC_PREAUTH_AMOUNT = src.CC_PREAUTH_AMOUNT,
            tgt.CC_CONNECT_TYPE = src.CC_CONNECT_TYPE,
            tgt.CC_CONNECT_ID = src.CC_CONNECT_ID,
            tgt.ACCESSORIES_CUSTOM_PRICE = src.ACCESSORIES_CUSTOM_PRICE,
            tgt.ACCESSORIES_TOTAL = src.ACCESSORIES_TOTAL,
            tgt.INSURANCE_AMOUNT = src.INSURANCE_AMOUNT,
            tgt.PETS = src.PETS,
            tgt.PARKING = src.PARKING,
            tgt.PARKING_OVERRIDE = src.PARKING_OVERRIDE,
            tgt.BOATS_TOTAL = src.BOATS_TOTAL,
            tgt.POS_TOTAL = src.POS_TOTAL,
            tgt.USE_CLUB_CREDITS = src.USE_CLUB_CREDITS,
            tgt.NO_SHOW_FEE = src.NO_SHOW_FEE,
            tgt.CANCELLATION_FEE = src.CANCELLATION_FEE,
            tgt.CLUB_FEES = src.CLUB_FEES,
            tgt.CLUB_FEES_OVERRIDE = src.CLUB_FEES_OVERRIDE,
            tgt.SUB_TOTAL = src.SUB_TOTAL,
            tgt.CONVENIENCE_FEE = src.CONVENIENCE_FEE,
            tgt.CONVENIENCE_FEE_WAIVED = src.CONVENIENCE_FEE_WAIVED,
            tgt.INTERNAL_APPLICATION_FEE = src.INTERNAL_APPLICATION_FEE,
            tgt.TAX_1 = src.TAX_1,
            tgt.TAX_1_EXEMPT = src.TAX_1_EXEMPT,
            tgt.TAX_1_RATE_OVERRIDE = src.TAX_1_RATE_OVERRIDE,
            tgt.TAX_2 = src.TAX_2,
            tgt.TAX_2_EXEMPT = src.TAX_2_EXEMPT,
            tgt.CHECK_IN_TAX_1 = src.CHECK_IN_TAX_1,
            tgt.CHECK_IN_TAX_2 = src.CHECK_IN_TAX_2,
            tgt.CHECK_IN_TOTAL = src.CHECK_IN_TOTAL,
            tgt.DEPOSIT_TOTAL = src.DEPOSIT_TOTAL,
            tgt.DEPOSIT_OVERRIDE = src.DEPOSIT_OVERRIDE,
            tgt.DEPOSIT_WAIVED = src.DEPOSIT_WAIVED,
            tgt.GRATUITY = src.GRATUITY,
            tgt.GRAND_TOTAL = src.GRAND_TOTAL,
            tgt.ADJUSTMENT_TOTAL = src.ADJUSTMENT_TOTAL,
            tgt.AMOUNT_PAID = src.AMOUNT_PAID,
            tgt.NOTES = src.NOTES,
            tgt.NOTES_CONTRACT = src.NOTES_CONTRACT,
            tgt.NOTES_FROM_CUSTOMER = src.NOTES_FROM_CUSTOMER,
            tgt.NOTES_FROM_CUSTOMER_CONTRACT = src.NOTES_FROM_CUSTOMER_CONTRACT,
            tgt.NOTES_FOR_CUSTOMER = src.NOTES_FOR_CUSTOMER,
            tgt.NOTES_FOR_CUSTOMER_CONTRACT = src.NOTES_FOR_CUSTOMER_CONTRACT,
            tgt.FRONTEND = src.FRONTEND,
            tgt.IS_ON_HOLD = src.IS_ON_HOLD,
            tgt.IS_LOCKED = src.IS_LOCKED,
            tgt.IS_FINALIZED = src.IS_FINALIZED,
            tgt.IS_CANCELED = src.IS_CANCELED,
            tgt.OVERRIDE_TURNAROUND_TIME = src.OVERRIDE_TURNAROUND_TIME,
            tgt.CANCELLATION_TYPE = src.CANCELLATION_TYPE,
            tgt.BYPASS_CLUB_RESTRICTIONS = src.BYPASS_CLUB_RESTRICTIONS,
            tgt.RENTERS_INSURANCE_INTEREST = src.RENTERS_INSURANCE_INTEREST,
            tgt.COUPON_ID = src.COUPON_ID,
            tgt.COUPON_TYPE = src.COUPON_TYPE,
            tgt.COUPON_AMOUNT = src.COUPON_AMOUNT,
            tgt.DISCOUNT_TOTAL = src.DISCOUNT_TOTAL,
            tgt.AGENT_ID = src.AGENT_ID,
            tgt.AGENT_NAME = src.AGENT_NAME,
            tgt.REFERRER_ID = src.REFERRER_ID,
            tgt.SAFETY_REMINDER = src.SAFETY_REMINDER,
            tgt.DELETED_ADMIN_ID = src.DELETED_ADMIN_ID,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.FINALIZED_AT = src.FINALIZED_AT,
            tgt.DELETED_AT = src.DELETED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
        WHERE 
            -- Only update if data has actually changed
            NVL(tgt.LOCATION_ID, -1) != NVL(src.LOCATION_ID, -1)
            OR NVL(tgt.CUSTOMER_ID, -1) != NVL(src.CUSTOMER_ID, -1)
            OR NVL(tgt.CREATOR_ID, -1) != NVL(src.CREATOR_ID, -1)
            OR NVL(tgt.ADMIN_ID, -1) != NVL(src.ADMIN_ID, -1)
            OR NVL(tgt.BILLING_FIRST_NAME, '~') != NVL(src.BILLING_FIRST_NAME, '~')
            OR NVL(tgt.BILLING_LAST_NAME, '~') != NVL(src.BILLING_LAST_NAME, '~')
            OR NVL(tgt.BILLING_STREET1, '~') != NVL(src.BILLING_STREET1, '~')
            OR NVL(tgt.BILLING_STREET2, '~') != NVL(src.BILLING_STREET2, '~')
            OR NVL(tgt.BILLING_CITY, '~') != NVL(src.BILLING_CITY, '~')
            OR NVL(tgt.BILLING_STATE, '~') != NVL(src.BILLING_STATE, '~')
            OR NVL(tgt.BILLING_COUNTRY, -1) != NVL(src.BILLING_COUNTRY, -1)
            OR NVL(tgt.BILLING_ZIP, '~') != NVL(src.BILLING_ZIP, '~')
            OR NVL(tgt.CC_SAVED_NAME, '~') != NVL(src.CC_SAVED_NAME, '~')
            OR NVL(tgt.CC_SAVED_LAST4, '~') != NVL(src.CC_SAVED_LAST4, '~')
            OR NVL(tgt.CC_SAVED_PROFILE_ID, -1) != NVL(src.CC_SAVED_PROFILE_ID, -1)
            OR NVL(tgt.CC_SAVED_METHOD_ID, -1) != NVL(src.CC_SAVED_METHOD_ID, -1)
            OR NVL(tgt.CC_SAVED_ADDRESS_ID, -1) != NVL(src.CC_SAVED_ADDRESS_ID, -1)
            OR NVL(tgt.CC_PREAUTH_ID, -1) != NVL(src.CC_PREAUTH_ID, -1)
            OR NVL(tgt.CC_PREAUTH_AMOUNT, -1) != NVL(src.CC_PREAUTH_AMOUNT, -1)
            OR NVL(tgt.CC_CONNECT_TYPE, '~') != NVL(src.CC_CONNECT_TYPE, '~')
            OR NVL(tgt.CC_CONNECT_ID, -1) != NVL(src.CC_CONNECT_ID, -1)
            OR NVL(tgt.ACCESSORIES_CUSTOM_PRICE, -1) != NVL(src.ACCESSORIES_CUSTOM_PRICE, -1)
            OR NVL(tgt.ACCESSORIES_TOTAL, '~') != NVL(src.ACCESSORIES_TOTAL, '~')
            OR NVL(tgt.INSURANCE_AMOUNT, -1) != NVL(src.INSURANCE_AMOUNT, -1)
            OR NVL(tgt.PETS, '~') != NVL(src.PETS, '~')
            OR NVL(tgt.PARKING, '~') != NVL(src.PARKING, '~')
            OR NVL(tgt.PARKING_OVERRIDE, '~') != NVL(src.PARKING_OVERRIDE, '~')
            OR NVL(tgt.BOATS_TOTAL, '~') != NVL(src.BOATS_TOTAL, '~')
            OR NVL(tgt.POS_TOTAL, '~') != NVL(src.POS_TOTAL, '~')
            OR NVL(tgt.USE_CLUB_CREDITS, '~') != NVL(src.USE_CLUB_CREDITS, '~')
            OR NVL(tgt.NO_SHOW_FEE, -1) != NVL(src.NO_SHOW_FEE, -1)
            OR NVL(tgt.CANCELLATION_FEE, -1) != NVL(src.CANCELLATION_FEE, -1)
            OR NVL(tgt.CLUB_FEES, -1) != NVL(src.CLUB_FEES, -1)
            OR NVL(tgt.CLUB_FEES_OVERRIDE, -1) != NVL(src.CLUB_FEES_OVERRIDE, -1)
            OR NVL(tgt.SUB_TOTAL, '~') != NVL(src.SUB_TOTAL, '~')
            OR NVL(tgt.CONVENIENCE_FEE, -1) != NVL(src.CONVENIENCE_FEE, -1)
            OR NVL(tgt.CONVENIENCE_FEE_WAIVED, -1) != NVL(src.CONVENIENCE_FEE_WAIVED, -1)
            OR NVL(tgt.INTERNAL_APPLICATION_FEE, -1) != NVL(src.INTERNAL_APPLICATION_FEE, -1)
            OR NVL(tgt.TAX_1, -1) != NVL(src.TAX_1, -1)
            OR NVL(tgt.TAX_1_EXEMPT, -1) != NVL(src.TAX_1_EXEMPT, -1)
            OR NVL(tgt.TAX_1_RATE_OVERRIDE, -1) != NVL(src.TAX_1_RATE_OVERRIDE, -1)
            OR NVL(tgt.TAX_2, -1) != NVL(src.TAX_2, -1)
            OR NVL(tgt.TAX_2_EXEMPT, -1) != NVL(src.TAX_2_EXEMPT, -1)
            OR NVL(tgt.CHECK_IN_TAX_1, -1) != NVL(src.CHECK_IN_TAX_1, -1)
            OR NVL(tgt.CHECK_IN_TAX_2, -1) != NVL(src.CHECK_IN_TAX_2, -1)
            OR NVL(tgt.CHECK_IN_TOTAL, '~') != NVL(src.CHECK_IN_TOTAL, '~')
            OR NVL(tgt.DEPOSIT_TOTAL, '~') != NVL(src.DEPOSIT_TOTAL, '~')
            OR NVL(tgt.DEPOSIT_OVERRIDE, '~') != NVL(src.DEPOSIT_OVERRIDE, '~')
            OR NVL(tgt.DEPOSIT_WAIVED, '~') != NVL(src.DEPOSIT_WAIVED, '~')
            OR NVL(tgt.GRATUITY, '~') != NVL(src.GRATUITY, '~')
            OR NVL(tgt.GRAND_TOTAL, '~') != NVL(src.GRAND_TOTAL, '~')
            OR NVL(tgt.ADJUSTMENT_TOTAL, '~') != NVL(src.ADJUSTMENT_TOTAL, '~')
            OR NVL(tgt.AMOUNT_PAID, -1) != NVL(src.AMOUNT_PAID, -1)
            OR NVL(tgt.NOTES, '~') != NVL(src.NOTES, '~')
            OR NVL(tgt.NOTES_CONTRACT, '~') != NVL(src.NOTES_CONTRACT, '~')
            OR NVL(tgt.NOTES_FROM_CUSTOMER, '~') != NVL(src.NOTES_FROM_CUSTOMER, '~')
            OR NVL(tgt.NOTES_FROM_CUSTOMER_CONTRACT, '~') != NVL(src.NOTES_FROM_CUSTOMER_CONTRACT, '~')
            OR NVL(tgt.NOTES_FOR_CUSTOMER, '~') != NVL(src.NOTES_FOR_CUSTOMER, '~')
            OR NVL(tgt.NOTES_FOR_CUSTOMER_CONTRACT, '~') != NVL(src.NOTES_FOR_CUSTOMER_CONTRACT, '~')
            OR NVL(tgt.FRONTEND, '~') != NVL(src.FRONTEND, '~')
            OR NVL(tgt.IS_ON_HOLD, '~') != NVL(src.IS_ON_HOLD, '~')
            OR NVL(tgt.IS_LOCKED, '~') != NVL(src.IS_LOCKED, '~')
            OR NVL(tgt.IS_FINALIZED, '~') != NVL(src.IS_FINALIZED, '~')
            OR NVL(tgt.IS_CANCELED, '~') != NVL(src.IS_CANCELED, '~')
            OR NVL(tgt.OVERRIDE_TURNAROUND_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.OVERRIDE_TURNAROUND_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CANCELLATION_TYPE, '~') != NVL(src.CANCELLATION_TYPE, '~')
            OR NVL(tgt.BYPASS_CLUB_RESTRICTIONS, '~') != NVL(src.BYPASS_CLUB_RESTRICTIONS, '~')
            OR NVL(tgt.RENTERS_INSURANCE_INTEREST, '~') != NVL(src.RENTERS_INSURANCE_INTEREST, '~')
            OR NVL(tgt.COUPON_ID, -1) != NVL(src.COUPON_ID, -1)
            OR NVL(tgt.COUPON_TYPE, '~') != NVL(src.COUPON_TYPE, '~')
            OR NVL(tgt.COUPON_AMOUNT, -1) != NVL(src.COUPON_AMOUNT, -1)
            OR NVL(tgt.DISCOUNT_TOTAL, -1) != NVL(src.DISCOUNT_TOTAL, -1)
            OR NVL(tgt.AGENT_ID, -1) != NVL(src.AGENT_ID, -1)
            OR NVL(tgt.AGENT_NAME, '~') != NVL(src.AGENT_NAME, '~')
            OR NVL(tgt.REFERRER_ID, -1) != NVL(src.REFERRER_ID, -1)
            OR NVL(tgt.SAFETY_REMINDER, '~') != NVL(src.SAFETY_REMINDER, '~')
            OR NVL(tgt.DELETED_ADMIN_ID, -1) != NVL(src.DELETED_ADMIN_ID, -1)
            OR NVL(tgt.CREATED_AT, '~') != NVL(src.CREATED_AT, '~')
            OR NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.FINALIZED_AT, '~') != NVL(src.FINALIZED_AT, '~')
            OR NVL(tgt.DELETED_AT, '~') != NVL(src.DELETED_AT, '~')
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, CUSTOMER_ID, CREATOR_ID, ADMIN_ID, BILLING_FIRST_NAME, BILLING_LAST_NAME, BILLING_STREET1, BILLING_STREET2, BILLING_CITY, BILLING_STATE, BILLING_COUNTRY, BILLING_ZIP, CC_SAVED_NAME, CC_SAVED_LAST4, CC_SAVED_PROFILE_ID, CC_SAVED_METHOD_ID, CC_SAVED_ADDRESS_ID, CC_PREAUTH_ID, CC_PREAUTH_AMOUNT, CC_CONNECT_TYPE, CC_CONNECT_ID, ACCESSORIES_CUSTOM_PRICE, ACCESSORIES_TOTAL, INSURANCE_AMOUNT, PETS, PARKING, PARKING_OVERRIDE, BOATS_TOTAL, POS_TOTAL, USE_CLUB_CREDITS, NO_SHOW_FEE, CANCELLATION_FEE, CLUB_FEES, CLUB_FEES_OVERRIDE, SUB_TOTAL, CONVENIENCE_FEE, CONVENIENCE_FEE_WAIVED, INTERNAL_APPLICATION_FEE, TAX_1, TAX_1_EXEMPT, TAX_1_RATE_OVERRIDE, TAX_2, TAX_2_EXEMPT, CHECK_IN_TAX_1, CHECK_IN_TAX_2, CHECK_IN_TOTAL, DEPOSIT_TOTAL, DEPOSIT_OVERRIDE, DEPOSIT_WAIVED, GRATUITY, GRAND_TOTAL, ADJUSTMENT_TOTAL, AMOUNT_PAID, NOTES, NOTES_CONTRACT, NOTES_FROM_CUSTOMER, NOTES_FROM_CUSTOMER_CONTRACT, NOTES_FOR_CUSTOMER, NOTES_FOR_CUSTOMER_CONTRACT, FRONTEND, IS_ON_HOLD, IS_LOCKED, IS_FINALIZED, IS_CANCELED, OVERRIDE_TURNAROUND_TIME, CANCELLATION_TYPE, BYPASS_CLUB_RESTRICTIONS, RENTERS_INSURANCE_INTEREST, COUPON_ID, COUPON_TYPE, COUPON_AMOUNT, DISCOUNT_TOTAL, AGENT_ID, AGENT_NAME, REFERRER_ID, SAFETY_REMINDER, DELETED_ADMIN_ID, CREATED_AT, UPDATED_AT, FINALIZED_AT, DELETED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.CUSTOMER_ID, src.CREATOR_ID, src.ADMIN_ID, src.BILLING_FIRST_NAME, src.BILLING_LAST_NAME, src.BILLING_STREET1, src.BILLING_STREET2, src.BILLING_CITY, src.BILLING_STATE, src.BILLING_COUNTRY, src.BILLING_ZIP, src.CC_SAVED_NAME, src.CC_SAVED_LAST4, src.CC_SAVED_PROFILE_ID, src.CC_SAVED_METHOD_ID, src.CC_SAVED_ADDRESS_ID, src.CC_PREAUTH_ID, src.CC_PREAUTH_AMOUNT, src.CC_CONNECT_TYPE, src.CC_CONNECT_ID, src.ACCESSORIES_CUSTOM_PRICE, src.ACCESSORIES_TOTAL, src.INSURANCE_AMOUNT, src.PETS, src.PARKING, src.PARKING_OVERRIDE, src.BOATS_TOTAL, src.POS_TOTAL, src.USE_CLUB_CREDITS, src.NO_SHOW_FEE, src.CANCELLATION_FEE, src.CLUB_FEES, src.CLUB_FEES_OVERRIDE, src.SUB_TOTAL, src.CONVENIENCE_FEE, src.CONVENIENCE_FEE_WAIVED, src.INTERNAL_APPLICATION_FEE, src.TAX_1, src.TAX_1_EXEMPT, src.TAX_1_RATE_OVERRIDE, src.TAX_2, src.TAX_2_EXEMPT, src.CHECK_IN_TAX_1, src.CHECK_IN_TAX_2, src.CHECK_IN_TOTAL, src.DEPOSIT_TOTAL, src.DEPOSIT_OVERRIDE, src.DEPOSIT_WAIVED, src.GRATUITY, src.GRAND_TOTAL, src.ADJUSTMENT_TOTAL, src.AMOUNT_PAID, src.NOTES, src.NOTES_CONTRACT, src.NOTES_FROM_CUSTOMER, src.NOTES_FROM_CUSTOMER_CONTRACT, src.NOTES_FOR_CUSTOMER, src.NOTES_FOR_CUSTOMER_CONTRACT, src.FRONTEND, src.IS_ON_HOLD, src.IS_LOCKED, src.IS_FINALIZED, src.IS_CANCELED, src.OVERRIDE_TURNAROUND_TIME, src.CANCELLATION_TYPE, src.BYPASS_CLUB_RESTRICTIONS, src.RENTERS_INSURANCE_INTEREST, src.COUPON_ID, src.COUPON_TYPE, src.COUPON_AMOUNT, src.DISCOUNT_TOTAL, src.AGENT_ID, src.AGENT_NAME, src.REFERRER_ID, src.SAFETY_REMINDER, src.DELETED_ADMIN_ID, src.CREATED_AT, src.UPDATED_AT, src.FINALIZED_AT, src.DELETED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_BOOKINGS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_BOOKINGS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_BOOKINGS;
/
