
-- ============================================================================
-- Merge STG_STELLAR_BOOKING_PAYMENTS to DW_STELLAR_BOOKING_PAYMENTS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_BOOKING_PAYMENTS
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    MERGE INTO DW_STELLAR_BOOKING_PAYMENTS tgt
    USING STG_STELLAR_BOOKING_PAYMENTS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.BOOKING_ID = src.BOOKING_ID,
            tgt.CUSTOMER_ID = src.CUSTOMER_ID,
            tgt.ADMIN_ID = src.ADMIN_ID,
            tgt.FRONTEND = src.FRONTEND,
            tgt.PAYMENT_FOR = src.PAYMENT_FOR,
            tgt.PAYMENT_TYPE = src.PAYMENT_TYPE,
            tgt.CARD_TYPE = src.CARD_TYPE,
            tgt.PAYMENT_TOTAL = src.PAYMENT_TOTAL,
            tgt.CASH_TOTAL = src.CASH_TOTAL,
            tgt.CREDIT_TOTAL = src.CREDIT_TOTAL,
            tgt.AGENT_AR_TOTAL = src.AGENT_AR_TOTAL,
            tgt.CREDIT_LAST4 = src.CREDIT_LAST4,
            tgt.CREDIT_EXPIRY = src.CREDIT_EXPIRY,
            tgt.BILLING_FIRST_NAME = src.BILLING_FIRST_NAME,
            tgt.BILLING_LAST_NAME = src.BILLING_LAST_NAME,
            tgt.BILLING_STREET1 = src.BILLING_STREET1,
            tgt.BILLING_STREET2 = src.BILLING_STREET2,
            tgt.BILLING_CITY = src.BILLING_CITY,
            tgt.BILLING_STATE = src.BILLING_STATE,
            tgt.BILLING_COUNTRY = src.BILLING_COUNTRY,
            tgt.BILLING_ZIP = src.BILLING_ZIP,
            tgt.TRANS_ID = src.TRANS_ID,
            tgt.ORIGINAL_PAYMENT_ID = src.ORIGINAL_PAYMENT_ID,
            tgt.STATUS_PAYMENT = src.STATUS_PAYMENT,
            tgt.NOTES = src.NOTES,
            tgt.IS_AGENT_AR = src.IS_AGENT_AR,
            tgt.OFFLINE_TYPE = src.OFFLINE_TYPE,
            tgt.DOCK_MASTER_TICKET = src.DOCK_MASTER_TICKET,
            tgt.MY_TASK_IT_ID = src.MY_TASK_IT_ID,
            tgt.REPORT_BOATS = src.REPORT_BOATS,
            tgt.REPORT_PROPANE = src.REPORT_PROPANE,
            tgt.REPORT_ACCESSORIES = src.REPORT_ACCESSORIES,
            tgt.REPORT_PARKING = src.REPORT_PARKING,
            tgt.REPORT_INSURANCE = src.REPORT_INSURANCE,
            tgt.REPORT_FUEL = src.REPORT_FUEL,
            tgt.REPORT_DAMAGES = src.REPORT_DAMAGES,
            tgt.REPORT_CLEANING = src.REPORT_CLEANING,
            tgt.REPORT_LATE = src.REPORT_LATE,
            tgt.REPORT_OTHER = src.REPORT_OTHER,
            tgt.REPORT_DISCOUNT = src.REPORT_DISCOUNT,
            tgt.INTERNAL_APPLICATION_FEE = src.INTERNAL_APPLICATION_FEE,
            tgt.CC_PROCESSOR_FEE = src.CC_PROCESSOR_FEE,
            tgt.CC_BRAND = src.CC_BRAND,
            tgt.CC_COUNTRY = src.CC_COUNTRY,
            tgt.CC_FUNDING = src.CC_FUNDING,
            tgt.CC_CONNECT_TYPE = src.CC_CONNECT_TYPE,
            tgt.CC_CONNECT_ID = src.CC_CONNECT_ID,
            tgt.CC_PAYOUT_ID = src.CC_PAYOUT_ID,
            tgt.CC_PAYOUT_DATE = src.CC_PAYOUT_DATE,
            tgt.EXTERNAL_CHARGE_ID = src.EXTERNAL_CHARGE_ID,
            tgt.IS_SYNCED = src.IS_SYNCED,
            tgt.STRIPE_READER_ID = src.STRIPE_READER_ID,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DELETED_AT = src.DELETED_AT,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.ID, -999) <> NVL(src.ID, -999) OR
            NVL(tgt.BOOKING_ID, -999) <> NVL(src.BOOKING_ID, -999) OR
            NVL(tgt.CUSTOMER_ID, -999) <> NVL(src.CUSTOMER_ID, -999) OR
            NVL(tgt.ADMIN_ID, -999) <> NVL(src.ADMIN_ID, -999) OR
            NVL(tgt.FRONTEND, -999) <> NVL(src.FRONTEND, -999) OR
            NVL(tgt.PAYMENT_FOR, '~NULL~') <> NVL(src.PAYMENT_FOR, '~NULL~') OR
            NVL(tgt.PAYMENT_TYPE, '~NULL~') <> NVL(src.PAYMENT_TYPE, '~NULL~') OR
            NVL(tgt.CARD_TYPE, '~NULL~') <> NVL(src.CARD_TYPE, '~NULL~') OR
            NVL(tgt.PAYMENT_TOTAL, -999.999) <> NVL(src.PAYMENT_TOTAL, -999.999) OR
            NVL(tgt.CASH_TOTAL, -999.999) <> NVL(src.CASH_TOTAL, -999.999) OR
            NVL(tgt.CREDIT_TOTAL, -999.999) <> NVL(src.CREDIT_TOTAL, -999.999) OR
            NVL(tgt.AGENT_AR_TOTAL, -999.999) <> NVL(src.AGENT_AR_TOTAL, -999.999) OR
            NVL(tgt.CREDIT_LAST4, '~NULL~') <> NVL(src.CREDIT_LAST4, '~NULL~') OR
            NVL(tgt.CREDIT_EXPIRY, '~NULL~') <> NVL(src.CREDIT_EXPIRY, '~NULL~') OR
            NVL(tgt.BILLING_FIRST_NAME, '~NULL~') <> NVL(src.BILLING_FIRST_NAME, '~NULL~') OR
            NVL(tgt.BILLING_LAST_NAME, '~NULL~') <> NVL(src.BILLING_LAST_NAME, '~NULL~') OR
            NVL(tgt.BILLING_STREET1, '~NULL~') <> NVL(src.BILLING_STREET1, '~NULL~') OR
            NVL(tgt.BILLING_STREET2, '~NULL~') <> NVL(src.BILLING_STREET2, '~NULL~') OR
            NVL(tgt.BILLING_CITY, '~NULL~') <> NVL(src.BILLING_CITY, '~NULL~') OR
            NVL(tgt.BILLING_STATE, '~NULL~') <> NVL(src.BILLING_STATE, '~NULL~') OR
            NVL(tgt.BILLING_COUNTRY, '~NULL~') <> NVL(src.BILLING_COUNTRY, '~NULL~') OR
            NVL(tgt.BILLING_ZIP, '~NULL~') <> NVL(src.BILLING_ZIP, '~NULL~') OR
            NVL(tgt.TRANS_ID, '~NULL~') <> NVL(src.TRANS_ID, '~NULL~') OR
            NVL(tgt.ORIGINAL_PAYMENT_ID, -999) <> NVL(src.ORIGINAL_PAYMENT_ID, -999) OR
            NVL(tgt.STATUS_PAYMENT, '~NULL~') <> NVL(src.STATUS_PAYMENT, '~NULL~') OR
            NVL(tgt.IS_AGENT_AR, '~NULL~') <> NVL(src.IS_AGENT_AR, '~NULL~') OR
            NVL(tgt.OFFLINE_TYPE, '~NULL~') <> NVL(src.OFFLINE_TYPE, '~NULL~') OR
            NVL(tgt.MY_TASK_IT_ID, '~NULL~') <> NVL(src.MY_TASK_IT_ID, '~NULL~') OR
            NVL(tgt.REPORT_BOATS, -999.999) <> NVL(src.REPORT_BOATS, -999.999) OR
            NVL(tgt.REPORT_PROPANE, -999.999) <> NVL(src.REPORT_PROPANE, -999.999) OR
            NVL(tgt.REPORT_ACCESSORIES, -999.999) <> NVL(src.REPORT_ACCESSORIES, -999.999) OR
            NVL(tgt.REPORT_PARKING, -999.999) <> NVL(src.REPORT_PARKING, -999.999) OR
            NVL(tgt.REPORT_INSURANCE, -999.999) <> NVL(src.REPORT_INSURANCE, -999.999) OR
            NVL(tgt.REPORT_FUEL, -999.999) <> NVL(src.REPORT_FUEL, -999.999) OR
            NVL(tgt.REPORT_DAMAGES, -999.999) <> NVL(src.REPORT_DAMAGES, -999.999) OR
            NVL(tgt.REPORT_CLEANING, -999.999) <> NVL(src.REPORT_CLEANING, -999.999) OR
            NVL(tgt.REPORT_LATE, -999.999) <> NVL(src.REPORT_LATE, -999.999) OR
            NVL(tgt.REPORT_OTHER, -999.999) <> NVL(src.REPORT_OTHER, -999.999) OR
            NVL(tgt.REPORT_DISCOUNT, -999.999) <> NVL(src.REPORT_DISCOUNT, -999.999) OR
            NVL(tgt.INTERNAL_APPLICATION_FEE, -999.999) <> NVL(src.INTERNAL_APPLICATION_FEE, -999.999) OR
            NVL(tgt.CC_PROCESSOR_FEE, -999.999) <> NVL(src.CC_PROCESSOR_FEE, -999.999) OR
            NVL(tgt.CC_BRAND, '~NULL~') <> NVL(src.CC_BRAND, '~NULL~') OR
            NVL(tgt.CC_COUNTRY, '~NULL~') <> NVL(src.CC_COUNTRY, '~NULL~') OR
            NVL(tgt.CC_FUNDING, '~NULL~') <> NVL(src.CC_FUNDING, '~NULL~') OR
            NVL(tgt.CC_CONNECT_TYPE, '~NULL~') <> NVL(src.CC_CONNECT_TYPE, '~NULL~') OR
            NVL(tgt.CC_CONNECT_ID, '~NULL~') <> NVL(src.CC_CONNECT_ID, '~NULL~') OR
            NVL(tgt.CC_PAYOUT_ID, '~NULL~') <> NVL(src.CC_PAYOUT_ID, '~NULL~') OR
            NVL(tgt.CC_PAYOUT_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CC_PAYOUT_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.EXTERNAL_CHARGE_ID, '~NULL~') <> NVL(src.EXTERNAL_CHARGE_ID, '~NULL~') OR
            NVL(tgt.IS_SYNCED, -999) <> NVL(src.IS_SYNCED, -999) OR
            NVL(tgt.STRIPE_READER_ID, '~NULL~') <> NVL(src.STRIPE_READER_ID, '~NULL~') OR
            NVL(tgt.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.DELETED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.DELETED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))
        )
    WHEN NOT MATCHED THEN
        INSERT (
            ID, BOOKING_ID, CUSTOMER_ID, ADMIN_ID, FRONTEND, PAYMENT_FOR, PAYMENT_TYPE, CARD_TYPE, PAYMENT_TOTAL, CASH_TOTAL, CREDIT_TOTAL, AGENT_AR_TOTAL, CREDIT_LAST4, CREDIT_EXPIRY, BILLING_FIRST_NAME, BILLING_LAST_NAME, BILLING_STREET1, BILLING_STREET2, BILLING_CITY, BILLING_STATE, BILLING_COUNTRY, BILLING_ZIP, TRANS_ID, ORIGINAL_PAYMENT_ID, STATUS_PAYMENT, NOTES, IS_AGENT_AR, OFFLINE_TYPE, DOCK_MASTER_TICKET, MY_TASK_IT_ID, REPORT_BOATS, REPORT_PROPANE, REPORT_ACCESSORIES, REPORT_PARKING, REPORT_INSURANCE, REPORT_FUEL, REPORT_DAMAGES, REPORT_CLEANING, REPORT_LATE, REPORT_OTHER, REPORT_DISCOUNT, INTERNAL_APPLICATION_FEE, CC_PROCESSOR_FEE, CC_BRAND, CC_COUNTRY, CC_FUNDING, CC_CONNECT_TYPE, CC_CONNECT_ID, CC_PAYOUT_ID, CC_PAYOUT_DATE, EXTERNAL_CHARGE_ID, IS_SYNCED, STRIPE_READER_ID, CREATED_AT, UPDATED_AT, DELETED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.BOOKING_ID, src.CUSTOMER_ID, src.ADMIN_ID, src.FRONTEND, src.PAYMENT_FOR, src.PAYMENT_TYPE, src.CARD_TYPE, src.PAYMENT_TOTAL, src.CASH_TOTAL, src.CREDIT_TOTAL, src.AGENT_AR_TOTAL, src.CREDIT_LAST4, src.CREDIT_EXPIRY, src.BILLING_FIRST_NAME, src.BILLING_LAST_NAME, src.BILLING_STREET1, src.BILLING_STREET2, src.BILLING_CITY, src.BILLING_STATE, src.BILLING_COUNTRY, src.BILLING_ZIP, src.TRANS_ID, src.ORIGINAL_PAYMENT_ID, src.STATUS_PAYMENT, src.NOTES, src.IS_AGENT_AR, src.OFFLINE_TYPE, src.DOCK_MASTER_TICKET, src.MY_TASK_IT_ID, src.REPORT_BOATS, src.REPORT_PROPANE, src.REPORT_ACCESSORIES, src.REPORT_PARKING, src.REPORT_INSURANCE, src.REPORT_FUEL, src.REPORT_DAMAGES, src.REPORT_CLEANING, src.REPORT_LATE, src.REPORT_OTHER, src.REPORT_DISCOUNT, src.INTERNAL_APPLICATION_FEE, src.CC_PROCESSOR_FEE, src.CC_BRAND, src.CC_COUNTRY, src.CC_FUNDING, src.CC_CONNECT_TYPE, src.CC_CONNECT_ID, src.CC_PAYOUT_ID, src.CC_PAYOUT_DATE, src.EXTERNAL_CHARGE_ID, src.IS_SYNCED, src.STRIPE_READER_ID, src.CREATED_AT, src.UPDATED_AT, src.DELETED_AT,
            v_timestamp,
            v_timestamp
        );
    
    -- Count inserts and updates
    SELECT COUNT(*) INTO v_inserted 
    FROM DW_STELLAR_BOOKING_PAYMENTS 
    WHERE DW_LAST_INSERTED = v_timestamp;
    
    SELECT COUNT(*) INTO v_updated 
    FROM DW_STELLAR_BOOKING_PAYMENTS 
    WHERE DW_LAST_UPDATED = v_timestamp 
    AND DW_LAST_INSERTED < v_timestamp;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_BOOKING_PAYMENTS: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_BOOKING_PAYMENTS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_BOOKING_PAYMENTS;
/
