
-- ============================================================================
-- Master Procedure: Execute All MOLO and Stellar Merges
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_RUN_ALL_MOLO_STELLAR_MERGES
IS
    v_start_time TIMESTAMP;
    v_end_time TIMESTAMP;
    v_duration NUMBER;
BEGIN
    v_start_time := SYSTIMESTAMP;
    
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('STARTING MERGE: STG_* -> DW_* Tables');
    DBMS_OUTPUT.PUT_LINE('========================================');
    
    -- MOLO Merges
    DBMS_OUTPUT.PUT_LINE('--- Processing MOLO Tables ---');
    SP_MERGE_MOLO_ACCOUNT_STATUS;
    SP_MERGE_MOLO_ACCOUNTS;
    SP_MERGE_MOLO_ADDRESS_TYPES;
    SP_MERGE_MOLO_BOATS;
    SP_MERGE_MOLO_BOAT_TYPES;
    SP_MERGE_MOLO_CITIES;
    SP_MERGE_MOLO_COMPANIES;
    SP_MERGE_MOLO_CONTACT_AUTO_CHARGE;
    SP_MERGE_MOLO_CONTACTS;
    SP_MERGE_MOLO_CONTACT_TYPES;
    SP_MERGE_MOLO_COUNTRIES;
    SP_MERGE_MOLO_CURRENCIES;
    SP_MERGE_MOLO_DUE_DATE_SETTINGS;
    SP_MERGE_MOLO_EQUIPMENT_FUEL_TYPES;
    SP_MERGE_MOLO_EQUIPMENT_TYPES;
    SP_MERGE_MOLO_INSTALLMENTS_PAYMENT_METHODS;
    SP_MERGE_MOLO_INSURANCE_STATUS;
    SP_MERGE_MOLO_INVOICE_ITEMS;
    SP_MERGE_MOLO_INVOICES;
    SP_MERGE_MOLO_INVOICE_STATUS;
    SP_MERGE_MOLO_INVOICE_TYPES;
    SP_MERGE_MOLO_INVOICE_ITEM_TYPES;
    SP_MERGE_MOLO_ITEM_CHARGE_METHODS;
    SP_MERGE_MOLO_ITEM_MASTERS;
    SP_MERGE_MOLO_MARINA_LOCATIONS;
    SP_MERGE_MOLO_PAYMENT_METHODS;
    SP_MERGE_MOLO_PAYMENTS_PROVIDER;
    SP_MERGE_MOLO_PHONE_TYPES;
    SP_MERGE_MOLO_PIERS;
    SP_MERGE_MOLO_POWER_NEEDS;
    SP_MERGE_MOLO_RECORD_STATUS;
    SP_MERGE_MOLO_RECURRING_INVOICE_OPTIONS;
    SP_MERGE_MOLO_RESERVATIONS;
    SP_MERGE_MOLO_RESERVATION_STATUS;
    SP_MERGE_MOLO_RESERVATION_TYPES;
    SP_MERGE_MOLO_SEASONAL_CHARGE_METHODS;
    SP_MERGE_MOLO_SEASONAL_INVOICING_METHODS;
    SP_MERGE_MOLO_SEASONAL_PRICES;
    SP_MERGE_MOLO_SLIPS;
    SP_MERGE_MOLO_SLIP_TYPES;
    SP_MERGE_MOLO_STATEMENTS_PREFERENCE;
    SP_MERGE_MOLO_TRANSACTION_METHODS;
    SP_MERGE_MOLO_TRANSACTIONS;
    SP_MERGE_MOLO_TRANSACTION_TYPES;
    SP_MERGE_MOLO_TRANSIENT_CHARGE_METHODS;
    SP_MERGE_MOLO_TRANSIENT_INVOICING_METHODS;
    SP_MERGE_MOLO_TRANSIENT_PRICES;
    SP_MERGE_MOLO_VESSEL_ENGINE_CLASS;
    
    -- Stellar Merges
    DBMS_OUTPUT.PUT_LINE('--- Processing Stellar Tables ---');
    SP_MERGE_STELLAR_CUSTOMERS;
    SP_MERGE_STELLAR_LOCATIONS;
    SP_MERGE_STELLAR_SEASONS;
    SP_MERGE_STELLAR_ACCESSORIES;
    SP_MERGE_STELLAR_ACCESSORY_OPTIONS;
    SP_MERGE_STELLAR_ACCESSORY_TIERS;
    SP_MERGE_STELLAR_AMENITIES;
    SP_MERGE_STELLAR_CATEGORIES;
    SP_MERGE_STELLAR_HOLIDAYS;
    SP_MERGE_STELLAR_BOOKINGS;
    SP_MERGE_STELLAR_BOOKING_BOATS;
    SP_MERGE_STELLAR_BOOKING_PAYMENTS;
    SP_MERGE_STELLAR_BOOKING_ACCESSORIES;
    SP_MERGE_STELLAR_STYLE_GROUPS;
    SP_MERGE_STELLAR_STYLES;
    SP_MERGE_STELLAR_STYLE_BOATS;
    SP_MERGE_STELLAR_CUSTOMER_BOATS;
    SP_MERGE_STELLAR_SEASON_DATES;
    SP_MERGE_STELLAR_STYLE_HOURLY_PRICES;
    SP_MERGE_STELLAR_STYLE_TIMES;
    SP_MERGE_STELLAR_STYLE_PRICES;
    SP_MERGE_STELLAR_CLUB_TIERS;
    SP_MERGE_STELLAR_COUPONS;
    SP_MERGE_STELLAR_POS_ITEMS;
    SP_MERGE_STELLAR_POS_SALES;
    SP_MERGE_STELLAR_FUEL_SALES;
    SP_MERGE_STELLAR_WAITLISTS;
    SP_MERGE_STELLAR_CLOSED_DATES;
    SP_MERGE_STELLAR_BLACKLISTS;
    
    v_end_time := SYSTIMESTAMP;
    v_duration := EXTRACT(SECOND FROM (v_end_time - v_start_time));
    
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('ALL MERGES COMPLETED');
    DBMS_OUTPUT.PUT_LINE('Duration: ' || ROUND(v_duration, 2) || ' seconds');
    DBMS_OUTPUT.PUT_LINE('========================================');
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        RAISE;
END SP_RUN_ALL_MOLO_STELLAR_MERGES;
/
